// Code generated by scripts/generate-agent-lanes.py; DO NOT EDIT.
export const laneRegistryManifestDigest = "sha256:e1c56a7950cf11215f4c3ded6b4156bf8f2c69912cfb8bfe22976a6fd62bfc44" as const;
export const agentLanes = [
  {
    "id": "research",
    "version": 1,
    "purpose": "Investigate bounded questions and return source-backed findings.",
    "capability_class": "research",
    "capabilities": [
      "read_repository",
      "search_public_sources",
      "cite_evidence"
    ],
    "packet_schema_ref": "agent-lane-packet.v1",
    "report_schema_ref": "agent-lane-report.v1",
    "budgets": {
      "cost_usd_max": 2,
      "context_tokens_max": 32000,
      "time_seconds_max": 900
    },
    "evidence_obligations": [
      "source_citations",
      "bounded_findings",
      "uncertainties"
    ],
    "lifecycle_states": [
      "dispatched",
      "completed",
      "failed"
    ],
    "pinned_model": "openai/gpt-5.6-luna",
    "digest": "sha256:e44e36a88bcd2ddc0d144423bcc6b4339c95b92aa44d273b94e49ee0e20901fb"
  },
  {
    "id": "implement",
    "version": 1,
    "purpose": "Implement one approved bounded engineering task and report verification.",
    "capability_class": "implementation",
    "capabilities": [
      "read_repository",
      "edit_scoped_files",
      "run_tests",
      "report_evidence"
    ],
    "packet_schema_ref": "agent-lane-packet.v1",
    "report_schema_ref": "agent-lane-report.v1",
    "budgets": {
      "cost_usd_max": 4,
      "context_tokens_max": 48000,
      "time_seconds_max": 1800
    },
    "evidence_obligations": [
      "files_touched",
      "verification_commands",
      "unresolved_issues"
    ],
    "lifecycle_states": [
      "dispatched",
      "completed",
      "failed"
    ],
    "pinned_model": "openai/gpt-5.6-luna",
    "digest": "sha256:84f204c2145897411b16e16f5d6d099ee792213042aecb01f59059090636de85"
  },
  {
    "id": "review",
    "version": 1,
    "purpose": "Review a bounded change against its contract and acceptance evidence.",
    "capability_class": "review",
    "capabilities": [
      "read_repository",
      "inspect_diff",
      "run_targeted_checks",
      "report_findings"
    ],
    "packet_schema_ref": "agent-lane-packet.v1",
    "report_schema_ref": "agent-lane-report.v1",
    "budgets": {
      "cost_usd_max": 2.5,
      "context_tokens_max": 40000,
      "time_seconds_max": 1200
    },
    "evidence_obligations": [
      "contract_findings",
      "severity",
      "verification_commands"
    ],
    "lifecycle_states": [
      "dispatched",
      "completed",
      "failed"
    ],
    "pinned_model": "zai-coding-plan/glm-5.3",
    "digest": "sha256:cc4d20f113f1bd0a1587afe400b3c3e5421536814efc177bbdda8a4572e53a56"
  },
  {
    "id": "verify",
    "version": 1,
    "purpose": "Run independent verification and return deterministic pass or failure evidence.",
    "capability_class": "verification",
    "capabilities": [
      "read_repository",
      "run_tests",
      "run_validators",
      "report_evidence"
    ],
    "packet_schema_ref": "agent-lane-packet.v1",
    "report_schema_ref": "agent-lane-report.v1",
    "budgets": {
      "cost_usd_max": 3,
      "context_tokens_max": 40000,
      "time_seconds_max": 1500
    },
    "evidence_obligations": [
      "commands",
      "exit_codes",
      "failure_classification"
    ],
    "lifecycle_states": [
      "dispatched",
      "completed",
      "failed"
    ],
    "pinned_model": "openai/gpt-5.6-luna",
    "digest": "sha256:27aa54758f4c90542c1e7d0da567e68bd79f8476cf50fa1590849be29a8a7f4c"
  }
] as const;
export const agentLanePacketSchema = {"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://raw.githubusercontent.com/Sharper-Flow/concord/main/contracts/agent-lane-packet.schema.json","title":"Concord agent lane packet v1","type":"object","additionalProperties":false,"required":["schema_version","attempt_id","lane_id","lane_version","lane_digest","work_id","step_id","inputs"],"properties":{"schema_version":{"const":"1.0"},"attempt_id":{"type":"string","minLength":2,"maxLength":128},"lane_id":{"type":"string","minLength":2,"maxLength":32},"lane_version":{"type":"integer","minimum":1,"maximum":2147483647},"lane_digest":{"type":"string","minLength":71,"maxLength":71,"pattern":"^sha256:[0-9a-f]{64}$"},"work_id":{"type":"string","minLength":1,"maxLength":128},"step_id":{"type":"string","minLength":1,"maxLength":128},"inputs":{"type":"object","additionalProperties":false,"required":["task"],"properties":{"task":{"type":"string","minLength":1,"maxLength":4096},"context":{"type":"string","minLength":0,"maxLength":16384},"constraints":{"type":"array","minItems":0,"maxItems":64,"items":{"type":"string","minLength":1,"maxLength":512}}}}}} as const;
export const routingPolicyManifestDigest = "sha256:34718d4f686c90b4806533ad1cc9eb1eab7c3cce0f4e732dcdaa70d73aa9f736" as const;
export const routingPolicyVersion = "routing-v1" as const;
export const routingPolicies = [
  {
    "capability_class": "research",
    "preferred_model": "openai/gpt-5.6-luna",
    "resolution_set": [
      "openai/gpt-5.6-luna",
      "zai-coding-plan/glm-5.3"
    ]
  },
  {
    "capability_class": "implementation",
    "preferred_model": "openai/gpt-5.6-luna",
    "resolution_set": [
      "openai/gpt-5.6-luna",
      "zai-coding-plan/glm-5.3"
    ]
  },
  {
    "capability_class": "review",
    "preferred_model": "zai-coding-plan/glm-5.3",
    "resolution_set": [
      "zai-coding-plan/glm-5.3",
      "kimi-for-coding/k3"
    ]
  },
  {
    "capability_class": "verification",
    "preferred_model": "openai/gpt-5.6-luna",
    "resolution_set": [
      "openai/gpt-5.6-luna",
      "zai-coding-plan/glm-5.3"
    ]
  }
] as const;
export type AgentLane = (typeof agentLanes)[number];
