// Code generated by scripts/generate-lane-step-dispatch.py; DO NOT EDIT.
export const laneStepDispatchManifestDigest = "sha256:2a4432afc029a28f6e553cfd92ee4c8906f096914912db6b49ca5883fa181ab6" as const;
export const laneStepDispatchKinds = {
  "design": [
    "external_effect"
  ],
  "implementation": [
    "external_effect"
  ],
  "research": [
    "internal_sqlite",
    "cross_authority"
  ],
  "review": [
    "cross_authority",
    "external_effect",
    "human_checkpoint",
    "internal_sqlite"
  ],
  "verification": [
    "external_effect"
  ]
} as const;
