// Code generated by scripts/generate-lane-step-dispatch.py; DO NOT EDIT.
export const laneStepDispatchManifestDigest = "sha256:943d1cadccdeed59180f9864d31d4410e1dcdb28b7138c2ea33acb85a6a1b4b3" as const;
export const laneStepDispatchKinds = {
  "design": [
    "external_effect"
  ],
  "implementation": [
    "external_effect"
  ],
  "research": [
    "internal_sqlite",
    "cross_authority"
  ],
  "review": [
    "cross_authority",
    "external_effect",
    "internal_sqlite"
  ],
  "verification": [
    "external_effect"
  ]
} as const;
