import { test, expect, mock } from "bun:test"

// The lane dispatcher reaches the Opencode plugin through ToolContext (typed
// only) and the dispatch worker through dispatchWorker, but the test never
// executes the real plugin path. The stub mirrors concord.test.ts so the
// suite never loads the real host module.
function schemaBuilder() {
  return {
    optional() { return this }, strict() { return this }, min() { return this }, max() { return this }, int() { return this }, regex() { return this },
    meta() { return this },
  }
}
const fakeTool = Object.assign((config: any) => config, {
  schema: {
    object: schemaBuilder, array: schemaBuilder, record: schemaBuilder, union: schemaBuilder, literal: schemaBuilder,
    string: schemaBuilder, number: schemaBuilder, unknown: schemaBuilder, null: schemaBuilder,
  },
})
mock.module("@opencode-ai/plugin", () => ({ tool: fakeTool }))

const { agentLanes } = await import("./generated-agent-lanes")
const { validateAgentLanePacket } = await import("./dispatch")
import type { DispatchRunner } from "./dispatch"
import type { CredentialStore } from "./credentials"
const { dispatchLaneWorker } = await import("./lane_dispatch")
const { laneDispatchRequest } = await import("./concord")

const isRecord = (value: unknown): value is Record<string, unknown> => value !== null && typeof value === "object" && !Array.isArray(value)

const testCredentials: CredentialStore = { async getPrivateKey() { return new Uint8Array(32).fill(7) } }

const lane = agentLanes[1]
const WORK_ID = "work-dispatch"
const PRODUCT_ID = "product-dispatch"
const WORKFLOW_STEP = "execution"
const NARRATIVE = "Project lane identity, step, narrative, and obligations into the closed agent-lane-packet.v1."
const OUTCOME_KIND = "capability_available"
const OUTCOME_PAYLOAD = "A host-side builder projects durable state into the agent lane packet."
const NOW = 1_700_000_000_000

function envelope<T>(body: T): T & { schema_version: "1.0"; origin: "core" } {
  return { schema_version: "1.0", origin: "core", ...body } as T & { schema_version: "1.0"; origin: "core" }
}

const scopeEnvelope = () => envelope({
  tool: "concord_work_browse", operation: "scope", outcome: "ok", authority: "authoritative", freshness: null,
  result: {
    work: { id: WORK_ID, kind: "task", title: "Reachability: dispatch through work_transition", lifecycle: "in_progress", version: 1, priority: 0, project_ids: [PRODUCT_ID], ready: true, narrative: NARRATIVE, terminal_at: null },
    memberships: [{ project_id: PRODUCT_ID, role: "primary" }],
    items: [],
  },
})

const continuityEnvelope = (overrides: Partial<{ pinned: Record<string, unknown> }> = {}) => envelope({
  tool: "concord_work_trace", operation: "continuity", outcome: "ok", authority: "authoritative", freshness: null,
  result: {
    work_id: WORK_ID,
    pinned: {
      product_identity: [PRODUCT_ID],
      workflow_step: WORKFLOW_STEP,
      contract: {
        version: 1, premise: "Reachability test", outcome_predicates: [{ predicate_id: "predicate:primary", ordinal: 0, outcome_kind: OUTCOME_KIND, outcome_payload: OUTCOME_PAYLOAD }],
        required_evidence: [], route_conventions: [], spec_mandate: [], changes_product_truth: false,
      },
      spec_mandate: [], pending_operator_decision: null, latest_checkpoint: null, unresolved_failure: null,
      ...(overrides.pinned ?? {}),
    },
    latest_checkpoint: null, boundaries: { count: 0, items: [], next_cursor: null, watermark: "seq:1" },
    typed_availability: { restart: "unavailable", reason: "typed restart is deliberately excluded (CD-0027); pinned continuity is re-derived per call" },
    pending_messages: 0, observations: [],
  },
})

// CD-0067 D6: the dispatch_worker response must carry worker_packet_digest on
// result so the adapter can quote it on the signed evidence assertion. Every
// test that exercises the happy path uses this envelope; tests that probe
// the digest-missing refusal override result to an empty record.
const CORE_PACKET_DIGEST = "sha256:eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
const coreOkEnvelope = () => envelope({
  tool: "concord_work_transition", operation: "workflow_action", outcome: "ok", authority: "authoritative", freshness: null,
  result: { worker_packet_digest: CORE_PACKET_DIGEST },
})

const coreErrorEnvelope = (kind: string, message: string) => envelope({
  tool: "concord_work_transition", operation: "workflow_action", outcome: "error", authority: "authoritative", freshness: null,
  error: { kind, retry_safe: false, recovery_action: { kind: "reconcile_operation" }, effect_state: "none", message },
})

const READBACK_MODEL = "openai/gpt-5.6-luna"
// The attempt id is generated by dispatchLaneWorker from `now`, so the test
// computes the expected id and bakes it into the report the worker emits.
const expectedAttemptId = `attempt-${WORK_ID}-${lane.id}-${Math.max(0, Math.floor(NOW)).toString(16).padStart(12, "0")}`
const reportEvent = () => JSON.stringify({ type: "text", timestamp: 2, sessionID: "session-1", part: { type: "text", text: JSON.stringify({
  schema_version: "1.0", attempt_id: expectedAttemptId, lane_id: lane.id, lane_version: lane.version, lane_digest: lane.digest,
  readback_model: READBACK_MODEL, status: "completed",
  evidence: lane.evidence_obligations.map((obligation) => ({ obligation, detail: `discharged ${obligation}` })),
}) } })
const runOutput = () => [
  JSON.stringify({ type: "step_start", timestamp: 1, sessionID: "session-1", part: { type: "step-start" } }),
  reportEvent(),
  JSON.stringify({ type: "step_finish", timestamp: 3, sessionID: "session-1", part: { type: "step-finish", reason: "stop" } }),
].join("\n")
const exportedSession = () => JSON.stringify({
  info: { id: "session-1" },
  messages: [{ info: { id: "message-1", sessionID: "session-1", role: "assistant", agent: `concord-${lane.id}`, providerID: READBACK_MODEL.split("/")[0], modelID: READBACK_MODEL.split("/").slice(1).join("/"), time: { created: 1 } }, parts: [] }],
})

const contextFor = () => ({ sessionID: "session-1", messageID: "message-1", agent: "agent-1", worktree: "/worktree", directory: "/worktree", abort: new AbortController().signal, ask: async () => {} }) as any

test("routing selects the lane dispatcher for dispatch_worker with object-form fields and a string lane_id", () => {
  const request = laneDispatchRequest({ operation: "workflow_action", input: { work_id: WORK_ID, expected_version: 3, action_id: "dispatch_worker", idempotency_key: "idemp-1", fields: { lane_id: "research" } } })
  expect(request).toEqual({ work_id: WORK_ID, expected_version: 3, idempotency_key: "idemp-1", lane_id: "research" })
})

test("routing returns the typed error when fields.lane_id is missing", () => {
  expect(laneDispatchRequest({ operation: "workflow_action", input: { work_id: WORK_ID, expected_version: 3, action_id: "dispatch_worker", idempotency_key: "idemp-1", fields: { attempt_id: "attempt-1" } } })).toEqual({ error: "dispatch_worker requires fields.lane_id naming the target lane" })
  expect(laneDispatchRequest({ operation: "workflow_action", input: { work_id: WORK_ID, expected_version: 3, action_id: "dispatch_worker", idempotency_key: "idemp-1", fields: [{ name: "attempt_id", value: "attempt-1" }] } })).toEqual({ error: "dispatch_worker requires fields.lane_id naming the target lane" })
  expect(laneDispatchRequest({ operation: "workflow_action", input: { work_id: WORK_ID, expected_version: 3, action_id: "dispatch_worker", idempotency_key: "idemp-1" } })).toEqual({ error: "dispatch_worker requires fields.lane_id naming the target lane" })
})

test("routing returns null for non-dispatch_worker actions so the generic transport handles them", () => {
  expect(laneDispatchRequest({ operation: "workflow_action", input: { work_id: WORK_ID, expected_version: 3, action_id: "complete", idempotency_key: "idemp-1", fields: { impact_verdict: "non-breaking" } } })).toBeNull()
  expect(laneDispatchRequest({ operation: "snapshot", input: {} })).toBeNull()
  expect(laneDispatchRequest(undefined)).toBeNull()
  expect(laneDispatchRequest(null)).toBeNull()
})

test("happy path: continuity → packet → core ok → spawn with stubbed runners reaches the runner", async () => {
  const seen: string[] = []
  const workflowInput: { value?: Record<string, unknown> } = {}
  const invoke = async (toolName: string, args: { operation: string; input?: Record<string, unknown> }): Promise<unknown> => {
    const key = `${toolName}.${args.operation}`
    seen.push(key)
    if (key === "concord_work_trace.continuity") return continuityEnvelope()
    if (key === "concord_work_browse.scope") return scopeEnvelope()
    if (key === "concord_work_transition.workflow_action") { workflowInput.value = args.input; return coreOkEnvelope() }
    throw new Error(`unscripted ${key}`)
  }
  const runner: DispatchRunner = {
    async run(argv) {
      if (argv[1] === "run") return { exitCode: 0, stdout: runOutput(), stderr: "" }
      if (argv[1] === "export") return { exitCode: 0, stdout: exportedSession(), stderr: "" }
      return { exitCode: 0, stdout: "", stderr: "" }
    },
  }
  let evidenceCalls = 0
  const evidenceRunner: DispatchRunner = { async run() { evidenceCalls++; return { exitCode: 0, stdout: "", stderr: "" } } }
  const result = await dispatchLaneWorker({ work_id: WORK_ID, expected_version: 3, idempotency_key: "idemp-1", lane_id: lane.id }, { context: contextFor(), invoke: invoke as any, credentials: testCredentials, runner, evidenceRunner, now: () => NOW })
  expect(result.outcome).toBe("ok")
  expect(seen).toContain("concord_work_trace.continuity")
  expect(seen).toContain("concord_work_browse.scope")
  expect(seen).toContain("concord_work_transition.workflow_action")
  expect(isRecord(workflowInput.value)).toBe(true)
  const fields = (workflowInput.value as Record<string, unknown>).fields as Record<string, unknown>
  expect(typeof fields.attempt_id).toBe("string")
  const packet = fields.worker_packet as Record<string, unknown>
  expect(isRecord(packet)).toBe(true)
  expect(packet.lane_id).toBe(lane.id)
  expect(packet.work_id).toBe(WORK_ID)
  expect(packet.step_id).toBe(WORKFLOW_STEP)
  expect(packet.attempt_id).toBe(fields.attempt_id)
  expect(validateAgentLanePacket(packet)).toBe(true)
  expect(evidenceCalls).toBeGreaterThan(0)
})

test("unregistered lane refuses before any core invoke or spawn", async () => {
  let workflowCalls = 0
  const invoke = async (toolName: string, args: { operation: string; input?: Record<string, unknown> }): Promise<unknown> => {
    if (toolName === "concord_work_trace") return continuityEnvelope()
    if (toolName === "concord_work_transition") { workflowCalls++; return coreOkEnvelope() }
    throw new Error(`unscripted ${toolName}.${args.operation}`)
  }
  let spawned = 0
  const runner: DispatchRunner = { async run() { spawned++; return { exitCode: 0, stdout: "", stderr: "" } } }
  const result = await dispatchLaneWorker({ work_id: WORK_ID, expected_version: 1, idempotency_key: "idemp-2", lane_id: "summarize" }, { context: contextFor(), invoke: invoke as any, runner, now: () => NOW })
  expect(result.outcome).toBe("error")
  expect(result.error?.kind).toBe("invalid_input")
  expect(result.error?.message).toContain("summarize")
  expect(spawned).toBe(0)
  expect(workflowCalls).toBe(0)
})

test("core refusal on dispatch_worker surfaces as unauthorized_dispatch without spawn", async () => {
  let spawned = 0
  let workflowCalls = 0
  const invoke = async (toolName: string, args: { operation: string; input?: Record<string, unknown> }): Promise<unknown> => {
    if (toolName === "concord_work_trace") return continuityEnvelope()
    if (toolName === "concord_work_browse") return scopeEnvelope()
    if (toolName === "concord_work_transition") { workflowCalls++; return coreErrorEnvelope("unauthorized_dispatch", "no authorized dispatch window exists for this work item at the current step") }
    throw new Error(`unscripted ${toolName}.${args.operation}`)
  }
  const runner: DispatchRunner = { async run() { spawned++; return { exitCode: 0, stdout: "", stderr: "" } } }
  const result = await dispatchLaneWorker({ work_id: WORK_ID, expected_version: 1, idempotency_key: "idemp-3", lane_id: lane.id }, { context: contextFor(), invoke: invoke as any, runner, now: () => NOW })
  expect(result.outcome).toBe("error")
  expect(result.error?.kind).toBe("unauthorized_dispatch")
  expect(result.error?.message).toBe("no authorized dispatch window exists for this work item at the current step")
  expect(spawned).toBe(0)
  expect(workflowCalls).toBe(1)
})

// product_identity is the distinct product set across the work item's
// projects: zero or several is valid core state that dispatch cannot project
// from, so the refusal is blocked with a reconcile action, never a transport
// fault.
test("a work item with zero or several product identities is a blocked refusal without spawn", async () => {
  let spawned = 0
  let workflowCalls = 0
  const invoke = async (toolName: string, args: { operation: string; input?: Record<string, unknown> }): Promise<unknown> => {
    if (toolName === "concord_work_trace") return continuityEnvelope({ pinned: { product_identity: [], workflow_step: WORKFLOW_STEP, contract: {} } })
    if (toolName === "concord_work_transition") { workflowCalls++; return coreOkEnvelope() }
    throw new Error(`unscripted ${toolName}.${args.operation}`)
  }
  const runner: DispatchRunner = { async run() { spawned++; return { exitCode: 0, stdout: "", stderr: "" } } }
  const result = await dispatchLaneWorker({ work_id: WORK_ID, expected_version: 1, idempotency_key: "idemp-4", lane_id: lane.id }, { context: contextFor(), invoke: invoke as any, runner, now: () => NOW })
  expect(result.outcome).toBe("blocked")
  expect(result.error?.kind).toBe("invalid_input")
  expect(result.error?.message).toContain("0 product identities")
  expect(spawned).toBe(0)
  expect(workflowCalls).toBe(0)
})

test("mandate_unapproved refusal maps to outcome blocked", async () => {
  let spawned = 0
  let workflowCalls = 0
  const invoke = async (toolName: string, args: { operation: string; input?: Record<string, unknown> }): Promise<unknown> => {
    if (toolName === "concord_work_trace") {
      return continuityEnvelope({ pinned: { product_identity: [PRODUCT_ID], workflow_step: WORKFLOW_STEP, contract: null } })
    }
    if (toolName === "concord_work_browse") return scopeEnvelope()
    if (toolName === "concord_work_transition") { workflowCalls++; return coreOkEnvelope() }
    throw new Error(`unscripted ${toolName}.${args.operation}`)
  }
  const runner: DispatchRunner = { async run() { spawned++; return { exitCode: 0, stdout: "", stderr: "" } } }
  const result = await dispatchLaneWorker({ work_id: WORK_ID, expected_version: 1, idempotency_key: "idemp-5", lane_id: lane.id }, { context: contextFor(), invoke: invoke as any, runner, now: () => NOW })
  expect(result.outcome).toBe("blocked")
  expect(result.error?.kind).toBe("invalid_input")
  expect(result.error?.message).toContain("no pinned workflow contract")
  expect(spawned).toBe(0)
  expect(workflowCalls).toBe(0)
})

// CD-0067 D6: a core that answers ok without recording worker_packet_digest
// is not the core that authored the window — the dispatch_worker response
// surface must carry the digest the dispatch authorization recorded, or the
// adapter refuses with transport_failure so a hostile or misconfigured
// core cannot smuggle evidence past the gate. Spawn never executes.
test("dispatch_worker response without worker_packet_digest refuses before spawn", async () => {
  let spawned = 0
  const invoke = async (toolName: string, args: { operation: string; input?: Record<string, unknown> }): Promise<unknown> => {
    if (toolName === "concord_work_trace") return continuityEnvelope()
    if (toolName === "concord_work_browse") return scopeEnvelope()
    if (toolName === "concord_work_transition") return envelope({
      tool: "concord_work_transition", operation: "workflow_action", outcome: "ok", authority: "authoritative", freshness: null,
      // result is an empty record — the cutover break this regression guards.
      result: {},
    })
    throw new Error(`unscripted ${toolName}.${args.operation}`)
  }
  const runner: DispatchRunner = { async run() { spawned++; return { exitCode: 0, stdout: "", stderr: "" } } }
  const result = await dispatchLaneWorker({ work_id: WORK_ID, expected_version: 3, idempotency_key: "idemp-6", lane_id: lane.id }, { context: contextFor(), invoke: invoke as any, runner, now: () => NOW })
  expect(result.outcome).toBe("error")
  expect(result.error?.kind).toBe("transport_failure")
  expect(result.error?.message).toContain("worker_packet_digest")
  expect(result.error?.recovery_action).toBe("reconcile_operation")
  expect(spawned).toBe(0)
})

// CD-0067 D6: when the core records the digest, dispatchLaneWorker hands
// the same digest to dispatchWorker via the packetDigest option, and the
// signed dispatch assertion quotes it. The runner sees a worker-dispatch
// evidence write whose assertion carries worker_packet_digest == the core's
// recorded value.
test("dispatchLaneWorker hands the core's packet digest to dispatchWorker", async () => {
  const recorded: Record<string, unknown>[] = []
  const invoke = async (toolName: string, args: { operation: string; input?: Record<string, unknown> }): Promise<unknown> => {
    if (toolName === "concord_work_trace") return continuityEnvelope()
    if (toolName === "concord_work_browse") return scopeEnvelope()
    if (toolName === "concord_work_transition") return coreOkEnvelope()
    throw new Error(`unscripted ${toolName}.${args.operation}`)
  }
  const runner: DispatchRunner = {
    async run(argv) {
      if (argv[1] === "run") return { exitCode: 0, stdout: runOutput(), stderr: "" }
      if (argv[1] === "export") return { exitCode: 0, stdout: exportedSession(), stderr: "" }
      return { exitCode: 0, stdout: "", stderr: "" }
    },
  }
  const result = await dispatchLaneWorker({ work_id: WORK_ID, expected_version: 3, idempotency_key: "idemp-7", lane_id: lane.id }, { context: contextFor(), invoke: invoke as any, credentials: testCredentials, runner, evidenceRunner: { async run(argv, input) { recorded.push({ command: argv[1], request: JSON.parse(input) }); return { exitCode: 0, stdout: "", stderr: "" } } }, now: () => NOW })
  expect(result.outcome).toBe("ok")
  expect(recorded.map((entry) => entry.command)).toEqual(["worker-dispatch", "worker-complete"])
  const dispatched = (recorded[0].request as any).assertion
  expect(dispatched.packet_digest).toBe(CORE_PACKET_DIGEST)
})
