// Code generated by scripts/generate-agent-contracts.py; DO NOT EDIT.
package agent

const GeneratedPayloadSchemaDocument = `{
  "$defs": {
    "approval": {
      "additionalProperties": false,
      "properties": {
        "approval_ref": {
          "$ref": "#/$defs/id"
        }
      },
      "required": [
        "approval_ref"
      ],
      "type": "object"
    },
    "blocked_work_page": {
      "additionalProperties": false,
      "properties": {
        "edges": {
          "items": {
            "additionalProperties": false,
            "properties": {
              "from": {
                "$ref": "#/$defs/id"
              },
              "kind": {
                "enum": [
                  "blocks",
                  "parent"
                ],
                "type": "string"
              },
              "to": {
                "$ref": "#/$defs/id"
              }
            },
            "required": [
              "from",
              "to",
              "kind"
            ],
            "type": "object"
          },
          "maxItems": 200,
          "type": "array"
        },
        "items": {
          "items": {
            "$ref": "#/$defs/work_summary"
          },
          "maxItems": 100,
          "type": "array"
        },
        "next_cursor": {
          "$ref": "#/$defs/cursor"
        },
        "nodes": {
          "items": {
            "$ref": "#/$defs/work_summary"
          },
          "maxItems": 100,
          "type": "array"
        }
      },
      "required": [
        "items",
        "nodes",
        "edges"
      ],
      "type": "object"
    },
    "budget": {
      "additionalProperties": false,
      "properties": {
        "max_bytes": {
          "maximum": 65536,
          "minimum": 1,
          "type": "integer"
        },
        "max_items": {
          "maximum": 100,
          "minimum": 1,
          "type": "integer"
        },
        "max_millis": {
          "maximum": 300000,
          "minimum": 1,
          "type": "integer"
        }
      },
      "required": [
        "max_bytes",
        "max_items"
      ],
      "type": "object"
    },
    "canonical_note_result": {
      "additionalProperties": false,
      "properties": {
        "candidates": {
          "items": {
            "$ref": "#/$defs/id"
          },
          "maxItems": 20,
          "type": "array",
          "uniqueItems": true
        },
        "locator": {
          "maxLength": 2048,
          "type": [
            "string",
            "null"
          ]
        },
        "state": {
          "enum": [
            "canonical",
            "not_compacted",
            "missing",
            "ambiguous"
          ],
          "type": "string"
        }
      },
      "required": [
        "state"
      ],
      "type": "object"
    },
    "cursor": {
      "maxLength": 4096,
      "type": [
        "string",
        "null"
      ]
    },
    "detail": {
      "enum": [
        "summary",
        "full"
      ],
      "type": "string"
    },
    "digest": {
      "maxLength": 128,
      "minLength": 8,
      "pattern": "^(sha256:)?[0-9a-fA-F]{8,}$",
      "type": "string"
    },
    "direction": {
      "enum": [
        "outgoing",
        "incoming",
        "both"
      ],
      "type": "string"
    },
    "evidence": {
      "additionalProperties": false,
      "properties": {
        "authority": {
          "$ref": "#/$defs/short"
        },
        "digest": {
          "$ref": "#/$defs/digest"
        },
        "kind": {
          "enum": [
            "verification",
            "review",
            "approval",
            "commit",
            "durable_note",
            "native_run",
            "artifact"
          ],
          "type": "string"
        },
        "locator": {
          "maxLength": 2048,
          "minLength": 1,
          "type": "string"
        },
        "locator_kind": {
          "$ref": "#/$defs/short"
        },
        "version": {
          "maxLength": 256,
          "type": "string"
        }
      },
      "required": [
        "kind",
        "authority",
        "locator_kind",
        "locator"
      ],
      "type": "object"
    },
    "field": {
      "additionalProperties": false,
      "properties": {
        "name": {
          "$ref": "#/$defs/short"
        },
        "value": {
          "type": [
            "string",
            "number",
            "boolean",
            "null"
          ]
        }
      },
      "required": [
        "name",
        "value"
      ],
      "type": "object"
    },
    "id": {
      "maxLength": 128,
      "minLength": 1,
      "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]*$",
      "type": "string"
    },
    "knowledge_page": {
      "additionalProperties": false,
      "properties": {
        "items": {
          "items": {
            "additionalProperties": false,
            "properties": {
              "commit_oid": {
                "$ref": "#/$defs/id"
              },
              "content_hash": {
                "$ref": "#/$defs/digest"
              },
              "kind": {
                "enum": [
                  "decision",
                  "lesson",
                  "specification",
                  "note",
                  "research"
                ],
                "type": "string"
              },
              "knowledge_id": {
                "$ref": "#/$defs/id"
              },
              "locator": {
                "maxLength": 2048,
                "minLength": 1,
                "type": "string"
              }
            },
            "required": [
              "knowledge_id",
              "kind",
              "locator"
            ],
            "type": "object"
          },
          "maxItems": 100,
          "type": "array"
        },
        "next_cursor": {
          "$ref": "#/$defs/cursor"
        },
        "watermark": {
          "maxLength": 256,
          "type": "string"
        }
      },
      "required": [
        "items"
      ],
      "type": "object"
    },
    "knowledge_resolve_input": {
      "additionalProperties": false,
      "oneOf": [
        {
          "not": {
            "required": [
              "knowledge_id"
            ]
          },
          "required": [
            "work_id"
          ]
        },
        {
          "not": {
            "required": [
              "work_id"
            ]
          },
          "required": [
            "knowledge_id"
          ]
        }
      ],
      "properties": {
        "knowledge_id": {
          "$ref": "#/$defs/id"
        },
        "work_id": {
          "$ref": "#/$defs/id"
        }
      },
      "type": "object"
    },
    "knowledge_search_input": {
      "additionalProperties": false,
      "properties": {
        "budget": {
          "$ref": "#/$defs/budget"
        },
        "kinds": {
          "items": {
            "enum": [
              "decision",
              "lesson",
              "specification",
              "note",
              "research"
            ],
            "type": "string"
          },
          "maxItems": 16,
          "type": "array",
          "uniqueItems": true
        },
        "page": {
          "$ref": "#/$defs/page"
        },
        "product_id": {
          "$ref": "#/$defs/id"
        },
        "project_id": {
          "$ref": "#/$defs/id"
        },
        "since": {
          "maxLength": 64,
          "type": [
            "string",
            "null"
          ]
        },
        "tags": {
          "items": {
            "$ref": "#/$defs/id"
          },
          "maxItems": 32,
          "type": "array",
          "uniqueItems": true
        },
        "text": {
          "maxLength": 512,
          "type": "string"
        },
        "until": {
          "maxLength": 64,
          "type": [
            "string",
            "null"
          ]
        }
      },
      "required": [
        "page"
      ],
      "type": "object"
    },
    "lifecycle": {
      "enum": [
        "needed",
        "in_progress",
        "completed",
        "cancelled"
      ],
      "type": "string"
    },
    "limit": {
      "default": 20,
      "maximum": 100,
      "minimum": 1,
      "type": "integer"
    },
    "mutation_result": {
      "additionalProperties": false,
      "properties": {
        "changed_refs": {
          "items": {
            "additionalProperties": false,
            "properties": {
              "entity_kind": {
                "$ref": "#/$defs/short"
              },
              "id": {
                "$ref": "#/$defs/id"
              },
              "version": {
                "$ref": "#/$defs/version"
              }
            },
            "required": [
              "entity_kind",
              "id",
              "version"
            ],
            "type": "object"
          },
          "maxItems": 32,
          "type": "array"
        },
        "next_valid_intents": {
          "items": {
            "additionalProperties": false,
            "properties": {
              "operation": {
                "$ref": "#/$defs/short"
              },
              "reason_code": {
                "$ref": "#/$defs/short"
              },
              "tool": {
                "$ref": "#/$defs/id"
              }
            },
            "required": [
              "tool",
              "operation",
              "reason_code"
            ],
            "type": "object"
          },
          "maxItems": 16,
          "type": "array"
        },
        "operation_id": {
          "$ref": "#/$defs/id"
        }
      },
      "required": [
        "changed_refs",
        "next_valid_intents"
      ],
      "type": "object"
    },
    "operator_choice": {
      "additionalProperties": false,
      "properties": {
        "action_id": {
          "$ref": "#/$defs/id"
        },
        "description": {
          "$ref": "#/$defs/short"
        },
        "id": {
          "$ref": "#/$defs/id"
        },
        "label": {
          "$ref": "#/$defs/short"
        }
      },
      "required": [
        "id",
        "label",
        "description",
        "action_id"
      ],
      "type": "object"
    },
    "operator_question": {
      "additionalProperties": false,
      "properties": {
        "action_id": {
          "$ref": "#/$defs/id"
        },
        "allow_custom": {
          "const": false
        },
        "allow_multiple": {
          "const": false
        },
        "choices": {
          "items": {
            "$ref": "#/$defs/operator_choice"
          },
          "maxItems": 8,
          "minItems": 1,
          "type": "array",
          "uniqueItems": true
        },
        "contract_summary": {
          "$ref": "#/$defs/short"
        },
        "decision_context_digest": {
          "$ref": "#/$defs/digest"
        },
        "header": {
          "$ref": "#/$defs/short"
        },
        "premise_summary": {
          "$ref": "#/$defs/short"
        },
        "prompt": {
          "$ref": "#/$defs/short"
        }
      },
      "required": [
        "action_id",
        "prompt",
        "header",
        "choices",
        "allow_multiple",
        "allow_custom",
        "premise_summary",
        "contract_summary",
        "decision_context_digest"
      ],
      "type": "object"
    },
    "page": {
      "additionalProperties": false,
      "properties": {
        "cursor": {
          "$ref": "#/$defs/cursor"
        },
        "limit": {
          "$ref": "#/$defs/limit"
        }
      },
      "required": [
        "cursor",
        "limit"
      ],
      "type": "object"
    },
    "product_context": {
      "additionalProperties": false,
      "properties": {
        "candidates": {
          "items": {
            "$ref": "#/$defs/id"
          },
          "maxItems": 20,
          "type": "array",
          "uniqueItems": true
        },
        "next_cursor": {
          "$ref": "#/$defs/cursor"
        },
        "product_id": {
          "$ref": "#/$defs/id"
        },
        "projects": {
          "items": {
            "additionalProperties": false,
            "properties": {
              "project_id": {
                "$ref": "#/$defs/id"
              },
              "role": {
                "enum": [
                  "primary",
                  "secondary"
                ],
                "type": "string"
              },
              "version": {
                "$ref": "#/$defs/version"
              }
            },
            "required": [
              "project_id",
              "version"
            ],
            "type": "object"
          },
          "maxItems": 100,
          "type": "array"
        },
        "stage": {
          "enum": [
            "prototype",
            "alpha",
            "beta",
            "production",
            "deprecated"
          ],
          "type": "string"
        }
      },
      "required": [
        "product_id",
        "projects"
      ],
      "type": "object"
    },
    "product_snapshot": {
      "additionalProperties": false,
      "properties": {
        "counts": {
          "additionalProperties": false,
          "properties": {
            "cancelled": {
              "minimum": 0,
              "type": "integer"
            },
            "completed": {
              "minimum": 0,
              "type": "integer"
            },
            "in_progress": {
              "minimum": 0,
              "type": "integer"
            },
            "needed": {
              "minimum": 0,
              "type": "integer"
            }
          },
          "required": [
            "needed",
            "in_progress",
            "completed",
            "cancelled"
          ],
          "type": "object"
        },
        "previews": {
          "items": {
            "$ref": "#/$defs/work_summary"
          },
          "maxItems": 20,
          "type": "array"
        }
      },
      "required": [
        "counts",
        "previews"
      ],
      "type": "object"
    },
    "product_view_resolve_input": {
      "additionalProperties": false,
      "oneOf": [
        {
          "not": {
            "required": [
              "project_id"
            ]
          },
          "required": [
            "product_id"
          ]
        },
        {
          "not": {
            "required": [
              "product_id"
            ]
          },
          "required": [
            "project_id"
          ]
        },
        {
          "not": {
            "anyOf": [
              {
                "required": [
                  "product_id"
                ]
              },
              {
                "required": [
                  "project_id"
                ]
              }
            ]
          }
        }
      ],
      "properties": {
        "budget": {
          "$ref": "#/$defs/budget"
        },
        "page": {
          "$ref": "#/$defs/page"
        },
        "product_id": {
          "$ref": "#/$defs/id"
        },
        "project_id": {
          "$ref": "#/$defs/id"
        }
      },
      "type": "object"
    },
    "product_view_snapshot_input": {
      "additionalProperties": false,
      "properties": {
        "budget": {
          "$ref": "#/$defs/budget"
        },
        "preview_limit": {
          "maximum": 20,
          "minimum": 1,
          "type": "integer"
        },
        "product_id": {
          "$ref": "#/$defs/id"
        },
        "project_ids": {
          "items": {
            "$ref": "#/$defs/id"
          },
          "maxItems": 100,
          "type": "array",
          "uniqueItems": true
        }
      },
      "type": "object"
    },
    "relation_kind": {
      "enum": [
        "parent",
        "blocks",
        "implements",
        "supersedes",
        "superseded_by"
      ],
      "type": "string"
    },
    "scope": {
      "additionalProperties": false,
      "properties": {
        "product_id": {
          "$ref": "#/$defs/id"
        },
        "project_ids": {
          "items": {
            "$ref": "#/$defs/id"
          },
          "maxItems": 100,
          "type": "array",
          "uniqueItems": true
        },
        "scope_version": {
          "$ref": "#/$defs/id"
        },
        "work_ids": {
          "items": {
            "$ref": "#/$defs/id"
          },
          "maxItems": 100,
          "type": "array",
          "uniqueItems": true
        }
      },
      "type": "object"
    },
    "short": {
      "maxLength": 256,
      "minLength": 1,
      "type": "string"
    },
    "version": {
      "minimum": 1,
      "type": "integer"
    },
    "work_browse_blocked_input": {
      "additionalProperties": false,
      "properties": {
        "budget": {
          "$ref": "#/$defs/budget"
        },
        "depth": {
          "maximum": 3,
          "minimum": 1,
          "type": "integer"
        },
        "kind": {
          "$ref": "#/$defs/work_kind"
        },
        "page": {
          "$ref": "#/$defs/page"
        },
        "product_id": {
          "$ref": "#/$defs/id"
        },
        "project_id": {
          "$ref": "#/$defs/id"
        },
        "work_id": {
          "$ref": "#/$defs/id"
        }
      },
      "required": [
        "page"
      ],
      "type": "object"
    },
    "work_browse_list_input": {
      "additionalProperties": false,
      "properties": {
        "budget": {
          "$ref": "#/$defs/budget"
        },
        "component_id": {
          "$ref": "#/$defs/id"
        },
        "detail": {
          "$ref": "#/$defs/detail"
        },
        "kind": {
          "$ref": "#/$defs/work_kind"
        },
        "lifecycle": {
          "$ref": "#/$defs/lifecycle"
        },
        "page": {
          "$ref": "#/$defs/page"
        },
        "priority_max": {
          "maximum": 100,
          "minimum": -100,
          "type": "integer"
        },
        "priority_min": {
          "maximum": 100,
          "minimum": -100,
          "type": "integer"
        },
        "product_id": {
          "$ref": "#/$defs/id"
        },
        "project_ids": {
          "items": {
            "$ref": "#/$defs/id"
          },
          "maxItems": 100,
          "type": "array",
          "uniqueItems": true
        },
        "tag_ids": {
          "items": {
            "$ref": "#/$defs/id"
          },
          "maxItems": 32,
          "type": "array",
          "uniqueItems": true
        },
        "terminal_since": {
          "maxLength": 64,
          "type": [
            "string",
            "null"
          ]
        },
        "work_ids": {
          "items": {
            "$ref": "#/$defs/id"
          },
          "maxItems": 100,
          "type": "array",
          "uniqueItems": true
        }
      },
      "required": [
        "page"
      ],
      "type": "object"
    },
    "work_browse_ready_input": {
      "additionalProperties": false,
      "properties": {
        "budget": {
          "$ref": "#/$defs/budget"
        },
        "kind": {
          "$ref": "#/$defs/work_kind"
        },
        "page": {
          "$ref": "#/$defs/page"
        },
        "product_id": {
          "$ref": "#/$defs/id"
        },
        "project_id": {
          "$ref": "#/$defs/id"
        }
      },
      "required": [
        "page"
      ],
      "type": "object"
    },
    "work_browse_scope_input": {
      "additionalProperties": false,
      "oneOf": [
        {
          "not": {
            "required": [
              "project_id"
            ]
          },
          "required": [
            "work_id"
          ]
        },
        {
          "not": {
            "required": [
              "work_id"
            ]
          },
          "required": [
            "project_id"
          ]
        }
      ],
      "properties": {
        "budget": {
          "$ref": "#/$defs/budget"
        },
        "one_of": {
          "enum": [
            "project",
            "work"
          ],
          "type": "string"
        },
        "page": {
          "$ref": "#/$defs/page"
        },
        "product_id": {
          "$ref": "#/$defs/id"
        },
        "project_id": {
          "$ref": "#/$defs/id"
        },
        "work_id": {
          "$ref": "#/$defs/id"
        }
      },
      "required": [
        "product_id"
      ],
      "type": "object"
    },
    "work_compact_publish_input": {
      "additionalProperties": false,
      "properties": {
        "approval": {
          "$ref": "#/$defs/approval"
        },
        "content": {
          "maxLength": 32768,
          "minLength": 1,
          "type": "string"
        },
        "content_digest": {
          "$ref": "#/$defs/digest"
        },
        "evidence": {
          "items": {
            "$ref": "#/$defs/evidence"
          },
          "maxItems": 32,
          "type": "array"
        },
        "expected_version": {
          "$ref": "#/$defs/version"
        },
        "home_locator_id": {
          "$ref": "#/$defs/id"
        },
        "home_project_id": {
          "$ref": "#/$defs/id"
        },
        "idempotency_key": {
          "$ref": "#/$defs/id"
        },
        "work_id": {
          "$ref": "#/$defs/id"
        }
      },
      "required": [
        "work_id",
        "expected_version",
        "content",
        "content_digest",
        "home_project_id",
        "home_locator_id",
        "idempotency_key",
        "approval"
      ],
      "type": "object"
    },
    "work_compact_reconcile_input": {
      "additionalProperties": false,
      "oneOf": [
        {
          "not": {
            "required": [
              "work_id",
              "expected_work_version"
            ]
          },
          "required": [
            "operation_id",
            "expected_operation_version",
            "idempotency_key"
          ]
        },
        {
          "not": {
            "required": [
              "operation_id",
              "expected_operation_version"
            ]
          },
          "required": [
            "work_id",
            "expected_work_version",
            "idempotency_key"
          ]
        }
      ],
      "properties": {
        "approval": {
          "$ref": "#/$defs/approval"
        },
        "evidence": {
          "items": {
            "$ref": "#/$defs/evidence"
          },
          "maxItems": 32,
          "type": "array"
        },
        "expected_operation_version": {
          "$ref": "#/$defs/version"
        },
        "expected_proof_digest": {
          "$ref": "#/$defs/digest"
        },
        "expected_work_version": {
          "$ref": "#/$defs/version"
        },
        "idempotency_key": {
          "$ref": "#/$defs/id"
        },
        "operation_id": {
          "$ref": "#/$defs/id"
        },
        "work_id": {
          "$ref": "#/$defs/id"
        }
      },
      "type": "object"
    },
    "work_define_capture_input": {
      "additionalProperties": false,
      "properties": {
        "approval": {
          "$ref": "#/$defs/approval"
        },
        "component_id": {
          "$ref": "#/$defs/id"
        },
        "external_ref": {
          "$ref": "#/$defs/short"
        },
        "idempotency_key": {
          "$ref": "#/$defs/id"
        },
        "kind": {
          "$ref": "#/$defs/work_kind"
        },
        "priority": {
          "maximum": 100,
          "minimum": -100,
          "type": "integer"
        },
        "project_ids": {
          "items": {
            "$ref": "#/$defs/id"
          },
          "maxItems": 100,
          "minItems": 1,
          "type": "array",
          "uniqueItems": true
        },
        "tags": {
          "items": {
            "$ref": "#/$defs/id"
          },
          "maxItems": 32,
          "type": "array",
          "uniqueItems": true
        },
        "title": {
          "$ref": "#/$defs/short"
        },
        "value_statement": {
          "$ref": "#/$defs/short"
        },
        "workflow_type_ref": {
          "$ref": "#/$defs/id"
        }
      },
      "required": [
        "title",
        "value_statement",
        "kind",
        "project_ids",
        "idempotency_key"
      ],
      "type": "object"
    },
    "work_define_revise_input": {
      "additionalProperties": false,
      "properties": {
        "component_id": {
          "$ref": "#/$defs/id"
        },
        "evidence": {
          "items": {
            "$ref": "#/$defs/evidence"
          },
          "maxItems": 32,
          "type": "array"
        },
        "expected_version": {
          "$ref": "#/$defs/version"
        },
        "idempotency_key": {
          "$ref": "#/$defs/id"
        },
        "kind": {
          "$ref": "#/$defs/work_kind"
        },
        "priority": {
          "maximum": 100,
          "minimum": -100,
          "type": "integer"
        },
        "reason": {
          "$ref": "#/$defs/short"
        },
        "tags": {
          "items": {
            "$ref": "#/$defs/id"
          },
          "maxItems": 32,
          "type": "array",
          "uniqueItems": true
        },
        "title": {
          "$ref": "#/$defs/short"
        },
        "value_statement": {
          "$ref": "#/$defs/short"
        },
        "work_id": {
          "$ref": "#/$defs/id"
        },
        "workflow_type_ref": {
          "$ref": "#/$defs/id"
        }
      },
      "required": [
        "work_id",
        "expected_version",
        "title",
        "value_statement",
        "kind",
        "reason",
        "idempotency_key"
      ],
      "type": "object"
    },
    "work_event_page": {
      "additionalProperties": false,
      "properties": {
        "events": {
          "items": {
            "additionalProperties": false,
            "properties": {
              "actor": {
                "$ref": "#/$defs/id"
              },
              "event_id": {
                "$ref": "#/$defs/id"
              },
              "evidence": {
                "items": {
                  "$ref": "#/$defs/evidence"
                },
                "maxItems": 32,
                "type": "array"
              },
              "kind": {
                "$ref": "#/$defs/short"
              },
              "occurred_at": {
                "maxLength": 64,
                "type": "string"
              },
              "reason": {
                "$ref": "#/$defs/short"
              },
              "version": {
                "$ref": "#/$defs/version"
              }
            },
            "required": [
              "event_id",
              "kind",
              "version",
              "occurred_at"
            ],
            "type": "object"
          },
          "maxItems": 100,
          "type": "array"
        },
        "next_cursor": {
          "$ref": "#/$defs/cursor"
        },
        "workflow": {
          "$ref": "#/$defs/workflow_read"
        }
      },
      "required": [
        "events"
      ],
      "type": "object"
    },
    "work_kind": {
      "enum": [
        "task",
        "bug",
        "decision",
        "research",
        "epic",
        "other"
      ],
      "type": "string"
    },
    "work_page": {
      "additionalProperties": false,
      "properties": {
        "items": {
          "items": {
            "$ref": "#/$defs/work_summary"
          },
          "maxItems": 100,
          "type": "array"
        },
        "next_cursor": {
          "$ref": "#/$defs/cursor"
        },
        "readiness_evidence": {
          "items": {
            "$ref": "#/$defs/evidence"
          },
          "maxItems": 32,
          "type": "array"
        }
      },
      "required": [
        "items"
      ],
      "type": "object"
    },
    "work_relate_link_input": {
      "additionalProperties": false,
      "properties": {
        "approval": {
          "$ref": "#/$defs/approval"
        },
        "from_expected_version": {
          "$ref": "#/$defs/version"
        },
        "from_work_id": {
          "$ref": "#/$defs/id"
        },
        "idempotency_key": {
          "$ref": "#/$defs/id"
        },
        "kind": {
          "$ref": "#/$defs/relation_kind"
        },
        "reason": {
          "$ref": "#/$defs/short"
        },
        "to_expected_version": {
          "$ref": "#/$defs/version"
        },
        "to_work_id": {
          "$ref": "#/$defs/id"
        }
      },
      "required": [
        "from_work_id",
        "to_work_id",
        "from_expected_version",
        "to_expected_version",
        "kind",
        "reason",
        "idempotency_key"
      ],
      "type": "object"
    },
    "work_relate_memberships_input": {
      "additionalProperties": false,
      "properties": {
        "approval": {
          "$ref": "#/$defs/approval"
        },
        "expected_version": {
          "$ref": "#/$defs/version"
        },
        "idempotency_key": {
          "$ref": "#/$defs/id"
        },
        "memberships": {
          "items": {
            "additionalProperties": false,
            "properties": {
              "project_id": {
                "$ref": "#/$defs/id"
              },
              "role": {
                "enum": [
                  "primary",
                  "secondary"
                ],
                "type": "string"
              }
            },
            "required": [
              "project_id",
              "role"
            ],
            "type": "object"
          },
          "maxItems": 100,
          "minItems": 1,
          "type": "array"
        },
        "work_id": {
          "$ref": "#/$defs/id"
        }
      },
      "required": [
        "work_id",
        "expected_version",
        "memberships",
        "idempotency_key"
      ],
      "type": "object"
    },
    "work_relate_restore_input": {
      "additionalProperties": false,
      "properties": {
        "approval": {
          "$ref": "#/$defs/approval"
        },
        "evidence": {
          "items": {
            "$ref": "#/$defs/evidence"
          },
          "maxItems": 32,
          "type": "array"
        },
        "idempotency_key": {
          "$ref": "#/$defs/id"
        },
        "instruction": {
          "$ref": "#/$defs/short"
        },
        "predecessor_expected_version": {
          "$ref": "#/$defs/version"
        },
        "predecessor_id": {
          "$ref": "#/$defs/id"
        },
        "reason": {
          "$ref": "#/$defs/short"
        },
        "replacement_successor_expected_version": {
          "$ref": "#/$defs/version"
        },
        "replacement_successor_id": {
          "$ref": "#/$defs/id"
        },
        "successor_expected_version": {
          "$ref": "#/$defs/version"
        },
        "successor_id": {
          "$ref": "#/$defs/id"
        }
      },
      "required": [
        "predecessor_id",
        "predecessor_expected_version",
        "successor_id",
        "successor_expected_version",
        "reason",
        "idempotency_key",
        "approval"
      ],
      "type": "object"
    },
    "work_relate_supersede_input": {
      "additionalProperties": false,
      "properties": {
        "approval": {
          "$ref": "#/$defs/approval"
        },
        "evidence": {
          "items": {
            "$ref": "#/$defs/evidence"
          },
          "maxItems": 32,
          "type": "array"
        },
        "idempotency_key": {
          "$ref": "#/$defs/id"
        },
        "predecessor_expected_version": {
          "$ref": "#/$defs/version"
        },
        "predecessor_id": {
          "$ref": "#/$defs/id"
        },
        "reason": {
          "$ref": "#/$defs/short"
        },
        "successor_expected_version": {
          "$ref": "#/$defs/version"
        },
        "successor_id": {
          "$ref": "#/$defs/id"
        }
      },
      "required": [
        "predecessor_id",
        "successor_id",
        "predecessor_expected_version",
        "successor_expected_version",
        "reason",
        "idempotency_key"
      ],
      "type": "object"
    },
    "work_relate_unlink_input": {
      "additionalProperties": false,
      "properties": {
        "approval": {
          "$ref": "#/$defs/approval"
        },
        "expected_versions": {
          "items": {
            "additionalProperties": false,
            "properties": {
              "version": {
                "$ref": "#/$defs/version"
              },
              "work_id": {
                "$ref": "#/$defs/id"
              }
            },
            "required": [
              "work_id",
              "version"
            ],
            "type": "object"
          },
          "maxItems": 100,
          "minItems": 1,
          "type": "array",
          "uniqueItems": true
        },
        "idempotency_key": {
          "$ref": "#/$defs/id"
        },
        "reason": {
          "$ref": "#/$defs/short"
        },
        "relation_id": {
          "$ref": "#/$defs/id"
        }
      },
      "required": [
        "relation_id",
        "expected_versions",
        "reason",
        "idempotency_key"
      ],
      "type": "object"
    },
    "work_relation_graph": {
      "additionalProperties": false,
      "properties": {
        "edges": {
          "items": {
            "additionalProperties": false,
            "properties": {
              "from": {
                "$ref": "#/$defs/id"
              },
              "kind": {
                "$ref": "#/$defs/relation_kind"
              },
              "to": {
                "$ref": "#/$defs/id"
              }
            },
            "required": [
              "from",
              "to",
              "kind"
            ],
            "type": "object"
          },
          "maxItems": 200,
          "type": "array"
        },
        "nodes": {
          "items": {
            "$ref": "#/$defs/work_summary"
          },
          "maxItems": 100,
          "type": "array"
        },
        "replacement_state": {
          "enum": [
            "none",
            "active",
            "reopened"
          ],
          "type": "string"
        }
      },
      "required": [
        "nodes",
        "edges"
      ],
      "type": "object"
    },
    "work_scope": {
      "additionalProperties": false,
      "anyOf": [
        {
          "required": [
            "work",
            "memberships"
          ]
        },
        {
          "required": [
            "items"
          ]
        }
      ],
      "properties": {
        "items": {
          "items": {
            "$ref": "#/$defs/work_summary"
          },
          "maxItems": 100,
          "type": "array"
        },
        "memberships": {
          "items": {
            "additionalProperties": false,
            "properties": {
              "project_id": {
                "$ref": "#/$defs/id"
              },
              "role": {
                "enum": [
                  "primary",
                  "secondary"
                ],
                "type": "string"
              }
            },
            "required": [
              "project_id",
              "role"
            ],
            "type": "object"
          },
          "maxItems": 100,
          "minItems": 1,
          "type": "array"
        },
        "next_cursor": {
          "$ref": "#/$defs/cursor"
        },
        "work": {
          "$ref": "#/$defs/work_summary"
        }
      },
      "required": [
        "items"
      ],
      "type": "object"
    },
    "work_summary": {
      "additionalProperties": false,
      "properties": {
        "id": {
          "$ref": "#/$defs/id"
        },
        "kind": {
          "$ref": "#/$defs/work_kind"
        },
        "lifecycle": {
          "$ref": "#/$defs/lifecycle"
        },
        "priority": {
          "maximum": 100,
          "minimum": -100,
          "type": "integer"
        },
        "project_ids": {
          "items": {
            "$ref": "#/$defs/id"
          },
          "maxItems": 100,
          "type": "array",
          "uniqueItems": true
        },
        "ready": {
          "type": "boolean"
        },
        "terminal_at": {
          "maxLength": 64,
          "type": [
            "string",
            "null"
          ]
        },
        "title": {
          "$ref": "#/$defs/short"
        },
        "version": {
          "$ref": "#/$defs/version"
        }
      },
      "required": [
        "id",
        "kind",
        "title",
        "lifecycle",
        "version"
      ],
      "type": "object"
    },
    "work_trace_history_input": {
      "additionalProperties": false,
      "properties": {
        "budget": {
          "$ref": "#/$defs/budget"
        },
        "direction": {
          "$ref": "#/$defs/direction"
        },
        "event_kinds": {
          "items": {
            "$ref": "#/$defs/short"
          },
          "maxItems": 32,
          "type": "array",
          "uniqueItems": true
        },
        "page": {
          "$ref": "#/$defs/page"
        },
        "work_id": {
          "$ref": "#/$defs/id"
        }
      },
      "required": [
        "work_id",
        "page"
      ],
      "type": "object"
    },
    "work_trace_relations_input": {
      "additionalProperties": false,
      "properties": {
        "budget": {
          "$ref": "#/$defs/budget"
        },
        "depth": {
          "maximum": 3,
          "minimum": 1,
          "type": "integer"
        },
        "direction": {
          "$ref": "#/$defs/direction"
        },
        "relation_kinds": {
          "items": {
            "$ref": "#/$defs/relation_kind"
          },
          "maxItems": 8,
          "type": "array",
          "uniqueItems": true
        },
        "work_id": {
          "$ref": "#/$defs/id"
        }
      },
      "required": [
        "work_id"
      ],
      "type": "object"
    },
    "work_transition_action_input": {
      "additionalProperties": false,
      "else": {
        "not": {
          "anyOf": [
            {
              "required": [
                "selected_choice"
              ]
            },
            {
              "required": [
                "decision_context_digest"
              ]
            }
          ]
        }
      },
      "if": {
        "properties": {
          "action_id": {
            "const": "confirm_premise"
          }
        }
      },
      "properties": {
        "action_id": {
          "$ref": "#/$defs/id"
        },
        "approval": {
          "$ref": "#/$defs/approval"
        },
        "decision_context_digest": {
          "$ref": "#/$defs/digest"
        },
        "evidence": {
          "items": {
            "$ref": "#/$defs/evidence"
          },
          "maxItems": 32,
          "type": "array"
        },
        "expected_version": {
          "$ref": "#/$defs/version"
        },
        "fields": {
          "oneOf": [
            {
              "items": {
                "$ref": "#/$defs/field"
              },
              "maxItems": 16,
              "type": "array",
              "uniqueItems": true
            },
            {
              "additionalProperties": false,
              "maxProperties": 64,
              "properties": {
                "added": {},
                "attempt_epoch": {},
                "audit_evidence": {},
                "candidate_kind": {},
                "candidate_refs": {},
                "complete_gate_prerequisites": {},
                "condition_id": {},
                "consumed_contract_version": {},
                "contract_version": {},
                "current_claim": {},
                "dependent_work_id": {},
                "edge_class": {},
                "edge_kind": {},
                "entity_kind": {},
                "entity_ref": {},
                "event_stream": {},
                "evidence_refs": {},
                "new_contract_version": {},
                "next_read_expectations": {},
                "notice_id": {},
                "observed_drift": {},
                "operation_id": {},
                "outcome": {},
                "payload": {},
                "premise": {},
                "project_ids": {},
                "proposed_route_conventions": {},
                "relation": {},
                "relation_data": {},
                "removed": {},
                "required_route_conventions": {},
                "resolution_evidence": {},
                "resolver_authority": {},
                "resolver_result": {},
                "route_conventions": {},
                "severity": {},
                "source_contract_version": {},
                "source_work_id": {},
                "staleness_rule_id": {},
                "successor_work_id": {},
                "supersede_reason": {},
                "target_work_id": {},
                "title": {},
                "transaction": {},
                "value_statement": {}
              },
              "type": "object"
            }
          ]
        },
        "idempotency_key": {
          "$ref": "#/$defs/id"
        },
        "selected_choice": {
          "enum": [
            "confirm",
            "revise",
            "stop"
          ],
          "type": "string"
        },
        "work_id": {
          "$ref": "#/$defs/id"
        }
      },
      "required": [
        "work_id",
        "expected_version",
        "action_id",
        "idempotency_key"
      ],
      "then": {
        "not": {
          "required": [
            "fields"
          ]
        },
        "required": [
          "selected_choice",
          "decision_context_digest"
        ]
      },
      "type": "object"
    },
    "work_transition_lifecycle_input": {
      "additionalProperties": false,
      "properties": {
        "approval": {
          "$ref": "#/$defs/approval"
        },
        "evidence": {
          "items": {
            "$ref": "#/$defs/evidence"
          },
          "maxItems": 32,
          "type": "array"
        },
        "expected_version": {
          "$ref": "#/$defs/version"
        },
        "idempotency_key": {
          "$ref": "#/$defs/id"
        },
        "reason": {
          "$ref": "#/$defs/short"
        },
        "target": {
          "$ref": "#/$defs/lifecycle"
        },
        "work_id": {
          "$ref": "#/$defs/id"
        }
      },
      "required": [
        "work_id",
        "expected_version",
        "target",
        "reason",
        "idempotency_key"
      ],
      "type": "object"
    },
    "workflow_contract": {
      "additionalProperties": false,
      "properties": {
        "outcome_kind": {
          "$ref": "#/$defs/short"
        },
        "outcome_payload": {
          "maxLength": 16384,
          "type": "string"
        },
        "premise": {
          "$ref": "#/$defs/short"
        },
        "required_evidence": {
          "items": {
            "$ref": "#/$defs/id"
          },
          "maxItems": 7,
          "type": "array"
        },
        "route_conventions": {
          "items": {
            "$ref": "#/$defs/id"
          },
          "maxItems": 16,
          "type": "array"
        },
        "spec_mandate": {
          "items": {
            "$ref": "#/$defs/id"
          },
          "maxItems": 32,
          "type": "array"
        },
        "version": {
          "$ref": "#/$defs/version"
        }
      },
      "required": [
        "version",
        "premise",
        "outcome_kind",
        "outcome_payload",
        "required_evidence",
        "route_conventions",
        "spec_mandate"
      ],
      "type": "object"
    },
    "workflow_read": {
      "additionalProperties": false,
      "properties": {
        "blocking_conditions": {
          "items": {
            "$ref": "#/$defs/id"
          },
          "maxItems": 100,
          "type": "array"
        },
        "candidate_ids": {
          "items": {
            "$ref": "#/$defs/id"
          },
          "maxItems": 100,
          "type": "array"
        },
        "completion_warnings": {
          "items": {
            "$ref": "#/$defs/short"
          },
          "maxItems": 32,
          "type": "array"
        },
        "conditions": {
          "items": {
            "additionalProperties": false,
            "properties": {
              "await_ref": {
                "$ref": "#/$defs/id"
              },
              "await_type": {
                "$ref": "#/$defs/short"
              },
              "id": {
                "$ref": "#/$defs/id"
              },
              "resolution_authority": {
                "$ref": "#/$defs/id"
              },
              "state": {
                "$ref": "#/$defs/short"
              }
            },
            "required": [
              "id",
              "await_type",
              "await_ref",
              "resolution_authority",
              "state"
            ],
            "type": "object"
          },
          "maxItems": 100,
          "type": "array"
        },
        "contract": {
          "$ref": "#/$defs/workflow_contract"
        },
        "current_step": {
          "$ref": "#/$defs/id"
        },
        "definition": {
          "additionalProperties": false,
          "properties": {
            "digest": {
              "$ref": "#/$defs/digest"
            },
            "ref": {
              "$ref": "#/$defs/id"
            },
            "version": {
              "$ref": "#/$defs/version"
            }
          },
          "required": [
            "ref",
            "version",
            "digest"
          ],
          "type": "object"
        },
        "impact_notices": {
          "items": {
            "additionalProperties": false,
            "properties": {
              "edge_id": {
                "$ref": "#/$defs/id"
              },
              "entity_kind": {
                "$ref": "#/$defs/short"
              },
              "entity_ref": {
                "$ref": "#/$defs/id"
              },
              "notice_id": {
                "$ref": "#/$defs/id"
              },
              "severity": {
                "$ref": "#/$defs/short"
              },
              "source_contract_version": {
                "$ref": "#/$defs/version"
              },
              "source_work_id": {
                "$ref": "#/$defs/id"
              },
              "target_work_id": {
                "$ref": "#/$defs/id"
              }
            },
            "required": [
              "notice_id",
              "source_work_id",
              "source_contract_version",
              "entity_kind",
              "entity_ref",
              "target_work_id",
              "edge_id",
              "severity"
            ],
            "type": "object"
          },
          "maxItems": 100,
          "type": "array"
        },
        "operator_question": {
          "$ref": "#/$defs/operator_question",
          "type": [
            "object",
            "null"
          ]
        },
        "ready": {
          "type": "boolean"
        },
        "state": {
          "$ref": "#/$defs/short"
        },
        "unreadable_conditions": {
          "items": {
            "$ref": "#/$defs/id"
          },
          "maxItems": 100,
          "type": "array"
        },
        "unresolved_conditions": {
          "items": {
            "$ref": "#/$defs/id"
          },
          "maxItems": 100,
          "type": "array"
        },
        "work_id": {
          "$ref": "#/$defs/id"
        }
      },
      "required": [
        "work_id",
        "state",
        "current_step",
        "definition",
        "conditions",
        "unresolved_conditions",
        "unreadable_conditions",
        "ready",
        "blocking_conditions",
        "impact_notices",
        "completion_warnings"
      ],
      "type": "object"
    }
  },
  "$id": "https://raw.githubusercontent.com/Sharper-Flow/concord/main/contracts/agent-tool-surface-payloads.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "title": "Concord TS3/TS4 operation payloads",
  "type": "object"
}`
