// Code generated by scripts/generate-agent-contracts.py; DO NOT EDIT.
package agent

import (
	"encoding/json"
	"fmt"
)

const ManifestVersion = "3.3.0"
const ManifestDigest = "sha256:7bdb77e7e10edafe41f384da9ad98ebb5cf7140188bd62b4839c2d8caa7142b5"

type OperationKind string

const (
	OperationRead     OperationKind = "read"
	OperationMutation OperationKind = "mutation"
)

type Capability string
type ApprovalClass string
type Availability string

const (
	AvailabilityAlways             Availability = "always"
	AvailabilityWorkflowDefinition Availability = "workflow_definition"
)

type ContractOperation struct {
	ID, Tool, Operation string
	Kind                OperationKind
	QueryID             string
	Capability          Capability
	Approval            ApprovalClass
	Availability        Availability
}

var ContractOperations = []ContractOperation{
	{ID: "concord_product_view.resolve", Tool: "concord_product_view", Operation: "resolve", Kind: OperationKind("read"), QueryID: "PM1.Q1", Capability: Capability("product_read"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_product_view.snapshot", Tool: "concord_product_view", Operation: "snapshot", Kind: OperationKind("read"), QueryID: "PM1.Q2", Capability: Capability("product_read"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_product_view.portfolio", Tool: "concord_product_view", Operation: "portfolio", Kind: OperationKind("read"), QueryID: "C14.ProductRows", Capability: Capability("product_read"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_product_view.blocked_sessions", Tool: "concord_product_view", Operation: "blocked_sessions", Kind: OperationKind("read"), QueryID: "PM1.Q12", Capability: Capability("product_read"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_browse.list", Tool: "concord_work_browse", Operation: "list", Kind: OperationKind("read"), QueryID: "PM1.Q3", Capability: Capability("product_read"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_browse.blocked", Tool: "concord_work_browse", Operation: "blocked", Kind: OperationKind("read"), QueryID: "PM1.Q4", Capability: Capability("product_read"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_browse.ready", Tool: "concord_work_browse", Operation: "ready", Kind: OperationKind("read"), QueryID: "PM1.Q5", Capability: Capability("product_read"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_browse.scope", Tool: "concord_work_browse", Operation: "scope", Kind: OperationKind("read"), QueryID: "PM1.Q6", Capability: Capability("product_read"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_trace.history", Tool: "concord_work_trace", Operation: "history", Kind: OperationKind("read"), QueryID: "PM1.Q7", Capability: Capability("product_read"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_trace.relations", Tool: "concord_work_trace", Operation: "relations", Kind: OperationKind("read"), QueryID: "PM1.Q8", Capability: Capability("product_read"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_trace.continuity", Tool: "concord_work_trace", Operation: "continuity", Kind: OperationKind("read"), QueryID: "C19.Continuity", Capability: Capability("product_read"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_trace.research", Tool: "concord_work_trace", Operation: "research", Kind: OperationKind("read"), QueryID: "PM1.Q11", Capability: Capability("product_read"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_knowledge.search", Tool: "concord_knowledge", Operation: "search", Kind: OperationKind("read"), QueryID: "PM1.Q9", Capability: Capability("product_read"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_knowledge.resolve_note", Tool: "concord_knowledge", Operation: "resolve_note", Kind: OperationKind("read"), QueryID: "PM1.Q10", Capability: Capability("product_read"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_define.capture", Tool: "concord_work_define", Operation: "capture", Kind: OperationKind("mutation"), QueryID: "", Capability: Capability("work_define"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_define.revise_intent", Tool: "concord_work_define", Operation: "revise_intent", Kind: OperationKind("mutation"), QueryID: "", Capability: Capability("work_define"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_define.research_pack_create", Tool: "concord_work_define", Operation: "research_pack_create", Kind: OperationKind("mutation"), QueryID: "", Capability: Capability("research"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_define.research_revision_append", Tool: "concord_work_define", Operation: "research_revision_append", Kind: OperationKind("mutation"), QueryID: "", Capability: Capability("research"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_define.research_finding_record", Tool: "concord_work_define", Operation: "research_finding_record", Kind: OperationKind("mutation"), QueryID: "", Capability: Capability("research"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_define.research_source_record", Tool: "concord_work_define", Operation: "research_source_record", Kind: OperationKind("mutation"), QueryID: "", Capability: Capability("research"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_define.research_freshness_set", Tool: "concord_work_define", Operation: "research_freshness_set", Kind: OperationKind("mutation"), QueryID: "", Capability: Capability("research"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_epic.create", Tool: "concord_work_epic", Operation: "create", Kind: OperationKind("mutation"), QueryID: "", Capability: Capability("work_epic"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_epic.add_entry", Tool: "concord_work_epic", Operation: "add_entry", Kind: OperationKind("mutation"), QueryID: "", Capability: Capability("work_epic"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_epic.remove_entry", Tool: "concord_work_epic", Operation: "remove_entry", Kind: OperationKind("mutation"), QueryID: "", Capability: Capability("work_epic"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_epic.reorder_entry", Tool: "concord_work_epic", Operation: "reorder_entry", Kind: OperationKind("mutation"), QueryID: "", Capability: Capability("work_epic"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_epic.change_requiredness", Tool: "concord_work_epic", Operation: "change_requiredness", Kind: OperationKind("mutation"), QueryID: "", Capability: Capability("work_epic"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_epic.revise_narrative", Tool: "concord_work_epic", Operation: "revise_narrative", Kind: OperationKind("mutation"), QueryID: "", Capability: Capability("work_epic"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_epic.entries", Tool: "concord_work_epic", Operation: "entries", Kind: OperationKind("read"), QueryID: "C21.EpicEntries", Capability: Capability("product_read"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_transition.lifecycle", Tool: "concord_work_transition", Operation: "lifecycle", Kind: OperationKind("mutation"), QueryID: "", Capability: Capability("work_transition"), Approval: ApprovalClass("conditional"), Availability: Availability("always")},
	{ID: "concord_work_transition.workflow_action", Tool: "concord_work_transition", Operation: "workflow_action", Kind: OperationKind("mutation"), QueryID: "", Capability: Capability("work_transition"), Approval: ApprovalClass("conditional"), Availability: Availability("workflow_definition")},
	{ID: "concord_work_transition.worktree_claim", Tool: "concord_work_transition", Operation: "worktree_claim", Kind: OperationKind("mutation"), QueryID: "", Capability: Capability("work_transition"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_transition.worktree_reclaim", Tool: "concord_work_transition", Operation: "worktree_reclaim", Kind: OperationKind("mutation"), QueryID: "", Capability: Capability("work_transition"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_relate.set_memberships", Tool: "concord_work_relate", Operation: "set_memberships", Kind: OperationKind("mutation"), QueryID: "", Capability: Capability("work_relate"), Approval: ApprovalClass("conditional"), Availability: Availability("always")},
	{ID: "concord_work_relate.link", Tool: "concord_work_relate", Operation: "link", Kind: OperationKind("mutation"), QueryID: "", Capability: Capability("work_relate"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_relate.unlink", Tool: "concord_work_relate", Operation: "unlink", Kind: OperationKind("mutation"), QueryID: "", Capability: Capability("work_relate"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_relate.supersede", Tool: "concord_work_relate", Operation: "supersede", Kind: OperationKind("mutation"), QueryID: "", Capability: Capability("work_relate"), Approval: ApprovalClass("required"), Availability: Availability("always")},
	{ID: "concord_work_relate.restore_superseded", Tool: "concord_work_relate", Operation: "restore_superseded", Kind: OperationKind("mutation"), QueryID: "", Capability: Capability("work_relate"), Approval: ApprovalClass("required"), Availability: Availability("always")},
	{ID: "concord_work_compact.publish", Tool: "concord_work_compact", Operation: "publish", Kind: OperationKind("mutation"), QueryID: "", Capability: Capability("work_compact"), Approval: ApprovalClass("required"), Availability: Availability("always")},
	{ID: "concord_work_compact.reconcile", Tool: "concord_work_compact", Operation: "reconcile", Kind: OperationKind("mutation"), QueryID: "", Capability: Capability("work_compact"), Approval: ApprovalClass("conditional"), Availability: Availability("always")},
	{ID: "concord_work_compact.lesson_publish", Tool: "concord_work_compact", Operation: "lesson_publish", Kind: OperationKind("mutation"), QueryID: "", Capability: Capability("work_compact"), Approval: ApprovalClass("required"), Availability: Availability("always")},
}

func ValidateContractOperation(tool, operation string) (ContractOperation, bool) {
	for _, candidate := range ContractOperations {
		if candidate.Tool == tool && candidate.Operation == operation {
			return candidate, true
		}
	}
	return ContractOperation{}, false
}

type GeneratedPayloadRule struct {
	Required   []string
	Properties []string
}

var GeneratedPayloadRules = map[string]GeneratedPayloadRule{
	"approval":                                   {Required: []string{"approval_ref"}, Properties: []string{"approval_ref"}},
	"blocked_sessions_page":                      {Required: []string{"sessions"}, Properties: []string{"sessions"}},
	"blocked_work_page":                          {Required: []string{"items", "nodes", "edges"}, Properties: []string{"items", "nodes", "edges", "next_cursor"}},
	"budget":                                     {Required: []string{"max_bytes", "max_items"}, Properties: []string{"max_bytes", "max_items", "max_millis"}},
	"canonical_note_result":                      {Required: []string{"state"}, Properties: []string{"state", "locator", "candidates"}},
	"continuity_boundary":                        {Required: []string{"boundary_id", "sequence", "kind", "checkpoint_id", "checkpoint_sequence", "summary", "recorded_at"}, Properties: []string{"boundary_id", "sequence", "kind", "checkpoint_id", "checkpoint_sequence", "summary", "recorded_at"}},
	"continuity_checkpoint":                      {Required: []string{"checkpoint_id", "work_version", "sequence", "step_id", "attempt_epoch", "active_unit", "hypothesis", "diagnosis", "strategy", "touched_refs", "evidence_refs", "pending_questions", "pending_decisions"}, Properties: []string{"checkpoint_id", "work_version", "sequence", "step_id", "attempt_epoch", "active_unit", "hypothesis", "diagnosis", "strategy", "touched_refs", "evidence_refs", "pending_questions", "pending_decisions"}},
	"continuity_failure":                         {Required: []string{"kind", "recoverable", "step_id", "attempt_epoch"}, Properties: []string{"kind", "recoverable", "step_id", "attempt_epoch"}},
	"continuity_operator_decision":               {Required: []string{"action_id", "prompt", "header", "choices", "allow_multiple", "allow_custom", "premise_summary", "contract_summary", "decision_context_digest"}, Properties: []string{"action_id", "prompt", "header", "choices", "allow_multiple", "allow_custom", "premise_summary", "contract_summary", "decision_context_digest"}},
	"continuity_snapshot":                        {Required: []string{"work_id", "pinned", "latest_checkpoint", "boundaries", "typed_availability"}, Properties: []string{"work_id", "pinned", "latest_checkpoint", "boundaries", "typed_availability"}},
	"epic_add_entry_input":                       {Required: []string{"epic_work_id", "child_work_id", "expected_version", "position", "idempotency_key"}, Properties: []string{"epic_work_id", "child_work_id", "expected_version", "position", "required", "idempotency_key"}},
	"epic_change_requiredness_input":             {Required: []string{"epic_work_id", "child_work_id", "expected_version", "required", "idempotency_key"}, Properties: []string{"epic_work_id", "child_work_id", "expected_version", "required", "idempotency_key"}},
	"epic_create_input":                          {Required: []string{"title", "value_statement", "project_ids", "idempotency_key"}, Properties: []string{"title", "value_statement", "project_ids", "priority", "urgency", "tags", "component_id", "external_ref", "idempotency_key"}},
	"epic_entries_input":                         {Required: []string{"epic_work_id"}, Properties: []string{"epic_work_id", "budget"}},
	"epic_entries_result":                        {Required: []string{"entries", "narrative"}, Properties: []string{"narrative", "entries"}},
	"epic_remove_entry_input":                    {Required: []string{"epic_work_id", "child_work_id", "expected_version", "idempotency_key"}, Properties: []string{"epic_work_id", "child_work_id", "expected_version", "idempotency_key"}},
	"epic_reorder_entry_input":                   {Required: []string{"epic_work_id", "child_work_id", "expected_version", "position", "idempotency_key"}, Properties: []string{"epic_work_id", "child_work_id", "expected_version", "position", "idempotency_key"}},
	"epic_revise_narrative_input":                {Required: []string{"epic_work_id", "expected_version", "narrative", "reason", "idempotency_key"}, Properties: []string{"epic_work_id", "expected_version", "narrative", "reason", "idempotency_key"}},
	"evidence":                                   {Required: []string{"kind", "authority", "locator_kind", "locator"}, Properties: []string{"kind", "authority", "locator_kind", "locator", "version", "digest"}},
	"field":                                      {Required: []string{"name", "value"}, Properties: []string{"name", "value"}},
	"knowledge_page":                             {Required: []string{"items"}, Properties: []string{"items", "next_cursor", "watermark"}},
	"knowledge_resolve_input":                    {Required: []string{}, Properties: []string{"work_id", "knowledge_id"}},
	"knowledge_scopes_input":                     {Required: []string{"mode"}, Properties: []string{"mode", "product_ids", "project_ids", "component_ids", "tag_ids"}},
	"knowledge_search_input":                     {Required: []string{"page"}, Properties: []string{"product_id", "project_id", "kinds", "tags", "text", "since", "until", "page", "budget"}},
	"mutation_result":                            {Required: []string{"changed_refs", "next_valid_intents"}, Properties: []string{"changed_refs", "next_valid_intents", "operation_id"}},
	"operator_choice":                            {Required: []string{"id", "label", "description", "action_id"}, Properties: []string{"id", "label", "description", "action_id"}},
	"operator_question":                          {Required: []string{"action_id", "prompt", "header", "choices", "allow_multiple", "allow_custom", "premise_summary", "contract_summary", "decision_context_digest"}, Properties: []string{"action_id", "prompt", "header", "choices", "allow_multiple", "allow_custom", "premise_summary", "contract_summary", "decision_context_digest"}},
	"page":                                       {Required: []string{"cursor", "limit"}, Properties: []string{"cursor", "limit"}},
	"product_context":                            {Required: []string{"product_id", "projects"}, Properties: []string{"product_id", "stage", "projects", "candidates", "next_cursor"}},
	"product_row":                                {Required: []string{"product_id", "display_name", "stage", "reliance", "action_counts"}, Properties: []string{"product_id", "display_name", "display_name_suffix", "stage", "reliance", "action_counts", "focus", "focus_absent_reason"}},
	"product_row_action_counts":                  {Required: []string{"state"}, Properties: []string{"state", "values", "unavailable"}},
	"product_row_action_values":                  {Required: []string{"in_progress", "blocked", "ready", "active_problems", "approval_required"}, Properties: []string{"in_progress", "blocked", "ready", "active_problems", "approval_required"}},
	"product_row_focus":                          {Required: []string{"work_id", "title", "work_kind", "lifecycle", "attention_kind", "priority", "project_count", "stage_context"}, Properties: []string{"work_id", "title", "work_kind", "lifecycle", "attention_kind", "priority", "workflow_step_label", "project_count", "stage_context"}},
	"product_row_page":                           {Required: []string{"observed_at", "rows"}, Properties: []string{"observed_at", "rows"}},
	"product_row_portfolio_input":                {Required: []string{"page"}, Properties: []string{"product_id", "page", "budget", "source"}},
	"product_row_reliance":                       {Required: []string{"authority", "observed_at", "age", "stale", "blocks_execution", "omissions"}, Properties: []string{"authority", "observed_at", "age", "stale", "blocks_execution", "reason", "omissions"}},
	"product_row_source":                         {Required: []string{}, Properties: []string{"authority", "observed_at", "age", "stale", "blocks_execution", "reason", "omissions"}},
	"product_row_stage":                          {Required: []string{"maturity", "audience_commitment"}, Properties: []string{"maturity", "audience_commitment"}},
	"product_row_stage_context":                  {Required: []string{"kind"}, Properties: []string{"kind", "focus_override"}},
	"product_row_unavailable":                    {Required: []string{"reason", "omissions"}, Properties: []string{"reason", "omissions"}},
	"product_snapshot":                           {Required: []string{"counts", "previews"}, Properties: []string{"counts", "previews"}},
	"product_view_blocked_sessions_input":        {Required: []string{"product_id"}, Properties: []string{"product_id", "page", "budget"}},
	"product_view_resolve_input":                 {Required: []string{}, Properties: []string{"product_id", "project_id", "page", "budget"}},
	"product_view_snapshot_input":                {Required: []string{}, Properties: []string{"product_id", "project_ids", "preview_limit", "budget"}},
	"research_finding":                           {Required: []string{"pack_id", "revision", "finding_id", "kind", "statement", "confidence", "freshness", "status"}, Properties: []string{"pack_id", "revision", "finding_id", "kind", "statement", "confidence", "freshness", "status", "source_ids", "scopes"}},
	"research_finding_input":                     {Required: []string{"finding_id", "kind", "statement", "confidence"}, Properties: []string{"finding_id", "kind", "statement", "confidence", "freshness", "status", "scopes"}},
	"research_pack":                              {Required: []string{"pack_id", "owner_work_id", "current_revision", "freshness", "expected_version", "created_at", "updated_at"}, Properties: []string{"pack_id", "owner_work_id", "current_revision", "freshness", "expected_version", "created_at", "updated_at", "revisions", "consumers"}},
	"research_revision":                          {Required: []string{"pack_id", "revision", "question", "created_at"}, Properties: []string{"pack_id", "revision", "question", "scope_in", "scope_out", "done_when", "method", "created_at", "findings", "sources"}},
	"research_revision_input":                    {Required: []string{"question", "method"}, Properties: []string{"question", "scope_in", "scope_out", "done_when", "method"}},
	"research_scopes_input":                      {Required: []string{"mode"}, Properties: []string{"mode", "product_ids", "project_ids", "component_ids", "tag_ids"}},
	"research_source":                            {Required: []string{"pack_id", "revision", "source_id", "kind", "locator", "title", "publisher_or_author", "accessed_at"}, Properties: []string{"pack_id", "revision", "source_id", "kind", "locator", "title", "publisher_or_author", "published_at", "accessed_at"}},
	"research_source_input":                      {Required: []string{"source_id", "kind", "locator", "title", "publisher_or_author", "accessed_at"}, Properties: []string{"source_id", "kind", "locator", "title", "publisher_or_author", "published_at", "accessed_at"}},
	"scope":                                      {Required: []string{}, Properties: []string{"product_id", "project_ids", "work_ids", "scope_version"}},
	"work_browse_blocked_input":                  {Required: []string{"page"}, Properties: []string{"product_id", "project_id", "work_id", "kind", "depth", "page", "budget"}},
	"work_browse_list_input":                     {Required: []string{"page"}, Properties: []string{"product_id", "project_ids", "work_ids", "lifecycle", "kind", "component_id", "tag_ids", "priority_min", "priority_max", "detail", "terminal_since", "page", "budget"}},
	"work_browse_ready_input":                    {Required: []string{"page"}, Properties: []string{"product_id", "project_id", "kind", "page", "budget"}},
	"work_browse_scope_input":                    {Required: []string{"product_id"}, Properties: []string{"product_id", "project_id", "work_id", "page", "budget", "one_of"}},
	"work_compact_lesson_publish_input":          {Required: []string{"work_id", "lesson_id", "title", "summary", "content", "idempotency_key"}, Properties: []string{"work_id", "lesson_id", "title", "summary", "content", "tags", "scopes", "evidence", "idempotency_key", "approval"}},
	"work_compact_publish_input":                 {Required: []string{"work_id", "expected_version", "content", "content_digest", "home_project_id", "home_locator_id", "idempotency_key", "approval"}, Properties: []string{"work_id", "expected_version", "content", "content_digest", "home_project_id", "home_locator_id", "idempotency_key", "approval", "evidence"}},
	"work_compact_reconcile_input":               {Required: []string{}, Properties: []string{"operation_id", "expected_operation_version", "work_id", "expected_work_version", "expected_proof_digest", "idempotency_key", "approval", "evidence"}},
	"work_define_capture_input":                  {Required: []string{"title", "value_statement", "kind", "project_ids", "idempotency_key"}, Properties: []string{"title", "value_statement", "kind", "project_ids", "priority", "urgency", "tags", "component_id", "workflow_type_ref", "external_ref", "idempotency_key", "approval"}},
	"work_define_research_finding_record_input":  {Required: []string{"pack_id", "expected_version", "finding", "idempotency_key"}, Properties: []string{"pack_id", "expected_version", "finding", "source_ids", "idempotency_key"}},
	"work_define_research_freshness_set_input":   {Required: []string{"pack_id", "expected_version", "freshness", "idempotency_key"}, Properties: []string{"pack_id", "expected_version", "freshness", "idempotency_key"}},
	"work_define_research_pack_create_input":     {Required: []string{"owner_work_id", "revision", "idempotency_key"}, Properties: []string{"owner_work_id", "revision", "freshness", "idempotency_key"}},
	"work_define_research_revision_append_input": {Required: []string{"pack_id", "expected_version", "revision", "idempotency_key"}, Properties: []string{"pack_id", "expected_version", "revision", "idempotency_key"}},
	"work_define_research_source_record_input":   {Required: []string{"pack_id", "expected_version", "source", "idempotency_key"}, Properties: []string{"pack_id", "expected_version", "source", "idempotency_key"}},
	"work_define_revise_input":                   {Required: []string{"work_id", "expected_version", "title", "value_statement", "kind", "reason", "idempotency_key"}, Properties: []string{"work_id", "expected_version", "title", "value_statement", "kind", "priority", "urgency", "tags", "component_id", "workflow_type_ref", "reason", "idempotency_key", "evidence"}},
	"work_event_page":                            {Required: []string{"events"}, Properties: []string{"events", "next_cursor", "workflow"}},
	"work_page":                                  {Required: []string{"items"}, Properties: []string{"items", "next_cursor", "readiness_evidence"}},
	"work_relate_link_input":                     {Required: []string{"from_work_id", "to_work_id", "from_expected_version", "to_expected_version", "kind", "reason", "idempotency_key"}, Properties: []string{"from_work_id", "to_work_id", "from_expected_version", "to_expected_version", "kind", "reason", "idempotency_key", "approval"}},
	"work_relate_memberships_input":              {Required: []string{"work_id", "expected_version", "memberships", "idempotency_key"}, Properties: []string{"work_id", "expected_version", "memberships", "idempotency_key", "approval"}},
	"work_relate_restore_input":                  {Required: []string{"predecessor_id", "predecessor_expected_version", "successor_id", "successor_expected_version", "reason", "idempotency_key", "approval"}, Properties: []string{"predecessor_id", "predecessor_expected_version", "successor_id", "successor_expected_version", "replacement_successor_id", "replacement_successor_expected_version", "instruction", "reason", "idempotency_key", "approval", "evidence"}},
	"work_relate_supersede_input":                {Required: []string{"predecessor_id", "successor_id", "predecessor_expected_version", "successor_expected_version", "reason", "idempotency_key"}, Properties: []string{"predecessor_id", "successor_id", "predecessor_expected_version", "successor_expected_version", "reason", "idempotency_key", "approval", "evidence"}},
	"work_relate_unlink_input":                   {Required: []string{"relation_id", "expected_versions", "reason", "idempotency_key"}, Properties: []string{"relation_id", "expected_versions", "reason", "idempotency_key", "approval"}},
	"work_relation_graph":                        {Required: []string{"nodes", "edges"}, Properties: []string{"nodes", "edges", "replacement_state"}},
	"work_scope":                                 {Required: []string{"items"}, Properties: []string{"work", "memberships", "items", "next_cursor", "verdict"}},
	"work_summary":                               {Required: []string{"id", "kind", "title", "lifecycle", "version"}, Properties: []string{"id", "kind", "title", "lifecycle", "version", "priority", "urgency", "project_ids", "ready", "narrative", "terminal_at"}},
	"work_trace_continuity_input":                {Required: []string{"work_id", "page"}, Properties: []string{"work_id", "page", "budget"}},
	"work_trace_history_input":                   {Required: []string{"work_id", "page"}, Properties: []string{"work_id", "direction", "event_kinds", "page", "budget"}},
	"work_trace_relations_input":                 {Required: []string{"work_id"}, Properties: []string{"work_id", "relation_kinds", "direction", "depth", "budget"}},
	"work_trace_research_input":                  {Required: []string{"product_id"}, Properties: []string{"product_id", "pack_id", "work_id", "page", "budget"}},
	"work_transition_action_input":               {Required: []string{"work_id", "expected_version", "action_id", "idempotency_key"}, Properties: []string{"work_id", "expected_version", "action_id", "selected_choice", "decision_context_digest", "fields", "idempotency_key", "evidence", "approval", "research_bindings"}},
	"work_transition_lifecycle_input":            {Required: []string{"work_id", "expected_version", "target", "reason", "idempotency_key"}, Properties: []string{"work_id", "expected_version", "target", "reason", "idempotency_key", "evidence", "approval"}},
	"work_transition_worktree_claim_input":       {Required: []string{"work_id", "project_id", "branch", "base_sha", "path", "expected_version", "idempotency_key"}, Properties: []string{"work_id", "project_id", "branch", "base_sha", "path", "expected_version", "idempotency_key"}},
	"work_transition_worktree_reclaim_input":     {Required: []string{"work_id", "project_id", "expected_version", "idempotency_key"}, Properties: []string{"work_id", "project_id", "default_ref", "expected_version", "idempotency_key"}},
	"workflow_contract":                          {Required: []string{"version", "premise", "outcome_kind", "outcome_payload", "required_evidence", "route_conventions", "spec_mandate"}, Properties: []string{"version", "premise", "outcome_kind", "outcome_payload", "required_evidence", "route_conventions", "spec_mandate", "law_modifies"}},
	"workflow_read":                              {Required: []string{"work_id", "state", "current_step", "definition", "conditions", "unresolved_conditions", "unreadable_conditions", "ready", "blocking_conditions", "impact_notices", "completion_warnings"}, Properties: []string{"work_id", "state", "current_step", "definition", "contract", "operator_question", "candidate_ids", "conditions", "unresolved_conditions", "unreadable_conditions", "ready", "blocking_conditions", "impact_notices", "completion_warnings"}},
}

func ValidateGeneratedPayload(schemaName string, data []byte) error {
	rule, ok := GeneratedPayloadRules[schemaName]
	if !ok {
		return fmt.Errorf("unknown payload schema %s", schemaName)
	}
	var object map[string]json.RawMessage
	if err := json.Unmarshal(data, &object); err != nil {
		return fmt.Errorf("payload is not an object: %w", err)
	}
	allowed := map[string]bool{}
	for _, name := range rule.Properties {
		allowed[name] = true
	}
	for name := range object {
		if !allowed[name] {
			return fmt.Errorf("unknown payload field %s", name)
		}
	}
	for _, name := range rule.Required {
		if _, ok := object[name]; !ok {
			return fmt.Errorf("missing payload field %s", name)
		}
	}
	return nil
}
