// Code generated by scripts/generate-agent-contracts.py; DO NOT EDIT.
package agent

import (
	"encoding/json"
	"fmt"
)

const ManifestVersion = "1.0.0"
const ManifestDigest = "sha256:ff0c8d047ab5565c168072eb6ca5daa6e4d664c482064abb920d583bb3bec6a5"

type OperationKind string

const (
	OperationRead     OperationKind = "read"
	OperationMutation OperationKind = "mutation"
)

type Capability string
type ApprovalClass string
type Availability string

const (
	AvailabilityAlways             Availability = "always"
	AvailabilityWorkflowDefinition Availability = "workflow_definition"
)

type ContractOperation struct {
	ID, Tool, Operation string
	Kind                OperationKind
	QueryID             string
	Capability          Capability
	Approval            ApprovalClass
	Availability        Availability
}

var ContractOperations = []ContractOperation{
	{ID: "concord_product_view.resolve", Tool: "concord_product_view", Operation: "resolve", Kind: OperationKind("read"), QueryID: "PM1.Q1", Capability: Capability("product_read"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_product_view.snapshot", Tool: "concord_product_view", Operation: "snapshot", Kind: OperationKind("read"), QueryID: "PM1.Q2", Capability: Capability("product_read"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_browse.list", Tool: "concord_work_browse", Operation: "list", Kind: OperationKind("read"), QueryID: "PM1.Q3", Capability: Capability("product_read"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_browse.blocked", Tool: "concord_work_browse", Operation: "blocked", Kind: OperationKind("read"), QueryID: "PM1.Q4", Capability: Capability("product_read"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_browse.ready", Tool: "concord_work_browse", Operation: "ready", Kind: OperationKind("read"), QueryID: "PM1.Q5", Capability: Capability("product_read"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_browse.scope", Tool: "concord_work_browse", Operation: "scope", Kind: OperationKind("read"), QueryID: "PM1.Q6", Capability: Capability("product_read"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_trace.history", Tool: "concord_work_trace", Operation: "history", Kind: OperationKind("read"), QueryID: "PM1.Q7", Capability: Capability("product_read"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_trace.relations", Tool: "concord_work_trace", Operation: "relations", Kind: OperationKind("read"), QueryID: "PM1.Q8", Capability: Capability("product_read"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_knowledge.search", Tool: "concord_knowledge", Operation: "search", Kind: OperationKind("read"), QueryID: "PM1.Q9", Capability: Capability("product_read"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_knowledge.resolve_note", Tool: "concord_knowledge", Operation: "resolve_note", Kind: OperationKind("read"), QueryID: "PM1.Q10", Capability: Capability("product_read"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_define.capture", Tool: "concord_work_define", Operation: "capture", Kind: OperationKind("mutation"), QueryID: "", Capability: Capability("work_define"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_define.revise_intent", Tool: "concord_work_define", Operation: "revise_intent", Kind: OperationKind("mutation"), QueryID: "", Capability: Capability("work_define"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_transition.lifecycle", Tool: "concord_work_transition", Operation: "lifecycle", Kind: OperationKind("mutation"), QueryID: "", Capability: Capability("work_transition"), Approval: ApprovalClass("conditional"), Availability: Availability("always")},
	{ID: "concord_work_transition.workflow_action", Tool: "concord_work_transition", Operation: "workflow_action", Kind: OperationKind("mutation"), QueryID: "", Capability: Capability("work_transition"), Approval: ApprovalClass("conditional"), Availability: Availability("workflow_definition")},
	{ID: "concord_work_relate.set_memberships", Tool: "concord_work_relate", Operation: "set_memberships", Kind: OperationKind("mutation"), QueryID: "", Capability: Capability("work_relate"), Approval: ApprovalClass("conditional"), Availability: Availability("always")},
	{ID: "concord_work_relate.link", Tool: "concord_work_relate", Operation: "link", Kind: OperationKind("mutation"), QueryID: "", Capability: Capability("work_relate"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_relate.unlink", Tool: "concord_work_relate", Operation: "unlink", Kind: OperationKind("mutation"), QueryID: "", Capability: Capability("work_relate"), Approval: ApprovalClass("none"), Availability: Availability("always")},
	{ID: "concord_work_relate.supersede", Tool: "concord_work_relate", Operation: "supersede", Kind: OperationKind("mutation"), QueryID: "", Capability: Capability("work_relate"), Approval: ApprovalClass("required"), Availability: Availability("always")},
	{ID: "concord_work_relate.restore_superseded", Tool: "concord_work_relate", Operation: "restore_superseded", Kind: OperationKind("mutation"), QueryID: "", Capability: Capability("work_relate"), Approval: ApprovalClass("required"), Availability: Availability("always")},
	{ID: "concord_work_compact.publish", Tool: "concord_work_compact", Operation: "publish", Kind: OperationKind("mutation"), QueryID: "", Capability: Capability("work_compact"), Approval: ApprovalClass("required"), Availability: Availability("always")},
	{ID: "concord_work_compact.reconcile", Tool: "concord_work_compact", Operation: "reconcile", Kind: OperationKind("mutation"), QueryID: "", Capability: Capability("work_compact"), Approval: ApprovalClass("conditional"), Availability: Availability("always")},
}

func ValidateContractOperation(tool, operation string) (ContractOperation, bool) {
	for _, candidate := range ContractOperations {
		if candidate.Tool == tool && candidate.Operation == operation {
			return candidate, true
		}
	}
	return ContractOperation{}, false
}
func WorkflowActionAvailable() bool { return false }

type GeneratedPayloadRule struct {
	Required   []string
	Properties []string
}

var GeneratedPayloadRules = map[string]GeneratedPayloadRule{
	"approval":                        {Required: []string{"approval_ref"}, Properties: []string{"approval_ref"}},
	"blocked_work_page":               {Required: []string{"items", "nodes", "edges"}, Properties: []string{"items", "nodes", "edges", "next_cursor"}},
	"budget":                          {Required: []string{"max_bytes", "max_items"}, Properties: []string{"max_bytes", "max_items", "max_millis"}},
	"canonical_note_result":           {Required: []string{"state"}, Properties: []string{"state", "locator", "candidates"}},
	"evidence":                        {Required: []string{"kind", "authority", "locator_kind", "locator"}, Properties: []string{"kind", "authority", "locator_kind", "locator", "version", "digest"}},
	"field":                           {Required: []string{"name", "value"}, Properties: []string{"name", "value"}},
	"knowledge_page":                  {Required: []string{"items"}, Properties: []string{"items", "next_cursor", "watermark"}},
	"knowledge_resolve_input":         {Required: []string{}, Properties: []string{"work_id", "knowledge_id"}},
	"knowledge_search_input":          {Required: []string{"page"}, Properties: []string{"product_id", "project_id", "kinds", "tags", "text", "since", "until", "page", "budget"}},
	"mutation_result":                 {Required: []string{"changed_refs", "next_valid_intents"}, Properties: []string{"changed_refs", "next_valid_intents", "operation_id"}},
	"page":                            {Required: []string{"cursor", "limit"}, Properties: []string{"cursor", "limit"}},
	"product_context":                 {Required: []string{"product_id", "projects"}, Properties: []string{"product_id", "stage", "projects", "candidates", "next_cursor"}},
	"product_snapshot":                {Required: []string{"counts", "previews"}, Properties: []string{"counts", "previews"}},
	"product_view_resolve_input":      {Required: []string{}, Properties: []string{"product_id", "project_id", "page", "budget"}},
	"product_view_snapshot_input":     {Required: []string{}, Properties: []string{"product_id", "project_ids", "preview_limit", "budget"}},
	"scope":                           {Required: []string{}, Properties: []string{"product_id", "project_ids", "work_ids", "scope_version"}},
	"work_browse_blocked_input":       {Required: []string{"page"}, Properties: []string{"product_id", "project_id", "work_id", "kind", "depth", "page", "budget"}},
	"work_browse_list_input":          {Required: []string{"page"}, Properties: []string{"product_id", "project_ids", "work_ids", "lifecycle", "kind", "component_id", "tag_ids", "priority_min", "priority_max", "detail", "terminal_since", "page", "budget"}},
	"work_browse_ready_input":         {Required: []string{"page"}, Properties: []string{"product_id", "project_id", "kind", "page", "budget"}},
	"work_browse_scope_input":         {Required: []string{"product_id"}, Properties: []string{"product_id", "project_id", "work_id", "page", "budget", "one_of"}},
	"work_compact_publish_input":      {Required: []string{"work_id", "expected_version", "content", "content_digest", "home_project_id", "home_locator_id", "idempotency_key", "approval"}, Properties: []string{"work_id", "expected_version", "content", "content_digest", "home_project_id", "home_locator_id", "idempotency_key", "approval", "evidence"}},
	"work_compact_reconcile_input":    {Required: []string{}, Properties: []string{"operation_id", "expected_operation_version", "work_id", "expected_work_version", "expected_proof_digest", "idempotency_key", "approval", "evidence"}},
	"work_define_capture_input":       {Required: []string{"title", "value_statement", "kind", "project_ids", "idempotency_key"}, Properties: []string{"title", "value_statement", "kind", "project_ids", "priority", "tags", "component_id", "workflow_type_ref", "external_ref", "idempotency_key", "approval"}},
	"work_define_revise_input":        {Required: []string{"work_id", "expected_version", "title", "value_statement", "kind", "reason", "idempotency_key"}, Properties: []string{"work_id", "expected_version", "title", "value_statement", "kind", "priority", "tags", "component_id", "workflow_type_ref", "reason", "idempotency_key", "evidence"}},
	"work_event_page":                 {Required: []string{"events"}, Properties: []string{"events", "next_cursor"}},
	"work_page":                       {Required: []string{"items"}, Properties: []string{"items", "next_cursor", "readiness_evidence"}},
	"work_relate_link_input":          {Required: []string{"from_work_id", "to_work_id", "from_expected_version", "to_expected_version", "kind", "reason", "idempotency_key"}, Properties: []string{"from_work_id", "to_work_id", "from_expected_version", "to_expected_version", "kind", "reason", "idempotency_key", "approval"}},
	"work_relate_memberships_input":   {Required: []string{"work_id", "expected_version", "memberships", "idempotency_key"}, Properties: []string{"work_id", "expected_version", "memberships", "idempotency_key", "approval"}},
	"work_relate_restore_input":       {Required: []string{"predecessor_id", "predecessor_expected_version", "successor_id", "successor_expected_version", "reason", "idempotency_key", "approval"}, Properties: []string{"predecessor_id", "predecessor_expected_version", "successor_id", "successor_expected_version", "replacement_successor_id", "replacement_successor_expected_version", "instruction", "reason", "idempotency_key", "approval", "evidence"}},
	"work_relate_supersede_input":     {Required: []string{"predecessor_id", "successor_id", "predecessor_expected_version", "successor_expected_version", "reason", "idempotency_key"}, Properties: []string{"predecessor_id", "successor_id", "predecessor_expected_version", "successor_expected_version", "reason", "idempotency_key", "approval", "evidence"}},
	"work_relate_unlink_input":        {Required: []string{"relation_id", "expected_versions", "reason", "idempotency_key"}, Properties: []string{"relation_id", "expected_versions", "reason", "idempotency_key", "approval"}},
	"work_relation_graph":             {Required: []string{"nodes", "edges"}, Properties: []string{"nodes", "edges", "replacement_state"}},
	"work_scope":                      {Required: []string{"items"}, Properties: []string{"work", "memberships", "items", "next_cursor"}},
	"work_summary":                    {Required: []string{"id", "kind", "title", "lifecycle", "version"}, Properties: []string{"id", "kind", "title", "lifecycle", "version", "priority", "project_ids", "ready", "terminal_at"}},
	"work_trace_history_input":        {Required: []string{"work_id", "page"}, Properties: []string{"work_id", "direction", "event_kinds", "page", "budget"}},
	"work_trace_relations_input":      {Required: []string{"work_id"}, Properties: []string{"work_id", "relation_kinds", "direction", "depth", "budget"}},
	"work_transition_action_input":    {Required: []string{"work_id", "expected_version", "action_id", "idempotency_key"}, Properties: []string{"work_id", "expected_version", "action_id", "fields", "idempotency_key", "evidence", "approval"}},
	"work_transition_lifecycle_input": {Required: []string{"work_id", "expected_version", "target", "reason", "idempotency_key"}, Properties: []string{"work_id", "expected_version", "target", "reason", "idempotency_key", "evidence", "approval"}},
}

func ValidateGeneratedPayload(schemaName string, data []byte) error {
	rule, ok := GeneratedPayloadRules[schemaName]
	if !ok {
		return fmt.Errorf("unknown payload schema %s", schemaName)
	}
	var object map[string]json.RawMessage
	if err := json.Unmarshal(data, &object); err != nil {
		return fmt.Errorf("payload is not an object: %w", err)
	}
	allowed := map[string]bool{}
	for _, name := range rule.Properties {
		allowed[name] = true
	}
	for name := range object {
		if !allowed[name] {
			return fmt.Errorf("unknown payload field %s", name)
		}
	}
	for _, name := range rule.Required {
		if _, ok := object[name]; !ok {
			return fmt.Errorf("missing payload field %s", name)
		}
	}
	return nil
}
