// Code generated by scripts/generate-agent-lanes.py; DO NOT EDIT.
package store

const LaneRegistryManifestDigest = "sha256:6019e5cea715c8f42066b61e5eddb635e7d2bf1e14aab975721dd12f809e4126"

var generatedLaneDefinitions = []LaneDefinition{
	{
		ID: "research", Version: 1, Digest: "sha256:69f0271ffb9e14808aaf5d420e19f49928fe660a7336ad254f4f19486e90e2c3",
		Purpose: "Investigate bounded questions and return source-backed findings.", CapabilityClass: "research",
		Capabilities: []string{"read_repository", "search_public_sources", "cite_evidence"}, PacketSchemaRef: "agent-lane-packet.v1", ReportSchemaRef: "agent-lane-report.v1",
		Budgets:             LaneBudgets{CostUSDMax: 2, ContextTokensMax: 32000, TimeSecondsMax: 900},
		EvidenceObligations: []string{"source_citations", "bounded_findings", "uncertainties"}, RequiredReportBlocks: []string{},
		LifecycleStates: []string{"dispatched", "completed", "failed"},
	},
	{
		ID: "implement", Version: 1, Digest: "sha256:8e773bc93eea48493500b58f118deee9f91efb26a0213ea1e415cac7b716cbaa",
		Purpose: "Implement one approved bounded engineering task and report verification.", CapabilityClass: "implementation",
		Capabilities: []string{"read_repository", "edit_scoped_files", "run_tests", "report_evidence"}, PacketSchemaRef: "agent-lane-packet.v1", ReportSchemaRef: "agent-lane-report.v1",
		Budgets:             LaneBudgets{CostUSDMax: 4, ContextTokensMax: 48000, TimeSecondsMax: 1800},
		EvidenceObligations: []string{"files_touched", "verification_commands", "unresolved_issues"}, RequiredReportBlocks: []string{},
		LifecycleStates: []string{"dispatched", "completed", "failed"},
	},
	{
		ID: "design", Version: 1, Digest: "sha256:a2061098223cc1b9b31c62ed9ad2d92c97ef50c25f20802706fae026e4318804",
		Purpose: "Implement visual UI and UX changes for one approved bounded task and report design evidence.", CapabilityClass: "design",
		Capabilities: []string{"read_repository", "edit_scoped_files", "run_targeted_checks", "report_evidence"}, PacketSchemaRef: "agent-lane-packet.v1", ReportSchemaRef: "agent-lane-report.v1",
		Budgets:             LaneBudgets{CostUSDMax: 4, ContextTokensMax: 48000, TimeSecondsMax: 1800},
		EvidenceObligations: []string{"files_touched", "verification_commands", "visual_artifacts", "unresolved_issues"}, RequiredReportBlocks: []string{},
		LifecycleStates: []string{"dispatched", "completed", "failed"},
	},
	{
		ID: "review", Version: 1, Digest: "sha256:139ba516f8744a6bfc9d1b26bda766dd270d12625a7bcc4610894141d216c5a6",
		Purpose: "Review a bounded change against its contract and acceptance evidence.", CapabilityClass: "review",
		Capabilities: []string{"read_repository", "inspect_diff", "run_targeted_checks", "report_findings"}, PacketSchemaRef: "agent-lane-packet.v1", ReportSchemaRef: "agent-lane-report.v1",
		Budgets:             LaneBudgets{CostUSDMax: 2.5, ContextTokensMax: 40000, TimeSecondsMax: 1200},
		EvidenceObligations: []string{"contract_findings", "severity", "verification_commands"}, RequiredReportBlocks: []string{"review"},
		LifecycleStates: []string{"dispatched", "completed", "failed"},
	},
	{
		ID: "verify", Version: 1, Digest: "sha256:1fda1ccd5f1e9f9add9dc5ecbe6776be9d5a4c83a377edbd7e2b8b4aaf5dfb71",
		Purpose: "Run independent verification and return deterministic pass or failure evidence.", CapabilityClass: "verification",
		Capabilities: []string{"read_repository", "run_tests", "run_validators", "report_evidence"}, PacketSchemaRef: "agent-lane-packet.v1", ReportSchemaRef: "agent-lane-report.v1",
		Budgets:             LaneBudgets{CostUSDMax: 3, ContextTokensMax: 40000, TimeSecondsMax: 1500},
		EvidenceObligations: []string{"commands", "exit_codes", "failure_classification"}, RequiredReportBlocks: []string{},
		LifecycleStates: []string{"dispatched", "completed", "failed"},
	},
}
