// Code generated by scripts/generate-work-kinds.py; DO NOT EDIT.
package store

var workKindStored = map[string]bool{
	"bug":        true,
	"decision":   true,
	"epic":       false,
	"initiative": true,
	"other":      true,
	"research":   true,
	"task":       true,
}

var workKindFoldCreate = map[string]bool{
	"bug":        true,
	"decision":   true,
	"epic":       false,
	"initiative": true,
	"other":      true,
	"research":   true,
	"task":       true,
}

var workKindFoldRevise = map[string]bool{
	"bug":        true,
	"decision":   true,
	"epic":       false,
	"initiative": false,
	"other":      true,
	"research":   true,
	"task":       true,
}

var workKindAgentCapture = map[string]bool{
	"bug":        true,
	"decision":   true,
	"epic":       false,
	"initiative": false,
	"other":      true,
	"research":   true,
	"task":       true,
}

type workKindRefusal struct {
	Message  string
	Recovery string
}

var workKindRefusals = map[string]workKindRefusal{
	"epic":       {Message: "obsolete work kind is not accepted", Recovery: "use Initiative through the dedicated Initiative operation"},
	"initiative": {Message: "initiative work kind is reserved for the dedicated Initiative operation", Recovery: "use Initiative through the dedicated Initiative operation"},
}

func WorkKindStored(kind string) bool {
	return workKindStored[kind]
}

func WorkKindFoldCreateAllowed(kind string) bool {
	return workKindFoldCreate[kind]
}

func WorkKindFoldReviseAllowed(kind string) bool {
	return workKindFoldRevise[kind]
}

func WorkKindAgentCaptureAllowed(kind string) bool {
	return workKindAgentCapture[kind]
}

func WorkKindRequiresDedicatedOperation(kind string) bool {
	return workKindStored[kind] && !workKindFoldRevise[kind]
}

func WorkKindRefusalFor(kind string) (message, recovery string, ok bool) {
	refusal, ok := workKindRefusals[kind]
	if !ok {
		return "", "", false
	}
	return refusal.Message, refusal.Recovery, true
}
