// Code generated by scripts/generate-agent-lanes.py; DO NOT EDIT.
package store

const RoutingPolicyManifestDigest = "sha256:99a5805ad7593954f6b5219511760609b80493a899c3d00fa1f68204d5e56046"
const RoutingPolicyVersion = "routing-v1"

var generatedRoutingPolicies = []RoutingPolicyDefinition{
	{
		CapabilityClass: "research", PreferredModel: "openai/gpt-5.6-luna",
		ResolutionSet: []string{"openai/gpt-5.6-luna", "zai-coding-plan/glm-5.2"},
	},
	{
		CapabilityClass: "implementation", PreferredModel: "openai/gpt-5.6-luna",
		ResolutionSet: []string{"openai/gpt-5.6-luna", "zai-coding-plan/glm-5.2"},
	},
	{
		CapabilityClass: "review", PreferredModel: "zai-coding-plan/glm-5.2",
		ResolutionSet: []string{"zai-coding-plan/glm-5.2", "kimi-for-coding/kimi-for-coding"},
	},
	{
		CapabilityClass: "verification", PreferredModel: "openai/gpt-5.6-luna",
		ResolutionSet: []string{"openai/gpt-5.6-luna", "zai-coding-plan/glm-5.2"},
	},
}
