// Code generated by scripts/generate-branch-freshness.py; DO NOT EDIT.

package store

import (
	"fmt"
	"math"
	"regexp"
	"strings"
)

// branchFreshnessSHAPattern matches the full commit SHA the owning
// branch-freshness contract requires for every sampled SHA field.
var branchFreshnessSHAPattern = regexp.MustCompile("^[0-9a-f]{40}$")

// branchFreshnessFields is the closed field set each status carries, in
// contract order.
var branchFreshnessFields = map[string][]string{
	"ok":      {"status", "head_sha", "default_ref", "default_sha", "behind_count"},
	"unknown": {"status", "reason"},
}

// BranchFreshnessStatusAllowed reports whether status is in the closed
// branch-freshness status vocabulary.
func BranchFreshnessStatusAllowed(status string) bool {
	_, ok := branchFreshnessFields[status]
	return ok
}

// branchFreshnessReasons is the closed typed failure-reason vocabulary.
var branchFreshnessReasons = map[string]bool{
	"timeout":      true,
	"fetch_failed": true,
	"probe_failed": true,
}

// BranchFreshnessReasonAllowed reports whether reason is in the closed
// branch-freshness typed failure-reason vocabulary.
func BranchFreshnessReasonAllowed(reason string) bool {
	return branchFreshnessReasons[reason]
}

// branchFreshnessDefaultRefValid reports whether ref is the "origin/" prefix
// plus a branch name git-check-ref-format accepts, per the owning contract's
// git_ref_rule: no control character, space, ~ ^ : ? * [ or backslash
// anywhere, no .., no @{, no leading or trailing slash or double slash, no
// trailing dot, and no slash-separated component that starts with a dot or
// ends with .lock.
func branchFreshnessDefaultRefValid(ref string) bool {
	const prefix = "origin/"
	if !strings.HasPrefix(ref, prefix) || len(ref) == len(prefix) {
		return false
	}
	name := "refs/remotes/" + ref
	for _, r := range name {
		if r <= 0x20 || r == 0x7f || strings.ContainsRune("~^:?*[\\", r) {
			return false
		}
	}
	if strings.Contains(name, "..") || strings.Contains(name, "@{") {
		return false
	}
	if strings.HasPrefix(name, "/") || strings.HasSuffix(name, "/") || strings.Contains(name, "//") {
		return false
	}
	if strings.HasSuffix(name, ".") {
		return false
	}
	for _, component := range strings.Split(name, "/") {
		if strings.HasPrefix(component, ".") || strings.HasSuffix(component, ".lock") {
			return false
		}
	}
	return true
}

// ValidateBranchFreshnessObject validates one decoded branch_freshness result
// object against the owning contract: a closed status, the exact field set
// that status carries, "^[0-9a-f]{40}$" sampled SHAs and a
// valid origin default ref and a nonnegative integer "behind_count" behind the
// ok status, and a closed typed failure reason behind the unknown status.
func ValidateBranchFreshnessObject(value map[string]any) error {
	status, ok := value["status"].(string)
	if !ok {
		return fmt.Errorf("branch_freshness status is not a string")
	}
	fields, known := branchFreshnessFields[status]
	if !known {
		return fmt.Errorf("branch_freshness status %q is not in the owning contract", status)
	}
	if len(value) != len(fields) {
		return fmt.Errorf("branch_freshness %s carries %d fields, want exactly %d", status, len(value), len(fields))
	}
	for _, field := range fields {
		if _, present := value[field]; !present {
			return fmt.Errorf("branch_freshness %s is missing field %q", status, field)
		}
	}
	if status != "ok" {
		reason, _ := value["reason"].(string)
		if !branchFreshnessReasons[reason] {
			return fmt.Errorf("branch_freshness reason %q is not in the owning contract", reason)
		}
		return nil
	}
	for _, field := range []string{"head_sha", "default_sha"} {
		sha, _ := value[field].(string)
		if !branchFreshnessSHAPattern.MatchString(sha) {
			return fmt.Errorf("branch_freshness %s %q is not a full commit SHA", field, sha)
		}
	}
	ref, _ := value["default_ref"].(string)
	if !branchFreshnessDefaultRefValid(ref) {
		return fmt.Errorf("branch_freshness default_ref %q is not a valid origin default ref", ref)
	}
	count, isNumber := value["behind_count"].(float64)
	if !isNumber || count != math.Trunc(count) || count < 0 {
		return fmt.Errorf("branch_freshness behind_count is not an integer of at least 0")
	}
	return nil
}

// BranchFreshnessStatuses returns the closed status vocabulary in contract order.
func BranchFreshnessStatuses() []string {
	return []string{"ok", "unknown"}
}

// BranchFreshnessReasons returns the closed typed failure reasons in contract order.
func BranchFreshnessReasons() []string {
	return []string{"timeout", "fetch_failed", "probe_failed"}
}
