// Code generated by scripts/generate-lane-step-dispatch.py; DO NOT EDIT.
package store

// LaneStepDispatchManifestDigest pins the authored join contract this
// projection was generated from: contracts/lane-step-dispatch.v1.json.
const LaneStepDispatchManifestDigest = "sha256:943d1cadccdeed59180f9864d31d4410e1dcdb28b7138c2ea33acb85a6a1b4b3"

// laneStepDispatchKinds maps one agent-lane capability class to the workflow
// step kinds at which a lane of that class may be dispatched. The map is the
// single authority both definition composition and dispatch-time validation
// read; neither may hard-code a step kind a binding does not name.
var laneStepDispatchKinds = map[string][]string{
	"design":         {"external_effect"},
	"implementation": {"external_effect"},
	"research":       {"internal_sqlite", "cross_authority"},
	"review":         {"cross_authority", "external_effect", "internal_sqlite"},
	"verification":   {"external_effect"},
}
