// Code generated by scripts/generate-agent-lanes.py; DO NOT EDIT.
package store

const LaneRegistryManifestDigest = "sha256:6b5760f8a2872a6e89db20129d39aa3353a6853b337810d6b0540cbb84c16e89"

var generatedLaneDefinitions = []LaneDefinition{
	{
		ID: "research", Version: 1, Digest: "sha256:4091e91c9c095b96be54aba40d9704d97ab025238663409768fcf205c171102f",
		Purpose: "Investigate bounded questions and return source-backed findings. Dispatch through dispatch_worker when a workflow step owes recorded research findings the contract can bind.", CapabilityClass: "research",
		Capabilities: []string{"read_repository", "search_public_sources", "cite_evidence"}, PacketSchemaRef: "agent-lane-packet.v1", ReportSchemaRef: "agent-lane-report.v1",
		Budgets:             LaneBudgets{CostUSDMax: 2, ContextTokensMax: 32000, TimeSecondsMax: 900},
		EvidenceObligations: []string{"source_citations", "bounded_findings", "uncertainties"}, RequiredReportBlocks: []string{},
		LifecycleStates: []string{"dispatched", "completed", "failed"},
	},
	{
		ID: "implement", Version: 1, Digest: "sha256:f4dad03f0b94430af796eecc1c53740d6441286c78879b46bee17ec79ce604e5",
		Purpose: "Implement one approved bounded engineering task and report verification. Dispatch through dispatch_worker when an approved contract premise needs an isolated worktree change with evidence.", CapabilityClass: "implementation",
		Capabilities: []string{"read_repository", "edit_scoped_files", "run_tests", "report_evidence"}, PacketSchemaRef: "agent-lane-packet.v1", ReportSchemaRef: "agent-lane-report.v1",
		Budgets:             LaneBudgets{CostUSDMax: 4, ContextTokensMax: 48000, TimeSecondsMax: 1800},
		EvidenceObligations: []string{"files_touched", "verification_commands", "unresolved_issues"}, RequiredReportBlocks: []string{},
		LifecycleStates: []string{"dispatched", "completed", "failed"},
	},
	{
		ID: "design", Version: 1, Digest: "sha256:1178f4074a4212eb0e8a95a61aa74a52161b9a275f8a1ef52b5edf4f584c79ef",
		Purpose: "Implement visual UI and UX changes for one approved bounded task and report design evidence. Dispatch through dispatch_worker when an approved contract premise names a visual surface change.", CapabilityClass: "design",
		Capabilities: []string{"read_repository", "edit_scoped_files", "run_targeted_checks", "report_evidence"}, PacketSchemaRef: "agent-lane-packet.v1", ReportSchemaRef: "agent-lane-report.v1",
		Budgets:             LaneBudgets{CostUSDMax: 4, ContextTokensMax: 48000, TimeSecondsMax: 1800},
		EvidenceObligations: []string{"files_touched", "verification_commands", "visual_artifacts", "unresolved_issues"}, RequiredReportBlocks: []string{},
		LifecycleStates: []string{"dispatched", "completed", "failed"},
	},
	{
		ID: "review", Version: 1, Digest: "sha256:3a4cd631ddffb655e6a432bb186af0dfe70113031a79c4d45487f53412f2f15d",
		Purpose: "Review a bounded change against its contract and acceptance evidence. Dispatch through dispatch_worker when a delivered change owes a severity-rated review before completion.", CapabilityClass: "review",
		Capabilities: []string{"read_repository", "inspect_diff", "run_targeted_checks", "report_findings"}, PacketSchemaRef: "agent-lane-packet.v1", ReportSchemaRef: "agent-lane-report.v1",
		Budgets:             LaneBudgets{CostUSDMax: 2.5, ContextTokensMax: 40000, TimeSecondsMax: 1200},
		EvidenceObligations: []string{"contract_findings", "severity", "verification_commands"}, RequiredReportBlocks: []string{"review"},
		LifecycleStates: []string{"dispatched", "completed", "failed"},
	},
	{
		ID: "verify", Version: 1, Digest: "sha256:807c155cf9e41729c4f7446c60b965ecb5519082d0611b67454b4db707e3bfd6",
		Purpose: "Run independent verification and return deterministic pass or failure evidence. Dispatch through dispatch_worker when a contract's outcome predicates need execution evidence a non-author produced.", CapabilityClass: "verification",
		Capabilities: []string{"read_repository", "run_tests", "run_validators", "report_evidence"}, PacketSchemaRef: "agent-lane-packet.v1", ReportSchemaRef: "agent-lane-report.v1",
		Budgets:             LaneBudgets{CostUSDMax: 3, ContextTokensMax: 40000, TimeSecondsMax: 1500},
		EvidenceObligations: []string{"commands", "exit_codes", "failure_classification"}, RequiredReportBlocks: []string{},
		LifecycleStates: []string{"dispatched", "completed", "failed"},
	},
}

// generatedLegacyLaneDigests records, per lane identity, every digest an
// earlier registry generation gave that lane. A persisted worker packet may
// pin one of them, and it resolves to the current definition (CD-0197 D5).
var generatedLegacyLaneDigests = map[string][]string{
	"research:1":  []string{"sha256:e44e36a88bcd2ddc0d144423bcc6b4339c95b92aa44d273b94e49ee0e20901fb", "sha256:3969ceda54cc6be1532877e6d5b1dc5530c280ff77835f43286c4a0ad37e861b"},
	"implement:1": []string{"sha256:84f204c2145897411b16e16f5d6d099ee792213042aecb01f59059090636de85", "sha256:ec541caf3d4df2d5fe70602cf65e747f19e5ac525b001fdd86ea7cf921b737fc"},
	"design:1":    []string{"sha256:50b73594e743bf14dc4ba2fdd8294bb7de64f695ea571a2fff572b5329c649a5"},
	"review:1":    []string{"sha256:cc4d20f113f1bd0a1587afe400b3c3e5421536814efc177bbdda8a4572e53a56", "sha256:49d6fac9d7ebcb95915dd3021e6e2cbd151a569a56221930c0d7a94232736e15"},
	"verify:1":    []string{"sha256:27aa54758f4c90542c1e7d0da567e68bd79f8476cf50fa1590849be29a8a7f4c", "sha256:7999bab09a266d4e5bcda060e0cc75786f7c0678acbde09df7f30dd19fd9eff2"},
}

// generatedWorkerScopeAssignments maps each registered lane to the one
// assigned result a worker attempt completes (contracts/worker-scope.v1.json).
var generatedWorkerScopeAssignments = map[string]string{
	"research":  "bounded_findings",
	"implement": "files_touched",
	"design":    "visual_artifacts",
	"review":    "contract_findings",
	"verify":    "exit_codes",
}
