// Code generated by scripts/generate-durable-tier-budget.py; DO NOT EDIT.
package store

// Durable-tier bounds projected from docs/durable-tier-budget.v1.json. CD-0069
// D1 keeps them in that file alone; scripts/check-durable-tier.py reads it
// directly and the producer reads these, so both surfaces enforce one number.
const (
	// maxDurableNoteBytes bounds the whole serialized note. CD-0002 calls the
	// artifact a page, not a state dump.
	maxDurableNoteBytes = 16384
	// maxDurableFencedJSONBytes bounds any single fenced JSON block inside a
	// note. A note that carries a large embedded document has stopped
	// distilling and started serializing.
	maxDurableFencedJSONBytes = 2048
)
