// Code generated by scripts/generate-agent-lanes.py; DO NOT EDIT.
package store

const LaneRegistryManifestDigest = "sha256:8eb42f5620abb0b87a3661b041fcb12b29620d14ccb985c052fafef2c6b3d3bc"

var generatedLaneDefinitions = []LaneDefinition{
	{
		ID: "research", Version: 1, Digest: "sha256:e44e36a88bcd2ddc0d144423bcc6b4339c95b92aa44d273b94e49ee0e20901fb",
		Purpose: "Investigate bounded questions and return source-backed findings.", CapabilityClass: "research",
		Capabilities: []string{"read_repository", "search_public_sources", "cite_evidence"}, PacketSchemaRef: "agent-lane-packet.v1", ReportSchemaRef: "agent-lane-report.v1",
		Budgets:             LaneBudgets{CostUSDMax: 2, ContextTokensMax: 32000, TimeSecondsMax: 900},
		EvidenceObligations: []string{"source_citations", "bounded_findings", "uncertainties"}, LifecycleStates: []string{"dispatched", "completed", "failed"}, PinnedModel: "openai/gpt-5.6-luna",
	},
	{
		ID: "implement", Version: 1, Digest: "sha256:84f204c2145897411b16e16f5d6d099ee792213042aecb01f59059090636de85",
		Purpose: "Implement one approved bounded engineering task and report verification.", CapabilityClass: "implementation",
		Capabilities: []string{"read_repository", "edit_scoped_files", "run_tests", "report_evidence"}, PacketSchemaRef: "agent-lane-packet.v1", ReportSchemaRef: "agent-lane-report.v1",
		Budgets:             LaneBudgets{CostUSDMax: 4, ContextTokensMax: 48000, TimeSecondsMax: 1800},
		EvidenceObligations: []string{"files_touched", "verification_commands", "unresolved_issues"}, LifecycleStates: []string{"dispatched", "completed", "failed"}, PinnedModel: "openai/gpt-5.6-luna",
	},
	{
		ID: "review", Version: 1, Digest: "sha256:b71b048949a3da7fcb7b06d8aa957f800921f39b98a63990478e69cbd876fc23",
		Purpose: "Review a bounded change against its contract and acceptance evidence.", CapabilityClass: "review",
		Capabilities: []string{"read_repository", "inspect_diff", "run_targeted_checks", "report_findings"}, PacketSchemaRef: "agent-lane-packet.v1", ReportSchemaRef: "agent-lane-report.v1",
		Budgets:             LaneBudgets{CostUSDMax: 2.5, ContextTokensMax: 40000, TimeSecondsMax: 1200},
		EvidenceObligations: []string{"contract_findings", "severity", "verification_commands"}, LifecycleStates: []string{"dispatched", "completed", "failed"}, PinnedModel: "zai-coding-plan/glm-5.2",
	},
	{
		ID: "verify", Version: 1, Digest: "sha256:27aa54758f4c90542c1e7d0da567e68bd79f8476cf50fa1590849be29a8a7f4c",
		Purpose: "Run independent verification and return deterministic pass or failure evidence.", CapabilityClass: "verification",
		Capabilities: []string{"read_repository", "run_tests", "run_validators", "report_evidence"}, PacketSchemaRef: "agent-lane-packet.v1", ReportSchemaRef: "agent-lane-report.v1",
		Budgets:             LaneBudgets{CostUSDMax: 3, ContextTokensMax: 40000, TimeSecondsMax: 1500},
		EvidenceObligations: []string{"commands", "exit_codes", "failure_classification"}, LifecycleStates: []string{"dispatched", "completed", "failed"}, PinnedModel: "openai/gpt-5.6-luna",
	},
}
