// Code generated by scripts/generate-native-run-statuses.py; DO NOT EDIT.
package store

var nativeRunStatuses = map[string]map[string]bool{
	"cleanup":  {"cleaned": false, "cleanup_failed": true},
	"health":   {"degraded": false, "failed": true, "healthy": false},
	"rollback": {"partially_rolled_back": true, "rollback_failed": true, "rolled_back": true},
	"start":    {"failed_to_start": true, "started": false},
}

func NativeRunStatusAllowed(phase, status string) bool {
	_, ok := nativeRunStatuses[phase][status]
	return ok
}

func NativeRunStatusIsFailure(phase, status string) bool {
	return nativeRunStatuses[phase][status]
}
