// Code generated by scripts/generate-relation-vocabulary.py; DO NOT EDIT.
package store

var relationStoredKinds = []string{"blocks", "compatible_with", "depends_on", "forward_link", "implements", "includes", "merged_into", "parent", "raised_from", "supersedes"}

var relationIdentityEventKinds = []string{"initiative_entry.added", "relation.added", "work.reopened_from_superseded", "work.superseded", "workflow.overlap_resolved", "workflow.successor_linked"}

var relationKinds = map[string]bool{
	"blocks":          true,
	"compatible_with": true,
	"depends_on":      true,
	"implements":      true,
	"includes":        true,
	"merged_into":     true,
	"parent":          true,
	"raised_from":     true,
	"supersedes":      true,
}

type relationLinkRefusal struct {
	Message  string
	Recovery string
}

var relationLinkRefusals = map[string]relationLinkRefusal{
	"compatible_with": {Message: "overlap-resolution relations must be created by resolve_overlap", Recovery: "use resolve_overlap so operator approval, version pins, and lifecycle changes remain atomic"},
	"includes":        {Message: "Initiative membership edges must be created by Initiative entry events", Recovery: "append an Initiative entry event"},
	"merged_into":     {Message: "overlap-resolution relations must be created by resolve_overlap", Recovery: "use resolve_overlap so operator approval, version pins, and lifecycle changes remain atomic"},
	"supersedes":      {Message: "supersedes relations must be created by work.superseded", Recovery: "append a work.superseded event so the edge and lifecycle change remain atomic"},
}

var relationTransitiveKinds = map[string]bool{
	"blocks":     true,
	"depends_on": true,
	"includes":   true,
	"parent":     true,
	"supersedes": true,
}

var relationQueryLabels = map[string]relationSpec{
	"blocked_by":      {label: "blocked_by", stored: "blocks", invert: true},
	"blocks":          {label: "blocks", stored: "blocks", invert: false},
	"child_of":        {label: "child_of", stored: "parent", invert: true},
	"compatible_with": {label: "compatible_with", stored: "compatible_with", invert: false},
	"depends_on":      {label: "depends_on", stored: "depends_on", invert: false},
	"forward_link":    {label: "forward_link", stored: "forward_link", invert: false},
	"implemented_by":  {label: "implemented_by", stored: "implements", invert: true},
	"implements":      {label: "implements", stored: "implements", invert: false},
	"included_by":     {label: "included_by", stored: "includes", invert: true},
	"includes":        {label: "includes", stored: "includes", invert: false},
	"merged_into":     {label: "merged_into", stored: "merged_into", invert: false},
	"parent":          {label: "parent", stored: "parent", invert: false},
	"raised":          {label: "raised", stored: "raised_from", invert: true},
	"raised_from":     {label: "raised_from", stored: "raised_from", invert: false},
	"superseded_by":   {label: "superseded_by", stored: "supersedes", invert: true},
	"supersedes":      {label: "supersedes", stored: "supersedes", invert: false},
}

var relationDefaultQueryLabels = []string{"blocks", "compatible_with", "depends_on", "forward_link", "implements", "includes", "merged_into", "parent", "raised_from", "supersedes"}
