package store

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/sharper-flow/concord/internal/payloadschema"
)

// Navigation fixtures use real immutable trees, not the synthetic OIDs of
// the unadopted shared-context fixtures.
func workContextNavigationRepo(t *testing.T, mutate func(map[string]any)) (string, string) {
	t.Helper()
	repo := initKnowledgeRepo(t)
	domains := []map[string]any{}
	for _, id := range []string{workContextTestRoot, workContextTestChild, workContextTestUnaffected} {
		cardPath := ".concord/navigation/domains/" + id + ".md"
		domains = append(domains, map[string]any{"domain_id": id, "card_path": cardPath})
		writeKnowledgeFile(t, repo, cardPath, "<!-- DO NOT EDIT: generated by scripts/generate-domain-navigation.py -->\n# Card\n\nDomain: `"+id+"`. Coarse navigation owner: `domain:"+id+"`.\nPRIVATE-CARD-CONTENT\n")
	}
	inventory := map[string]any{"schema_version": "1.1", "domains": domains, "unresolved_count": 0, "unresolved": []any{}}
	if mutate != nil {
		mutate(inventory)
	}
	writeKnowledgeFile(t, repo, ".concord/navigation/inventory.json", string(mustJSONValue(inventory)))
	writeKnowledgeFile(t, repo, ".concord/domain-navigation.v1.json", `{"schema_version":"1.1","rules":[],"unresolved":[],"mechanisms":[],"catalog_bindings":[],"test_coverage":[],"dependency_interpretations":[]}`)
	writeKnowledgeFile(t, repo, "README.md", "context subject\n")
	return repo, commitKnowledgeRepo(t, repo, "navigation fixture")
}

func workContextNavigationHome(t *testing.T, f workContextFixture, repo, oid string) {
	t.Helper()
	// The law-context locator still opens the designated home's registry;
	// registered-source fixtures never gain this file.
	writeKnowledgeFile(t, repo, knowledgeRegistryPath, `{"schema_version":"1.0","product_key":"product","root_domain_id":"root","domains":[]}`)
	tx, err := f.store.DatabaseForTesting().BeginTx(context.Background(), nil)
	if err != nil {
		t.Fatal(err)
	}
	defer tx.Rollback()
	if err := enterFold(context.Background(), tx); err != nil {
		t.Fatal(err)
	}
	if _, err := tx.Exec(`UPDATE project_locators SET locator_value=?,normalized_value=? WHERE locator_id='workflow-law-locator'`, repo, repo); err != nil {
		t.Fatal(err)
	}
	if _, err := tx.Exec(`UPDATE domain_registries SET scanned_commit_oid=? WHERE product_id='product'`, oid); err != nil {
		t.Fatal(err)
	}
	if err := leaveFold(context.Background(), tx); err != nil {
		t.Fatal(err)
	}
	if err := tx.Commit(); err != nil {
		t.Fatal(err)
	}
}

func workContextNavigationDeclare(t *testing.T, f workContextFixture, readings []map[string]any) {
	t.Helper()
	if err := f.recordWorkContext(t, map[string]any{"required_reading": readings, "finding_refs": []string{}, "context_findings": []any{}}); err != nil {
		t.Fatal(err)
	}
}

func workContextNavigationPreparedContext(t *testing.T, f workContextFixture) context.Context {
	t.Helper()
	ctx, err := prepareWorkNavigation(context.Background(), f.store, f.workID)
	if err != nil {
		t.Fatal(err)
	}
	return ctx
}

func TestWorkContextNavigationPinnedCardsAndDedup(t *testing.T) {
	f := seedWorkContextFixture(t, "navigation-pinned")
	repo, oid := workContextNavigationRepo(t, nil)
	workContextNavigationHome(t, f, repo, oid)
	reading := workContextRepoReading(workContextTestChild, "")
	reading["source"] = map[string]any{"kind": "repository_file", "project_id": "project", "path": ".concord/navigation/domains/child-alpha.md", "commit_oid": oid}
	workContextNavigationDeclare(t, f, []map[string]any{reading})
	// Changed checkout bytes and a later HEAD must not replace the scanned pin.
	writeKnowledgeFile(t, repo, ".concord/navigation/inventory.json", `{"schema_version":"99"}`)
	writeKnowledgeFile(t, repo, ".concord/navigation/domains/root.md", "changed checkout\n")
	commitKnowledgeRepo(t, repo, "later navigation")
	ctx := workContextNavigationPreparedContext(t, f)
	tx, err := f.store.DatabaseForTesting().BeginTx(ctx, nil)
	if err != nil {
		t.Fatal(err)
	}
	defer tx.Rollback()
	view, err := readWorkContextView(ctx, tx, f.workID)
	if err != nil {
		t.Fatal(err)
	}
	if len(view.RequiredReading) != 2 {
		t.Fatalf("required readings = %d, want existing child plus root, deduplicated", len(view.RequiredReading))
	}
	cards := 0
	for _, group := range view.DomainGroups {
		for _, card := range group.DomainCards {
			cards++
			raw := mustJSONValue(card)
			var source WorkContextReadingSource
			if err := json.Unmarshal(raw, &source); err != nil {
				t.Fatal(err)
			}
			if source.Kind != WorkContextSourceRepositoryFile || source.ProjectID != "project" || source.CommitOID != oid || source.Path != ".concord/navigation/domains/"+group.DomainID+".md" {
				t.Fatalf("card source = %s", raw)
			}
		}
	}
	if cards != 2 {
		t.Fatalf("domain cards = %d, want affected child and root once", cards)
	}
	if strings.Contains(string(mustJSONValue(view)), "PRIVATE-CARD-CONTENT") {
		t.Fatal("card content leaked into context")
	}
	if err := validateWorkerPacketWorkContext(ctx, tx, f.workID, mustJSONValue(map[string]any{"inputs": map[string]any{"work_context": view}})); err != nil {
		t.Fatal(err)
	}
}

func TestWorkContextNavigationOverflowRefusesDispatch(t *testing.T) {
	f := seedWorkContextFixture(t, "navigation-overflow")
	repo, oid := workContextNavigationRepo(t, nil)
	workContextNavigationHome(t, f, repo, oid)
	readings := []map[string]any{}
	for i := 0; i < WorkContextRequiredReadingMax; i++ {
		reading := workContextRepoReading(workContextTestChild, "")
		reading["source"] = map[string]any{"kind": "repository_file", "project_id": "project", "path": fmt.Sprintf("reading-%d.md", i), "commit_oid": oid}
		readings = append(readings, reading)
	}
	workContextNavigationDeclare(t, f, readings)
	err := validateWorkerPacketWorkContext(workContextNavigationPreparedContext(t, f), f.store.DatabaseForTesting(), f.workID, mustJSONValue(map[string]any{"inputs": map[string]any{}}))
	if !hasFailureKind(err, KindLimitExceeded) {
		t.Fatalf("overflow dispatch = %v, want limit_exceeded", err)
	}
}

func TestWorkContextNavigationRefusals(t *testing.T) {
	tests := []struct {
		name       string
		mutate     func(map[string]any)
		change     func(*testing.T, string)
		missingPin bool
		kind       FailureKind
	}{
		{name: "unsupported-inventory", mutate: func(m map[string]any) { m["schema_version"] = "1.2" }, kind: KindInvalidNoteProof},
		{name: "unresolved", mutate: func(m map[string]any) { m["unresolved_count"] = 1 }, kind: KindInvalidNoteProof},
		{name: "missing-entry", mutate: func(m map[string]any) { m["domains"] = m["domains"].([]map[string]any)[1:] }, kind: KindInvalidNoteProof},
		{name: "duplicate-domain", mutate: func(m map[string]any) { ds := m["domains"].([]map[string]any); m["domains"] = append(ds, ds[0]) }, kind: KindInvalidNoteProof},
		{name: "unknown-domain", mutate: func(m map[string]any) { m["domains"].([]map[string]any)[0]["domain_id"] = "unknown" }, kind: KindStaleRequiresReview},
		{name: "deprecated-domain", mutate: func(m map[string]any) { m["domains"].([]map[string]any)[0]["domain_id"] = workContextTestDeprecated }, kind: KindStaleRequiresReview},
		{name: "traversal", mutate: func(m map[string]any) { m["domains"].([]map[string]any)[0]["card_path"] = "../card.md" }, kind: KindInvalidPayload},
		{name: "stale-card", change: func(t *testing.T, repo string) {
			writeKnowledgeFile(t, repo, ".concord/navigation/domains/root.md", "Domain: `child-alpha`. Coarse navigation owner: `domain:child-alpha`.\n")
		}, kind: KindStaleRequiresReview},
		{name: "missing-card", change: func(t *testing.T, repo string) {
			runKnowledgeGit(t, repo, "rm", "--", ".concord/navigation/domains/root.md")
		}, kind: KindInvalidNoteProof},
		{name: "missing-inventory", change: func(t *testing.T, repo string) {
			runKnowledgeGit(t, repo, "rm", "--", ".concord/navigation/inventory.json")
		}, kind: KindInvalidNoteProof},
		{name: "missing-companion-with-complete-inventory", change: func(t *testing.T, repo string) {
			runKnowledgeGit(t, repo, "rm", "--", ".concord/domain-navigation.v1.json")
		}, kind: KindInvalidNoteProof},
		{name: "unsupported-companion", change: func(t *testing.T, repo string) {
			writeKnowledgeFile(t, repo, ".concord/domain-navigation.v1.json", `{"schema_version":"1.2"}`)
		}, kind: KindInvalidNoteProof},
		{name: "duplicate-json", change: func(t *testing.T, repo string) {
			writeKnowledgeFile(t, repo, ".concord/navigation/inventory.json", `{"schema_version":"1.1","schema_version":"1.1"}`)
		}, kind: KindInvalidNoteProof},
		{name: "missing-pinned-object", missingPin: true, kind: KindGitUnreachable},
		{name: "symlink-card", change: func(t *testing.T, repo string) {
			path := filepath.Join(repo, ".concord/navigation/domains/root.md")
			if err := os.Remove(path); err != nil {
				t.Fatal(err)
			}
			if err := os.Symlink("child-alpha.md", path); err != nil {
				t.Fatal(err)
			}
		}, kind: KindInvalidNoteProof},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			f := seedWorkContextFixture(t, "navigation-"+test.name)
			workContextNavigationDeclare(t, f, []map[string]any{})
			repo, oid := workContextNavigationRepo(t, test.mutate)
			if test.change != nil {
				test.change(t, repo)
				oid = commitKnowledgeRepo(t, repo, "refusal fixture")
			}
			if test.missingPin {
				oid = strings.Repeat("1", 40)
				// Committed adoption still refuses if the checkout hides both artifacts.
				if err := os.Remove(filepath.Join(repo, ".concord/domain-navigation.v1.json")); err != nil {
					t.Fatal(err)
				}
				if err := os.Remove(filepath.Join(repo, ".concord/navigation/inventory.json")); err != nil {
					t.Fatal(err)
				}
			}
			workContextNavigationHome(t, f, repo, oid)
			err := validateWorkerPacketWorkContext(workContextNavigationPreparedContext(t, f), f.store.DatabaseForTesting(), f.workID, mustJSONValue(map[string]any{"inputs": map[string]any{}}))
			if !hasFailureKind(err, test.kind) {
				t.Fatalf("dispatch = %v, want %s", err, test.kind)
			}
		})
	}
}

func TestWorkContextNavigationAdoptionAndNilBoundary(t *testing.T) {
	for _, version := range []string{"absent", "1.0", "1.1"} {
		t.Run(version, func(t *testing.T) {
			f := seedWorkContextFixture(t, "navigation-boundary-"+version)
			repo, oid := workContextNavigationRepo(t, nil)
			if version == "absent" {
				runKnowledgeGit(t, repo, "rm", "--", ".concord/domain-navigation.v1.json", ".concord/navigation/inventory.json")
			}
			if version == "1.0" {
				writeKnowledgeFile(t, repo, ".concord/domain-navigation.v1.json", `{"schema_version":"1.0","unresolved":[]}`)
			}
			if version != "1.1" {
				oid = commitKnowledgeRepo(t, repo, "historical adoption")
			}
			workContextNavigationHome(t, f, repo, oid)
			view, err := readWorkContextView(workContextNavigationPreparedContext(t, f), f.store.DatabaseForTesting(), f.workID)
			if err != nil {
				t.Fatal(err)
			}
			if version == "1.1" {
				if view == nil || len(view.RequiredReading) != 2 || view.SourceEventFrontier != 0 || len(view.Findings) != 0 {
					t.Fatalf("derived context without declaration = %+v; want two cards, zero frontier and no findings", view)
				}
			} else if view != nil {
				t.Fatalf("unadopted context = %+v, want nil", view)
			}
			workContextNavigationDeclare(t, f, []map[string]any{})
			view, err = readWorkContextView(workContextNavigationPreparedContext(t, f), f.store.DatabaseForTesting(), f.workID)
			if err != nil {
				t.Fatal(err)
			}
			want := 0
			if version == "1.1" {
				want = 2
			}
			if len(view.RequiredReading) != want {
				t.Fatalf("readings = %d, want %d", len(view.RequiredReading), want)
			}
		})
	}
}

func TestWorkContextNavigationRootOutsideAffectedAndBound(t *testing.T) {
	f := seedWorkContextFixture(t, "navigation-root-bound")
	repo, oid := workContextNavigationRepo(t, nil)
	workContextNavigationHome(t, f, repo, oid)
	if _, err := f.store.DatabaseForTesting().Exec(`INSERT INTO fold_guard(active) VALUES(1); DELETE FROM workflow_contract_affected_domains WHERE work_id='navigation-root-bound' AND domain_id='root'; DELETE FROM fold_guard`); err != nil {
		t.Fatal(err)
	}
	readings := []map[string]any{}
	for i := 0; i < WorkContextRequiredReadingMax-2; i++ {
		reading := workContextRepoReading(workContextTestChild, "")
		reading["source"] = map[string]any{"kind": "repository_file", "project_id": "project", "path": fmt.Sprintf("reading-%d.md", i), "commit_oid": oid}
		readings = append(readings, reading)
	}
	workContextNavigationDeclare(t, f, readings)
	view, err := readWorkContextView(workContextNavigationPreparedContext(t, f), f.store.DatabaseForTesting(), f.workID)
	if err != nil {
		t.Fatal(err)
	}
	if len(view.RequiredReading) != WorkContextRequiredReadingMax || len(view.DomainGroups) != 2 || view.DomainGroups[1].DomainID != workContextTestRoot {
		t.Fatalf("root and exact existing bound: %+v", view)
	}
}

func TestWorkContextNavigationRegisteredSourceUsesOwnScannedTree(t *testing.T) {
	for _, scanned := range []bool{false, true} {
		t.Run(fmt.Sprintf("scanned-%t", scanned), func(t *testing.T) {
			f := seedWorkContextFixture(t, fmt.Sprintf("navigation-source-%t", scanned))
			repo, oid := workContextNavigationRepo(t, nil)
			workContextNavigationHome(t, f, repo, oid)
			sourceRepo, sourceOID := workContextNavigationRepo(t, nil)
			home := KnowledgeHome{HomeProjectID: "source-project", HomeLocatorID: "source-locator", RepoPath: sourceRepo, HeadRef: "HEAD"}
			authorizeSourceLocator(t, f.store, home)
			db := f.store.DatabaseForTesting()
			if _, err := db.Exec(`INSERT INTO fold_guard(active) VALUES(1)`); err != nil {
				t.Fatal(err)
			}
			if _, err := db.Exec(`INSERT INTO product_projects(product_id,project_id,role) VALUES('product','source-project','secondary')`); err != nil {
				t.Fatal(err)
			}
			if _, err := db.Exec(`INSERT INTO product_knowledge_sources(product_id,project_id,locator_id,registered_at) VALUES('product','source-project','source-locator','now')`); err != nil {
				t.Fatal(err)
			}
			if scanned {
				if _, err := db.Exec(`INSERT INTO knowledge_index_watermark(home_project_id,home_locator_id,head_ref,scanned_commit_oid,scanned_at,complete,projection_version) VALUES('source-project','source-locator','HEAD',?,'now',1,?)`, sourceOID, knowledgeProjectionVersion); err != nil {
					t.Fatal(err)
				}
			}
			if _, err := db.Exec(`DELETE FROM fold_guard`); err != nil {
				t.Fatal(err)
			}
			if scanned {
				writeKnowledgeFile(t, sourceRepo, ".concord/navigation/inventory.json", `{"schema_version":"unsupported"}`)
				commitKnowledgeRepo(t, sourceRepo, "later registered source")
			}
			if _, err := os.Stat(filepath.Join(sourceRepo, knowledgeRegistryPath)); !os.IsNotExist(err) {
				t.Fatal("registered source unexpectedly carries a copied registry")
			}
			workContextNavigationDeclare(t, f, []map[string]any{})
			view, err := readWorkContextView(workContextNavigationPreparedContext(t, f), db, f.workID)
			if err != nil {
				t.Fatal(err)
			}
			if len(view.RequiredReading) != 4 {
				t.Fatalf("readings = %d, want two Projects' affected and root cards", len(view.RequiredReading))
			}
			for _, group := range view.DomainGroups {
				if len(group.DomainCards) != 2 {
					t.Fatalf("cards = %+v", group.DomainCards)
				}
				for _, card := range group.DomainCards {
					if card.ProjectID == "source-project" && card.CommitOID != sourceOID {
						t.Fatalf("registered source lost its own pin: %+v", card)
					}
				}
			}
		})
	}
}

func TestWorkContextNavigationDistinctReadingRevision(t *testing.T) {
	f := seedWorkContextFixture(t, "navigation-revision")
	repo, scannedOID := workContextNavigationRepo(t, nil)
	workContextNavigationHome(t, f, repo, scannedOID)
	writeKnowledgeFile(t, repo, "README.md", "second context revision\n")
	readingOID := commitKnowledgeRepo(t, repo, "context reading revision")
	reading := workContextRepoReading(workContextTestChild, "")
	reading["source"] = map[string]any{"kind": "repository_file", "project_id": "project", "path": ".concord/navigation/domains/child-alpha.md", "commit_oid": readingOID}
	workContextNavigationDeclare(t, f, []map[string]any{reading})
	view, err := readWorkContextView(workContextNavigationPreparedContext(t, f), f.store.DatabaseForTesting(), f.workID)
	if err != nil {
		t.Fatal(err)
	}
	if len(view.RequiredReading) != 4 {
		t.Fatalf("reading identities collapsed across revisions: %+v", view.RequiredReading)
	}
	for _, group := range view.DomainGroups {
		if len(group.DomainCards) != 2 {
			t.Fatalf("revision cards = %+v", group.DomainCards)
		}
	}
}

func TestWorkContextNavigationInventoryResolvesCardPath(t *testing.T) {
	f := seedWorkContextFixture(t, "navigation-inventory-path")
	const path = ".concord/navigation/root-card.md"
	repo, _ := workContextNavigationRepo(t, func(m map[string]any) { m["domains"].([]map[string]any)[0]["card_path"] = path })
	runKnowledgeGit(t, repo, "mv", "--", ".concord/navigation/domains/root.md", path)
	oid := commitKnowledgeRepo(t, repo, "inventory-resolved card path")
	workContextNavigationHome(t, f, repo, oid)
	workContextNavigationDeclare(t, f, []map[string]any{})
	view, err := readWorkContextView(workContextNavigationPreparedContext(t, f), f.store.DatabaseForTesting(), f.workID)
	if err != nil {
		t.Fatal(err)
	}
	for _, reading := range view.RequiredReading {
		if reading.DomainID == workContextTestRoot && reading.Source.Path != path {
			t.Fatalf("reader inferred a filename instead of using the inventory: %+v", reading)
		}
	}
}

func TestWorkContextNavigationSharedConsumersAndWorktreeBase(t *testing.T) {
	f := seedWorkContextFixture(t, "navigation-consumers")
	workContextNavigationDeclare(t, f, []map[string]any{})
	repo, baseOID := workContextNavigationRepo(t, nil)
	writeKnowledgeFile(t, repo, ".concord/navigation/inventory.json", `{"schema_version":"unsupported"}`)
	commitKnowledgeRepo(t, repo, "changed claimed checkout")
	db := f.store.DatabaseForTesting()
	if _, err := db.Exec(`INSERT INTO fold_guard(active) VALUES(1)`); err != nil {
		t.Fatal(err)
	}
	if _, err := db.Exec(`INSERT INTO worktree_entries(set_id,project_id,claim_op_id,branch,base_sha,path,repository_id,state,verified_at,git_facts) VALUES(?,'project','navigation-claim','navigation-branch',?,?,'navigation-repository','active','now','{}')`, WorktreeSetID(f.workID), baseOID, repo); err != nil {
		t.Fatal(err)
	}
	if _, err := db.Exec(`DELETE FROM fold_guard`); err != nil {
		t.Fatal(err)
	}
	job := seedReadyWorkerJob(t, f)
	ctx := workContextNavigationPreparedContext(t, f)
	view, err := readWorkContextView(ctx, db, f.workID)
	if err != nil {
		t.Fatal(err)
	}
	if len(view.RequiredReading) != 2 || view.RequiredReading[0].Source.CommitOID != baseOID {
		t.Fatalf("claimed base authority lost: %+v", view)
	}
	pin, err := ReadWorkPin(ctx, f.store, f.workID)
	if err != nil {
		t.Fatal(err)
	}
	if err := payloadschema.Validate("work_pin", mustJSONValue(pin)); err != nil {
		t.Fatal(err)
	}
	continuity, err := ReadWorkflowContinuity(ctx, f.store, ContinuityRequest{Work: f.workID})
	if err != nil {
		t.Fatal(err)
	}
	if string(mustJSONValue(pin.WorkContext)) != string(mustJSONValue(view)) || string(mustJSONValue(continuity.WorkContext)) != string(mustJSONValue(view)) {
		t.Fatal("shared consumers changed the derived navigation view")
	}
	packet := workContextDispatchPacket(t, f, "navigation-attempt", job, view)
	if err := dispatchWorkContextAttempt(t, f, packet); err != nil {
		t.Fatal(err)
	}
	if got := dispatchStartedCount(t, f.store, f.workID); got != 1 {
		t.Fatalf("dispatch started count = %d", got)
	}
	var contentEvents int
	if err := db.QueryRow(`SELECT count(*) FROM domain_events WHERE instr(payload,'PRIVATE-CARD-CONTENT')>0`).Scan(&contentEvents); err != nil {
		t.Fatal(err)
	}
	if contentEvents != 0 {
		t.Fatal("card content entered the event log")
	}
}

func TestWorkContextNavigationMissingRegistryAndStaleContract(t *testing.T) {
	for _, missingRegistry := range []bool{false, true} {
		t.Run(fmt.Sprintf("missing-registry-%t", missingRegistry), func(t *testing.T) {
			f := seedWorkContextFixture(t, fmt.Sprintf("navigation-registry-%t", missingRegistry))
			workContextNavigationDeclare(t, f, []map[string]any{})
			repo, oid := workContextNavigationRepo(t, nil)
			workContextNavigationHome(t, f, repo, oid)
			db := f.store.DatabaseForTesting()
			tx, err := db.BeginTx(context.Background(), nil)
			if err != nil {
				t.Fatal(err)
			}
			defer tx.Rollback()
			if err := enterFold(context.Background(), tx); err != nil {
				t.Fatal(err)
			}
			want := KindStaleRequiresReview
			if missingRegistry {
				if _, err := tx.Exec(`DELETE FROM domains WHERE product_id='product'; DELETE FROM domain_registries WHERE product_id='product'`); err != nil {
					t.Fatal(err)
				}
				want = KindDomainRegistryAbsent
			} else {
				// A new registry revision leaves the approved contract immutable.
				hash := "sha256:" + strings.Repeat("c", 64)
				if _, err := tx.Exec(`UPDATE domain_registries SET content_hash=? WHERE product_id='product'`, hash); err != nil {
					t.Fatal(err)
				}
				if _, err := tx.Exec(`UPDATE domains SET registry_content_hash=? WHERE product_id='product'`, hash); err != nil {
					t.Fatal(err)
				}
			}
			if err := leaveFold(context.Background(), tx); err != nil {
				t.Fatal(err)
			}
			if err := tx.Commit(); err != nil {
				t.Fatal(err)
			}
			_, err = readWorkContextView(workContextNavigationPreparedContext(t, f), db, f.workID)
			if !hasFailureKind(err, want) {
				t.Fatalf("registry binding read = %v, want %s", err, want)
			}
		})
	}
}

func TestWorkContextNavigationTransactionUsesPreparedFacts(t *testing.T) {
	f := seedWorkContextFixture(t, "navigation-prepared-tx")
	repo, oid := workContextNavigationRepo(t, nil)
	workContextNavigationHome(t, f, repo, oid)
	ctx := context.Background()
	tx, err := f.store.DatabaseForTesting().BeginTx(ctx, nil)
	if err != nil {
		t.Fatal(err)
	}
	_, err = readWorkContextView(ctx, tx, f.workID)
	if rollbackErr := tx.Rollback(); rollbackErr != nil {
		t.Fatal(rollbackErr)
	}
	if !hasFailureKind(err, KindStaleRequiresReview) {
		t.Fatalf("unprepared transaction = %v, want an explicit proof refusal", err)
	}
	ctx = workContextNavigationPreparedContext(t, f)
	// The immutable facts have been read. Removing object access now makes a
	// subprocess re-read fail; the snapshot must consume only the prepared facts.
	objects := filepath.Join(repo, ".git", "objects")
	if err := os.Rename(objects, objects+"-held"); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		if err := os.Rename(objects+"-held", objects); err != nil {
			t.Error(err)
		}
	})
	tx, err = f.store.DatabaseForTesting().BeginTx(ctx, nil)
	if err != nil {
		t.Fatal(err)
	}
	defer tx.Rollback()
	view, err := readWorkContextView(ctx, tx, f.workID)
	if err != nil {
		t.Fatal(err)
	}
	if view == nil || len(view.RequiredReading) != 2 || view.RequiredReading[0].Source.CommitOID != oid {
		t.Fatalf("prepared navigation = %+v", view)
	}
}

func TestWorkContextNavigationPreparedSourceChangesRefuse(t *testing.T) {
	for _, changeLocator := range []bool{false, true} {
		t.Run(fmt.Sprintf("locator-%t", changeLocator), func(t *testing.T) {
			f := seedWorkContextFixture(t, fmt.Sprintf("navigation-prepared-change-%t", changeLocator))
			repo, oid := workContextNavigationRepo(t, nil)
			workContextNavigationHome(t, f, repo, oid)
			ctx := workContextNavigationPreparedContext(t, f)
			if changeLocator {
				otherRepo, _ := workContextNavigationRepo(t, nil)
				workContextNavigationHome(t, f, otherRepo, oid)
			} else {
				writeKnowledgeFile(t, repo, "README.md", "new source revision\n")
				workContextNavigationHome(t, f, repo, commitKnowledgeRepo(t, repo, "new source revision"))
			}
			tx, err := f.store.DatabaseForTesting().BeginTx(ctx, nil)
			if err != nil {
				t.Fatal(err)
			}
			defer tx.Rollback()
			_, err = readWorkContextView(ctx, tx, f.workID)
			if !hasFailureKind(err, KindStaleRequiresReview) {
				t.Fatalf("changed source = %v, want stale proof refusal", err)
			}
		})
	}
}

func TestWorkContextNavigationFullListPreparesBeforeSnapshot(t *testing.T) {
	f := seedWorkContextFixture(t, "navigation-full-list")
	repo, oid := workContextNavigationRepo(t, nil)
	workContextNavigationHome(t, f, repo, oid)
	result, err := f.store.QueryQ3(context.Background(), Q3Request{Product: "product", WorkIDs: []string{f.workID}, Detail: "full"})
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Items) != 1 || result.Items[0].WorkPin == nil || result.Items[0].WorkPin.WorkContext == nil || len(result.Items[0].WorkPin.WorkContext.RequiredReading) != 2 {
		t.Fatalf("full list navigation = %+v", result.Items)
	}
}

func TestWorkContextNavigationLegacyProofDoesNotHideNewAdoption(t *testing.T) {
	f := seedWorkContextFixture(t, "navigation-legacy-proof")
	repo, _ := workContextNavigationRepo(t, nil)
	runKnowledgeGit(t, repo, "rm", "--", workContextNavigationCompanion, workContextNavigationInventory)
	commitKnowledgeRepo(t, repo, "unadopted source")
	workContextNavigationHome(t, f, repo, strings.Repeat("1", 40))
	ctx := workContextNavigationPreparedContext(t, f)
	writeKnowledgeFile(t, repo, workContextNavigationCompanion, `{"schema_version":"1.1","unresolved":[]}`)
	commitKnowledgeRepo(t, repo, "adopt navigation")
	tx, err := f.store.DatabaseForTesting().BeginTx(ctx, nil)
	if err != nil {
		t.Fatal(err)
	}
	defer tx.Rollback()
	_, err = readWorkContextView(ctx, tx, f.workID)
	if !hasFailureKind(err, KindStaleRequiresReview) {
		t.Fatalf("new adoption after legacy proof = %v, want stale proof refusal", err)
	}
}

func TestWorkContextNavigationUnverifiableLegacyHeadRefuses(t *testing.T) {
	f := seedWorkContextFixture(t, "navigation-legacy-alias")
	repo, _ := workContextNavigationRepo(t, nil)
	runKnowledgeGit(t, repo, "rm", "--", workContextNavigationCompanion, workContextNavigationInventory)
	commitKnowledgeRepo(t, repo, "unadopted source")
	branch := strings.TrimSpace(runKnowledgeGit(t, repo, "symbolic-ref", "HEAD"))
	runKnowledgeGit(t, repo, "symbolic-ref", "refs/heads/alias", branch)
	runKnowledgeGit(t, repo, "symbolic-ref", "HEAD", "refs/heads/alias")
	workContextNavigationHome(t, f, repo, strings.Repeat("1", 40))
	ctx := workContextNavigationPreparedContext(t, f)
	_, err := readWorkContextView(ctx, f.store.DatabaseForTesting(), f.workID)
	if !hasFailureKind(err, KindStaleRequiresReview) {
		t.Fatalf("unverifiable HEAD = %v, want explicit freshness refusal", err)
	}
}

func TestWorkContextNavigationProspectiveReadingUsesClaimedLocator(t *testing.T) {
	f := seedWorkContextFixture(t, "navigation-pending-reading")
	canonical, _ := workContextNavigationRepo(t, nil)
	claimed, base := workContextNavigationRepo(t, nil)
	writeKnowledgeFile(t, claimed, "README.md", "pending declared revision\n")
	readingOID := commitKnowledgeRepo(t, claimed, "pending reading revision")
	authorizeSourceLocator(t, f.store, KnowledgeHome{HomeProjectID: "source-project", HomeLocatorID: "source-locator", RepoPath: canonical, HeadRef: "HEAD"})
	db := f.store.DatabaseForTesting()
	if _, err := db.Exec(`INSERT INTO fold_guard(active) VALUES(1); INSERT INTO product_projects(product_id,project_id,role) VALUES('product','source-project','secondary')`); err != nil {
		t.Fatal(err)
	}
	if _, err := db.Exec(`INSERT INTO worktree_entries(set_id,project_id,claim_op_id,branch,base_sha,path,repository_id,state,verified_at,git_facts) VALUES(?,'source-project','pending-claim','pending-branch',?,?,'pending-repository','active','now','{}')`, WorktreeSetID(f.workID), base, claimed); err != nil {
		t.Fatal(err)
	}
	if _, err := db.Exec(`DELETE FROM fold_guard`); err != nil {
		t.Fatal(err)
	}
	source := WorkContextReadingSource{Kind: WorkContextSourceRepositoryFile, ProjectID: "source-project", Path: "README.md", CommitOID: readingOID}
	ctx, err := f.store.EstablishWorkContextNavigationProof(context.Background(), WorkContextNavigationRequest{WorkIDs: []string{f.workID}, Sources: []WorkContextReadingSource{source}})
	if err != nil {
		t.Fatal(err)
	}
	view := WorkContextView{RequiredReading: []WorkContextReading{{DomainID: workContextTestChild, Reason: "Read the declared source.", Source: source}}}
	_, err = assembleWorkContextNavigation(ctx, db, f.workID, []string{workContextTestChild}, &view)
	if err != nil {
		t.Fatal(err)
	}
	if len(view.RequiredReading) != 5 {
		t.Fatalf("prospective reading lost claimed revisions: %+v", view.RequiredReading)
	}
}

func TestWorkContextNavigationPreparationPreservesReplayWindow(t *testing.T) {
	f := seedWorkContextFixture(t, "navigation-replay-order")
	db := f.store.DatabaseForTesting()
	if _, err := db.Exec(`INSERT INTO fold_guard(active) VALUES(1); UPDATE project_locators SET kind='git_remote' WHERE locator_id=(SELECT home_locator_id FROM domain_registries WHERE product_id='product'); DELETE FROM fold_guard`); err != nil {
		t.Fatal(err)
	}
	called := false
	err := AuthorizeWorkflowActionAtBoundaryWithPreflightTx(context.Background(), f.store, nil, WorkflowActionPreflightRequest{WorkID: f.workID}, nil, f.store.Clock(), func(*Transaction) (bool, error) {
		called = true
		return true, nil
	}, nil, func(*Transaction) error { return nil })
	if err != nil || !called {
		t.Fatalf("source preparation changed replay order: called=%t err=%v", called, err)
	}
}

func TestWorkContextNavigationPreparedLocatorCannotBecomeNonGit(t *testing.T) {
	f := seedWorkContextFixture(t, "navigation-nongit-locator")
	repo, oid := workContextNavigationRepo(t, nil)
	workContextNavigationHome(t, f, repo, oid)
	ctx := workContextNavigationPreparedContext(t, f)
	empty := t.TempDir()
	db := f.store.DatabaseForTesting()
	if _, err := db.Exec(`INSERT INTO fold_guard(active) VALUES(1)`); err != nil {
		t.Fatal(err)
	}
	if _, err := db.Exec(`UPDATE project_locators SET normalized_value=? WHERE locator_id=(SELECT home_locator_id FROM domain_registries WHERE product_id='product')`, empty); err != nil {
		t.Fatal(err)
	}
	if _, err := db.Exec(`DELETE FROM fold_guard`); err != nil {
		t.Fatal(err)
	}
	_, err := readWorkContextView(ctx, db, f.workID)
	if !hasFailureKind(err, KindStaleRequiresReview) {
		t.Fatalf("changed non-Git locator = %v, want freshness refusal", err)
	}
}

func TestWorkContextNavigationLegacyProofNeedsHeadObjects(t *testing.T) {
	f := seedWorkContextFixture(t, "navigation-legacy-objects")
	repo, _ := workContextNavigationRepo(t, nil)
	runKnowledgeGit(t, repo, "rm", "--", workContextNavigationCompanion, workContextNavigationInventory)
	commitKnowledgeRepo(t, repo, "unadopted source")
	workContextNavigationHome(t, f, repo, strings.Repeat("1", 40))
	objects := filepath.Join(repo, ".git", "objects")
	if err := os.Rename(objects, objects+"-unavailable"); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		if err := os.Rename(objects+"-unavailable", objects); err != nil {
			t.Errorf("restore git objects: %v", err)
		}
	})
	ctx := workContextNavigationPreparedContext(t, f)
	_, err := readWorkContextView(ctx, f.store.DatabaseForTesting(), f.workID)
	if err == nil {
		t.Fatal("unreachable HEAD objects accepted as a verified negative proof")
	}
}

func TestWorkContextNavigationClaimPreparesDeclaredRevisions(t *testing.T) {
	f := seedWorkContextFixture(t, "navigation-claim-readings")
	repo, readingOID := workContextNavigationRepo(t, nil)
	writeKnowledgeFile(t, repo, "README.md", "claim base\n")
	base := commitKnowledgeRepo(t, repo, "claim base")
	workContextNavigationHome(t, f, repo, base)
	reading := workContextRepoReading(workContextTestChild, "")
	reading["source"] = map[string]any{"kind": "repository_file", "project_id": "project", "path": "README.md", "commit_oid": readingOID}
	workContextNavigationDeclare(t, f, []map[string]any{reading})
	claimed := filepath.Join(t.TempDir(), "claimed")
	runKnowledgeGit(t, repo, "worktree", "add", "--detach", claimed, base)
	proof := prepareClaimNavigation(context.Background(), f.store, WorktreeClaimRequest{WorkID: f.workID, ProjectID: "project", BaseSHA: base}, claimed)
	for _, oid := range []string{base, readingOID} {
		material, exists := proof.sources[workContextNavigationSource{"project", claimed, oid}]
		if !exists || material.err != nil || len(material.cards) != 3 {
			t.Fatalf("claim revision %s: exists=%t material=%+v", oid, exists, material)
		}
	}
}
