#!/usr/bin/env python3
"""Run deterministic TS8 drift checks and optional Bun syntax validation."""
from __future__ import annotations
import shutil, subprocess, sys, tempfile
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
def main() -> int:
    tamper = subprocess.run([sys.executable, str(ROOT / "scripts/test-agent-contracts.py")], cwd=ROOT)
    if tamper.returncode: return tamper.returncode
    generated = subprocess.run([sys.executable, str(ROOT / "scripts/generate-agent-contracts.py"), "--check"], cwd=ROOT)
    if generated.returncode: return generated.returncode
    bun = shutil.which("bun")
    if bun:
        with tempfile.TemporaryDirectory() as out:
            checked = subprocess.run([bun, "build", "adapter/opencode/generated-contracts.ts", "adapter/opencode/generated-contract-tests.ts", "--outdir", out], cwd=ROOT)
            if checked.returncode: return checked.returncode
            probe = Path(out) / "fixture-probe.ts"
            probe.write_text(f'''import {{ validateGeneratedPayload }} from {str(ROOT / "adapter/opencode/generated-contract-tests.ts").replace(chr(92), "/").__repr__()};
import corpus from {str(ROOT / "contracts/agent-tool-surface.fixtures.json").replace(chr(92), "/").__repr__()} with {{ type: "json" }};
for (const fixture of corpus.fixtures) {{ if (!validateGeneratedPayload(fixture.input_schema, fixture.input_valid) || fixture.input_invalid_cases.some((value: unknown) => validateGeneratedPayload(fixture.input_schema, value)) || !validateGeneratedPayload(fixture.result_schema, fixture.result_valid) || fixture.result_invalid_cases.some((value: unknown) => validateGeneratedPayload(fixture.result_schema, value))) throw new Error(`fixture failed: ${{fixture.operation}}`); }}
''')
            checked = subprocess.run([bun, "run", str(probe)], cwd=ROOT)
            if checked.returncode: return checked.returncode
            adapter = subprocess.run([bun, "build", "adapter/opencode/concord.ts", "--outdir", out, "--external", "@opencode-ai/plugin", "--target", "bun"], cwd=ROOT)
            if adapter.returncode: return adapter.returncode
            adapter_tests = subprocess.run([bun, "test", "adapter/opencode/concord.test.ts"], cwd=ROOT)
            if adapter_tests.returncode: return adapter_tests.returncode
            source = (ROOT / "adapter/opencode/concord.ts").read_text(encoding="utf-8")
            exports = re.findall(r"export const ([A-Za-z_][A-Za-z0-9_]*) = tool\(", source)
            if exports != ["product_view", "work_browse", "work_trace", "knowledge", "work_define", "work_transition", "work_relate", "work_compact"]:
                print(f"adapter export drift: {exports}", file=sys.stderr); return 1
        print("agent contract check passed (Bun syntax/build)")
    else:
        for path in (ROOT / "adapter/opencode/generated-contracts.ts", ROOT / "adapter/opencode/generated-contract-tests.ts"):
            text = path.read_text(encoding="utf-8")
            if "Code generated by scripts/generate-agent-contracts.py" not in text or "manifestDigest" not in text and path.name == "generated-contracts.ts":
                print(f"generated TypeScript marker missing: {path}", file=sys.stderr); return 1
        print("agent contract check passed (deterministic TypeScript fallback; Bun unavailable)")
    return 0
if __name__ == "__main__": raise SystemExit(main())
