"""Repository navigation only: no law identity, law-home, or relation writes.

Rules are case-sensitive POSIX segments. * and ? match within one segment;
** as a whole segment matches zero or more segments, including hidden paths.
Includes form a union per Domain, then excludes subtract. Explicit rules precede
directory defaults; Domains within a tier have no precedence. Named legacy gaps
remain unresolved. The universe is tracked and non-ignored untracked regular
files, plus declared outputs. A missing companion is an opt-out.
Observed Go imports are package-level only; no symbol graph is built or persisted.

A schema_version 1.1 companion keeps the 1.0 rules and adds closed semantic
machinery: mechanisms with law/control/check references resolved through the
composed knowledge manifest and coverage shards (never authored duplicate law
text), catalog bindings joined against the derived CLI, agent, and workflow
catalogs, and dependency interpretations resolved against the exact current
registry relation tuple. Bindings and interpretations are advisory joins:
navigation does not prove dispatch admission at the current workflow step and
is not an import allowlist or an execution gate.
"""

from __future__ import annotations

from fnmatch import fnmatchcase
from functools import lru_cache
import hashlib
import json
from pathlib import Path
import re
import subprocess

import knowledge_index

COMPANION = ".concord/domain-navigation.v1.json"
REGISTRY = ".concord/docs/knowledge/domain-registry.json"
TOOLING = ".concord/tooling.v1.json"
AGENT_SURFACE = "contracts/agent-tool-surface.v1.json"
OUTPUT = ".concord/navigation"
GENERATED = "DO NOT EDIT: generated by scripts/generate-domain-navigation.py"
SCHEMA_1_0 = ("schema_version", "rules", "unresolved", "test_coverage")
SCHEMA_1_1 = (*SCHEMA_1_0, "mechanisms", "catalog_bindings", "dependency_interpretations")
LAW_KINDS = ("constitution", "decision", "spec")
MECHANISM_FIELDS = ("owner_id", "domain_id", "responsibility", "source_paths", "contract_refs",
                    "law_refs", "control_law_ids", "check_ids")
BINDING_FIELDS = ("catalog", "entry_id", "owner_id")
INTERPRETATION_FIELDS = ("source_domain_id", "kind", "target_domain_id", "law_refs", "contract_refs")
CATALOGS = ("cli", "agent", "workflow")
RELATION_KINDS = ("depends_on", "shares_contract_with")
MECHANISM_OWNER = re.compile(r"^mechanism:[a-z0-9][a-z0-9-]{0,63}$")
HEADING = re.compile(r"^ {0,3}#{1,6}(?:[ \t]+(?P<text>\S.*?))?[ \t]*$")
SCENARIO = re.compile(r"^ {0,3}Scenario:[ \t]+(?P<text>\S.*)$")
ADVISORY_NOTES = (
    "Catalog bindings are advisory joins over authored mechanisms; navigation does not prove dispatch admission at the current workflow step.",
    "Dependency interpretations are advisory; they are not an import allowlist or an execution gate.",
    "Observed package imports are package-level only and grant no execution permission; complete lists live in the inventory.",
)
OBSERVED_IMPORT_SEMANTICS = (
    "Package-level observation only: an import names a package, not a symbol; intra-package edges are unmeasurable and unmeasured.",
    "No symbol graph is built or persisted.",
    "Observed imports grant no execution permission and are not an import allowlist; dependency interpretations stay advisory.",
)


class NavigationError(ValueError):
    pass


def git(root: Path, *args: str) -> bytes:
    result = subprocess.run(["git", "-C", str(root), *args], capture_output=True)
    if result.returncode:
        raise NavigationError(f"git {' '.join(args)}: {result.stderr.decode().strip()}")
    return result.stdout


def unique_object(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise NavigationError(f"duplicate JSON key: {key}")
        result[key] = value
    return result


def decode(data: bytes):
    return json.loads(data, object_pairs_hook=unique_object)


def read_json(root: Path, path: str):
    return decode((root / path).read_bytes())


def selector(value: str, *, pattern: bool = False) -> str:
    if not isinstance(value, str) or not re.fullmatch(r"[A-Za-z0-9_.:/%*?-]+", value):
        raise NavigationError(f"invalid repository selector: {value!r}")
    parts = value.split("/")
    if value.startswith("/") or any(p in ("", ".", "..") for p in parts):
        raise NavigationError(f"selector must be repository-relative and normalized: {value!r}")
    if any("**" in p and p != "**" for p in parts) or (not pattern and any("*" in p or "?" in p for p in parts)):
        raise NavigationError(f"invalid wildcard selector: {value!r}")
    return value


def matches(path: str, pattern: str) -> bool:
    parts, patterns = path.split("/"), pattern.split("/")

    @lru_cache(None)
    def match(i, j):
        if j == len(patterns):
            return i == len(parts)
        if patterns[j] == "**":
            return match(i, j + 1) or (i < len(parts) and match(i + 1, j))
        return i < len(parts) and fnmatchcase(parts[i], patterns[j]) and match(i + 1, j + 1)

    return match(0, 0)


def card_path(domain_id: str) -> str:
    """Use colon-free ASCII slugs without changing the Domain identity."""
    if not re.fullmatch(r"[a-z0-9:-]+", domain_id):
        raise NavigationError(f"Domain ID cannot name a card: {domain_id!r}")
    slug = domain_id.replace(":", "--")
    return f"{OUTPUT}/domains/{slug}.md"


def expected_paths(registry: dict) -> set[str]:
    cards = {}
    for domain in registry["domains"]:
        if domain["status"] != "current":
            continue
        domain_id = domain["domain_id"]
        path = card_path(domain_id)
        if path in cards:
            raise NavigationError(f"card filename collision: {cards[path]} and {domain_id}: {path}")
        cards[path] = domain_id
    return {f"{OUTPUT}/inventory.json", *cards}


def repository_paths(root: Path) -> set[str]:
    return {p for p in git(root, "ls-files", "-co", "--exclude-standard", "-z").decode().split("\0")
            if p and ((root / p).is_file() or (root / p).is_symlink())}


def closed(value, fields, subject):
    if not isinstance(value, dict) or set(value) != set(fields):
        raise NavigationError(f"{subject}: expected exactly {', '.join(sorted(fields))}")


def strings(value, subject):
    if not isinstance(value, list) or any(not isinstance(v, str) or not v for v in value) or len(set(value)) != len(value):
        raise NavigationError(f"{subject}: expected distinct nonempty strings")
    return value


def rule_set(root: Path, items: list, domains: set[str], files: set[str], root_id: str, *, defaults: bool = False) -> dict:
    if not isinstance(items, list):
        raise NavigationError("navigation rules must be an array")
    rules = {}
    for rule in items:
        closed(rule, ("domain_id", "include", "exclude"), "navigation rule")
        domain = rule["domain_id"]
        if not isinstance(domain, str) or domain not in domains or domain in rules:
            raise NavigationError(f"unknown or duplicate navigation Domain: {domain!r}")
        for field in ("include", "exclude"):
            for pattern in strings(rule[field], f"{domain}.{field}"):
                selector(pattern, pattern=True)
                if defaults:
                    parts = pattern.split("/")
                    fixed = []
                    for segment in parts:
                        if "*" in segment or "?" in segment:
                            break
                        fixed.append(segment)
                    if len(fixed) == len(parts):
                        fixed.pop()
                    if not fixed or not (root / "/".join(fixed)).is_dir():
                        raise NavigationError(f"directory default must name an existing directory: {pattern}")
                elif not any(matches(p, pattern) for p in files):
                    raise NavigationError(f"dead navigation rule: {domain}: {pattern}")
        if domain == root_id and any(p in ("*", "**", "**/*") for p in rule["include"]):
            raise NavigationError("the root Domain is not a file catch-all")
        rules[domain] = rule
    return rules


def assigned_domains(path: str, rules: dict) -> list[str]:
    return [domain for domain, rule in rules.items()
            if any(matches(path, p) for p in rule["include"])
            and not any(matches(path, p) for p in rule["exclude"])]


def mapping_remediation(path: str) -> str:
    return f"{path}; navmap-style remediation: add an explicit rule or directory default in {COMPANION}"


def partition(root: Path, registry: dict, *, base_ref: str = "HEAD") -> dict:
    base_ref = git(root, "rev-parse", "--verify", "--end-of-options", f"{base_ref}^{{commit}}").decode().strip()
    navigation = read_json(root, COMPANION)
    if not isinstance(navigation, dict):
        raise NavigationError(f"{COMPANION}: expected an object")
    version = navigation.get("schema_version")
    if version not in ("1.0", "1.1"):
        raise NavigationError("navigation schema_version must be 1.0 or 1.1")
    fields = SCHEMA_1_1 if version == "1.1" else SCHEMA_1_0
    if "default_rules" in navigation:
        fields += ("default_rules",)
    closed(navigation, fields, COMPANION)
    for field in fields[1:]:
        if not isinstance(navigation[field], list):
            raise NavigationError(f"navigation {field} must be an array")
    if version == "1.1" and navigation["unresolved"]:
        raise NavigationError("navigation schema_version 1.1 requires an empty unresolved list")
    domains = {d["domain_id"] for d in registry["domains"] if d["status"] == "current"}
    repo_files = repository_paths(root)
    files = repo_files | expected_paths(registry)
    for path in files:
        selector(path)
        target = root / path
        if target.is_symlink() or not target.resolve().is_relative_to(root.resolve()):
            raise NavigationError(f"navigation source escapes or is a symlink: {path}")
    rules = rule_set(root, navigation["rules"], domains, files, registry["root_domain_id"])
    defaults = rule_set(root, navigation.get("default_rules", []), domains, files, registry["root_domain_id"], defaults=True)
    if set(rules) != domains:
        raise NavigationError("navigation rules must name every current Domain exactly once")
    unresolved = {}
    for item in navigation["unresolved"]:
        closed(item, ("path", "candidate_domain_ids", "reason"), "unresolved entry")
        path = selector(item["path"])
        if path not in files or path in unresolved or path in expected_paths(registry):
            raise NavigationError(f"missing, duplicate, or generated unresolved path: {path}")
        candidates = strings(item["candidate_domain_ids"], f"{path}.candidate_domain_ids")
        if not candidates or not set(candidates) <= domains:
            raise NavigationError(f"unresolved candidates must name current Domains: {path}")
        if not isinstance(item["reason"], str) or not item["reason"].strip() or len(item["reason"]) > 512:
            raise NavigationError(f"unresolved reason must be nonempty and at most 512 characters: {path}")
        unresolved[path] = item
    owners = {}
    for path in sorted(files):
        assigned = assigned_domains(path, rules)
        if len(assigned) > 1 or (assigned and path in unresolved):
            raise NavigationError(f"overlapping navigation owners: {path}: {assigned}")
        if not assigned and path not in unresolved:
            assigned = assigned_domains(path, defaults)
            if len(assigned) > 1:
                raise NavigationError(f"overlapping default navigation owners: {path}: {assigned}")
            if not assigned:
                raise NavigationError(f"unmapped repository path: {mapping_remediation(path)}")
        if assigned:
            owners[path] = assigned[0]
    baseline_paths = set(git(root, "ls-tree", "-r", "--name-only", "-z", base_ref).decode().split("\0"))
    if COMPANION in baseline_paths:
        previous = decode(git(root, "show", f"{base_ref}:{COMPANION}"))
        previous_unresolved = {item["path"] for item in previous["unresolved"]}
        if not set(unresolved) <= previous_unresolved:
            raise NavigationError("legacy unresolved list may only shrink")
    changed = set(git(root, "diff", "--name-only", "-z", base_ref, "--").decode().split("\0"))
    advisories = []
    for path in unresolved:
        if path not in baseline_paths:
            raise NavigationError(f"new unresolved path must map: {mapping_remediation(path)}")
        if path in changed or git(root, "show", f"{base_ref}:{path}") != (root / path).read_bytes():
            advisories.append(f"domain navigation advisory: changed legacy unresolved path: {path}; ownership remains unresolved")
    coverage = {}
    for item in navigation["test_coverage"]:
        closed(item, ("path", "covers_owner_ids"), "test coverage")
        path = selector(item["path"])
        if path not in owners or path in coverage or not is_test(path):
            raise NavigationError(f"shared test must have one mapped test-file owner: {path}")
        targets = strings(item["covers_owner_ids"], f"{path}.covers_owner_ids")
        if not targets or not set(targets) <= {f"domain:{d}" for d in domains}:
            raise NavigationError(f"unknown covered owner: {path}")
        coverage[path] = targets
    state = {"navigation": navigation, "owners": owners, "unresolved": unresolved, "coverage": coverage,
             "default_rules": defaults, "advisories": advisories}
    if version == "1.1":
        state["semantics"] = read_semantics(root, registry, navigation, domains=domains, repo_files=repo_files)
    return state


def law_records(root: Path) -> dict:
    """The composed knowledge manifest's records, keyed by distinct id."""
    manifest = knowledge_index.compose_manifest(root)
    if not isinstance(manifest, dict) or not isinstance(manifest.get("records"), list):
        raise NavigationError("composed knowledge manifest must carry a records array")
    records = {}
    for record in manifest["records"]:
        if not isinstance(record, dict):
            raise NavigationError("knowledge record must be an object")
        identifier = record.get("id")
        if not isinstance(identifier, str) or not identifier or identifier in records:
            raise NavigationError(f"knowledge record id must be distinct nonempty text: {identifier!r}")
        records[identifier] = record
    return records


def law_document(root: Path, records: dict, law_id: str, anchors: dict) -> tuple[str, set[str]]:
    """The law record's locator and its exact Markdown heading and criterion IDs.

    ATX headings anchor a section outside fenced code blocks; `Scenario:`
    criteria are the Gherkin acceptance criteria inside them, mirroring the
    doc-contract reader's grammar.
    """
    record = records.get(law_id)
    if record is None:
        raise NavigationError(f"unknown law id: {law_id}")
    if record.get("kind") not in LAW_KINDS:
        raise NavigationError(f"knowledge record is not law: {law_id} (kind {record.get('kind')!r})")
    locator = record.get("path")
    if not isinstance(locator, str) or not locator:
        raise NavigationError(f"law record must carry a locator path: {law_id}")
    locator = selector(locator)
    if locator not in anchors:
        target = root / locator
        if target.is_symlink() or not target.resolve().is_relative_to(root.resolve()) or not target.is_file():
            raise NavigationError(f"law source is missing or escapes: {law_id}: {locator}")
        try:
            lines = target.read_text(encoding="utf-8").splitlines()
        except UnicodeDecodeError as exc:
            raise NavigationError(f"law source is not UTF-8: {law_id}: {locator}: {exc}") from exc
        found, fence = set(), None
        for line in lines:
            stripped = line.lstrip(" \t")
            if fence is not None:
                if stripped.startswith(fence):
                    fence = None
                else:
                    match = SCENARIO.match(line)
                    if match:
                        found.add(match.group("text").rstrip())
                continue
            if stripped.startswith("```") or stripped.startswith("~~~"):
                fence = stripped[:3]
                continue
            match = HEADING.match(line)
            if match and match.group("text"):
                found.add(match.group("text").rstrip())
        anchors[locator] = found
    return locator, anchors[locator]


def resolve_law_refs(root: Path, records: dict, refs, anchors: dict, subject: str) -> list[dict]:
    """Resolve {law_id, clause_id} refs against composed knowledge.

    The emitted reference carries the owning source's current locator and
    content hash; law text is never duplicated from the companion.
    """
    if not isinstance(refs, list) or not refs:
        raise NavigationError(f"{subject}: law_refs must be a nonempty array")
    resolved, seen = [], set()
    for ref in refs:
        closed(ref, ("law_id", "clause_id"), f"{subject} law ref")
        law_id, clause_id = ref["law_id"], ref["clause_id"]
        if not isinstance(law_id, str) or not law_id or not isinstance(clause_id, str) or not clause_id:
            raise NavigationError(f"{subject}: law ref must carry nonempty law_id and clause_id")
        if (law_id, clause_id) in seen:
            raise NavigationError(f"{subject}: duplicate law ref: {law_id}: {clause_id}")
        seen.add((law_id, clause_id))
        locator, clauses = law_document(root, records, law_id, anchors)
        if clause_id not in clauses:
            raise NavigationError(f"law clause is absent: {law_id}: {clause_id!r}")
        resolved.append({"law_id": law_id, "clause_id": clause_id, "locator": locator,
                         "content_hash": sha((root / locator).read_bytes())})
    return resolved


def repository_files(refs, repo_files: set[str], subject: str, *, required: bool) -> list[str]:
    """Normalized, distinct, currently existing regular repository files."""
    paths = strings(refs, subject)
    if required and not paths:
        raise NavigationError(f"{subject}: must name at least one repository file")
    for path in paths:
        selector(path)
        if path not in repo_files:
            raise NavigationError(f"{subject} must name a tracked or unignored repository file: {path}")
    return sorted(paths)


def coverage_records(root: Path) -> dict:
    data = knowledge_index.compose_law_coverage_bytes(root)
    document = json.loads(data)
    if not isinstance(document, dict) or not isinstance(document.get("records"), list):
        raise NavigationError("composed law coverage must carry a records array")
    records = {}
    for record in document["records"]:
        if not isinstance(record, dict) or not isinstance(record.get("id"), str):
            raise NavigationError("coverage record must carry an id")
        records[record["id"]] = record
    return records


def read_semantics(root: Path, registry: dict, navigation: dict, *, domains: set[str], repo_files: set[str]) -> dict:
    """Validate and resolve the 1.1 semantic companion sections."""
    records = law_records(root)
    coverage = coverage_records(root)
    tools = read_json(root, TOOLING)
    if not isinstance(tools, dict) or not isinstance(tools.get("tools"), list):
        raise NavigationError(f"{TOOLING}: expected a tools array")
    tool_ids = {tool.get("id") for tool in tools["tools"] if isinstance(tool, dict)}
    anchors: dict[str, set[str]] = {}
    mechanisms = {}
    for mechanism in navigation["mechanisms"]:
        closed(mechanism, MECHANISM_FIELDS, "mechanism")
        owner = mechanism["owner_id"]
        if not isinstance(owner, str) or not MECHANISM_OWNER.fullmatch(owner) or owner in mechanisms:
            raise NavigationError(f"mechanism owner_id must be a distinct bounded stable id (mechanism:<slug>): {owner!r}")
        domain = mechanism["domain_id"]
        if not isinstance(domain, str) or domain not in domains:
            raise NavigationError(f"mechanism must name a current Domain: {owner}: {domain!r}")
        responsibility = mechanism["responsibility"]
        if (not isinstance(responsibility, str) or not responsibility.strip()
                or len(responsibility.encode("utf-8")) > 512):
            raise NavigationError(f"mechanism responsibility must be nonempty and at most 512 bytes: {owner}")
        resolved = {
            "owner_id": owner, "domain_id": domain, "responsibility": responsibility,
            "source_paths": repository_files(mechanism["source_paths"], repo_files, f"{owner}.source_paths", required=True),
            "contract_refs": repository_files(mechanism["contract_refs"], repo_files, f"{owner}.contract_refs", required=True),
            "law_refs": resolve_law_refs(root, records, mechanism["law_refs"], anchors, owner),
            "control_law_ids": [], "controls": [], "check_ids": strings(mechanism["check_ids"], f"{owner}.check_ids"),
        }
        for identifier in strings(mechanism["control_law_ids"], f"{owner}.control_law_ids"):
            if identifier not in coverage:
                raise NavigationError(f"unknown law coverage shard: {owner}: {identifier}")
            resolved["control_law_ids"].append(identifier)
            resolved["controls"].append(coverage[identifier])
        for identifier in resolved["check_ids"]:
            if identifier not in tool_ids:
                raise NavigationError(f"unknown tooling check: {owner}: {identifier}")
        mechanisms[owner] = resolved
    bindings, bound = [], set()
    for binding in navigation["catalog_bindings"]:
        closed(binding, BINDING_FIELDS, "catalog binding")
        catalog, entry, owner = binding["catalog"], binding["entry_id"], binding["owner_id"]
        if catalog not in CATALOGS:
            raise NavigationError(f"catalog binding catalog must be one of {', '.join(CATALOGS)}: {catalog!r}")
        if not isinstance(entry, str) or not entry:
            raise NavigationError(f"catalog binding entry_id must be nonempty text: {entry!r}")
        if owner not in mechanisms:
            raise NavigationError(f"catalog binding names an unknown mechanism: {owner!r}")
        if (catalog, entry) in bound:
            raise NavigationError(f"duplicate catalog binding: {catalog}: {entry}")
        bound.add((catalog, entry))
        bindings.append({"catalog": catalog, "entry_id": entry, "owner_id": owner})
    tuples = {(domain["domain_id"], relation["kind"], relation["target_domain_id"]): relation["governing_law_ids"]
              for domain in registry["domains"] if domain["status"] == "current"
              for relation in domain.get("architecture_relations", [])}
    interpretations, seen_tuples = [], set()
    for interpretation in navigation["dependency_interpretations"]:
        closed(interpretation, INTERPRETATION_FIELDS, "dependency interpretation")
        source, kind, target = interpretation["source_domain_id"], interpretation["kind"], interpretation["target_domain_id"]
        if source not in domains or target not in domains:
            raise NavigationError(f"dependency interpretation must name current Domains: {source!r} -> {target!r}")
        if kind not in RELATION_KINDS:
            raise NavigationError(f"dependency interpretation kind must be one of {', '.join(RELATION_KINDS)}: {kind!r}")
        key = (source, kind, target)
        if key not in tuples:
            raise NavigationError(f"dependency interpretation has no current registry relation: {key}")
        if key in seen_tuples:
            raise NavigationError(f"duplicate dependency interpretation: {key}")
        seen_tuples.add(key)
        contract_refs = repository_files(interpretation["contract_refs"], repo_files,
                                         f"interpretation {source}->{target}.contract_refs", required=False)
        if kind == "shares_contract_with" and not contract_refs:
            raise NavigationError(f"shares_contract_with interpretation must reference the shared contract: {source}->{target}")
        resolved_refs = resolve_law_refs(root, records, interpretation["law_refs"], anchors, f"interpretation {source}->{target}")
        if {ref["law_id"] for ref in resolved_refs} != set(tuples[key]):
            raise NavigationError(f"interpretation law refs must equal the registry tuple's governing law ids: {key}: {sorted(tuples[key])}")
        interpretations.append({"source_domain_id": source, "kind": kind, "target_domain_id": target,
                                "law_refs": resolved_refs, "contract_refs": contract_refs})
    return {"mechanisms": sorted(mechanisms.values(), key=lambda m: m["owner_id"]),
            "catalog_bindings": sorted(bindings, key=lambda b: (b["catalog"], b["entry_id"])),
            "dependency_interpretations": sorted(interpretations, key=lambda i: (i["source_domain_id"], i["kind"], i["target_domain_id"]))}


def validate_companion(root: Path, registry: dict, *, base_ref: str = "HEAD") -> tuple[list[str], list[str]]:
    """Blocking partition and complete-navigation semantic findings.

    Changed legacy unresolved paths remain advisory, including in strict mode.
    Complete navigation also joins the source catalogs before validation passes.
    """
    try:
        if not (root / COMPANION).exists():
            if (root / ".git").exists():
                base = git(root, "rev-parse", "--verify", "--end-of-options", f"{base_ref}^{{commit}}").decode().strip()
                if COMPANION in git(root, "ls-tree", "-r", "--name-only", base).decode().splitlines():
                    return ["domain navigation: an adopted companion cannot be removed"], []
            return [], []
        state = partition(root, registry, base_ref=base_ref)
        if "semantics" in state:
            join_catalogs(state["semantics"], catalogs(root, workflow=True))
    except (NavigationError, OSError, ValueError, KeyError, TypeError) as exc:
        return [f"domain navigation: {exc}"], []
    return [], state["advisories"]


def is_test(path: str) -> bool:
    name = Path(path).name
    return name.endswith("_test.go") or ".test." in name or ".spec." in name or name.startswith(("test-", "test_"))


def sha(data: bytes) -> str:
    return "sha256:" + hashlib.sha256(data).hexdigest()


def catalogs(root: Path, *, workflow: bool) -> dict:
    """Derive the CLI, agent, and workflow catalogs from their owning sources.

    The CLI catalog joins the commandSpecs canonical verbs with the commands
    main.go dispatches on args[0] before commandSpecs routing; the workflow
    catalog reuses the existing action-contracts projection rather than a
    second extractor.
    """
    cli = subprocess.run(["go", "run", "./scripts/domain-navigation-cli", "cmd/concord/main.go"],
                         cwd=root, capture_output=True, text=True)
    if cli.returncode:
        raise NavigationError(f"commandSpecs extraction failed: {cli.stderr.strip()}")
    extracted = json.loads(cli.stdout)
    verbs, early = extracted["verbs"], extracted["early_dispatch"]
    if len({v["canonical"] for v in verbs}) != len(verbs):
        raise NavigationError("CLI catalog has duplicate canonical verbs")
    surface = read_json(root, AGENT_SURFACE)
    operations = sorted(op for tool in surface["tools"] for op in tool["operations"])
    if len(operations) != len(set(operations)):
        raise NavigationError("agent catalog has duplicate operations")
    actions: list[str] = []
    if workflow:
        projection = subprocess.run(["go", "run", "./scripts/workflow-action-contracts"],
                                    cwd=root, capture_output=True, text=True)
        if projection.returncode:
            raise NavigationError(f"workflow action projection failed: {projection.stderr.strip()}")
        actions = sorted(action["id"] for action in json.loads(projection.stdout)["actions"])
        if len(actions) != len(set(actions)):
            raise NavigationError("workflow catalog has duplicate actions")
    return {"verbs": verbs, "early_dispatch": sorted(early),
            "entries": {"cli": sorted({v["canonical"] for v in verbs} | set(early)),
                        "agent": operations, "workflow": actions}}


def join_catalogs(semantics: dict, derived: dict) -> dict:
    """Refuse bindings that name unknown entries or leave derived entries uncovered."""
    bound = {(b["catalog"], b["entry_id"]) for b in semantics["catalog_bindings"]}
    for binding in semantics["catalog_bindings"]:
        if binding["entry_id"] not in derived["entries"][binding["catalog"]]:
            raise NavigationError(f"unknown catalog entry: {binding['catalog']}: {binding['entry_id']}")
    for catalog in CATALOGS:
        missing = set(derived["entries"][catalog]) - {entry for owner, entry in bound if owner == catalog}
        if missing:
            raise NavigationError(f"uncovered catalog entries: {catalog}: {sorted(missing)}")
    return {catalog: len(derived["entries"][catalog]) for catalog in CATALOGS}


def import_observations(root: Path, owners: dict, module: str) -> dict:
    """Package-level observed Go imports per Domain, from the AST helper.

    An import names a package, not a symbol: intra-package edges are
    unmeasurable, no symbol graph is built, and nothing here grants execution
    permission or acts as an import allowlist.
    """
    paths = sorted(path for path in owners if path.endswith(".go"))
    observed = subprocess.run(["go", "run", "./scripts/domain-navigation-cli", "--imports", ".", *paths],
                              cwd=root, capture_output=True, text=True)
    if observed.returncode:
        raise NavigationError(f"observed import extraction failed: {observed.stderr.strip()}")
    data = json.loads(observed.stdout)
    if not isinstance(data, dict):
        raise NavigationError("observed import extraction must return an object")

    def package_path(path: str) -> str:
        parent = str(Path(path).parent)
        return module if parent == "." else module + "/" + parent

    imports_by_domain: dict[str, set[str]] = {}
    package_owners: dict[str, set[str]] = {}
    for path, home in owners.items():
        record = data.get(path)
        if record is None or not path.endswith(".go"):
            continue
        imports_by_domain.setdefault(home, set()).update(record.get("imports") or [])
        package_owners.setdefault(package_path(path), set()).add(home)
    result = {}
    for domain, imports in imports_by_domain.items():
        edges = []
        for path in sorted(imports):
            targets = sorted(package_owners.get(path, ()))
            if targets and targets != [domain]:
                edges.append({"import_path": path, "target_domain_ids": targets})
        result[domain] = {"observed_imports": sorted(imports), "observed_package_edges": edges}
    return result


def inventory(root: Path, registry: dict, *, base_ref: str = "HEAD") -> dict:
    state = partition(root, registry, base_ref=base_ref)
    version = state["navigation"]["schema_version"]
    semantics = state.get("semantics")
    module_lines = re.findall(r'^module\s+(\S+)\s*$', (root / "go.mod").read_text(), re.M)
    if len(module_lines) != 1:
        raise NavigationError("go.mod must declare exactly one module path")
    module = module_lines[0].strip('"')
    derived = catalogs(root, workflow=semantics is not None)
    commands, early, operations = derived["verbs"], derived["early_dispatch"], derived["entries"]["agent"]
    sizes = join_catalogs(semantics, derived) if semantics is not None else None
    tools = read_json(root, TOOLING)["tools"]
    owners = state["owners"]
    observed = import_observations(root, owners, module)
    domains = []
    for domain in sorted(registry["domains"], key=lambda d: d["domain_id"]):
        if domain["status"] != "current":
            continue
        domain_id = domain["domain_id"]
        paths = sorted(p for p, home in owners.items() if home == domain_id)
        tests = [p for p in paths if is_test(p)]
        candidates = sorted(p for p, item in state["unresolved"].items() if domain_id in item["candidate_domain_ids"])
        rule = next(r for r in state["navigation"]["rules"] if r["domain_id"] == domain_id)
        record = {"domain_id": domain_id, "owner_id": f"domain:{domain_id}", "name": domain["name"],
                  "purpose": domain["purpose"], "card_path": card_path(domain_id), "path_rules": rule,
                  "default_path_rules": state["default_rules"].get(domain_id),
                  "mapped_count": len(paths), "test_count": len(tests), "unresolved_candidate_count": len(candidates),
                  "unresolved_candidates": candidates,
                  "test_packages": sorted({module + "/" + str(Path(p).parent) for p in tests if p.endswith(".go")}),
                  "test_paths": tests,
                  "cli_verbs": commands if owners.get("cmd/concord/main.go") == domain_id else [],
                  "cli_early_dispatch": early if owners.get("cmd/concord/main.go") == domain_id else [],
                  "agent_operations": operations if owners.get(AGENT_SURFACE) == domain_id else [],
                  "checks": tools,
                  **observed.get(domain_id, {"observed_imports": [], "observed_package_edges": []})}
        if semantics is not None:
            mechanisms = [m for m in semantics["mechanisms"] if m["domain_id"] == domain_id]
            owned = {m["owner_id"] for m in mechanisms}
            record["mechanism_owner_ids"] = sorted(owned)
            record["mechanisms"] = mechanisms
            record["bound_entries"] = {catalog: sorted(b["entry_id"] for b in semantics["catalog_bindings"]
                                                       if b["catalog"] == catalog and b["owner_id"] in owned)
                                       for catalog in CATALOGS}
            record["dependency_interpretations_from"] = sorted(
                ({"kind": i["kind"], "target_domain_id": i["target_domain_id"]}
                 for i in semantics["dependency_interpretations"] if i["source_domain_id"] == domain_id),
                key=lambda i: (i["kind"], i["target_domain_id"]))
            record["dependency_interpretations_to"] = sorted(
                ({"kind": i["kind"], "source_domain_id": i["source_domain_id"]}
                 for i in semantics["dependency_interpretations"] if i["target_domain_id"] == domain_id),
                key=lambda i: (i["kind"], i["source_domain_id"]))
        domains.append(record)
    scope = ("coarse file navigation, not law homes or semantic mechanism ownership" if version == "1.0" else
             "coarse file navigation plus advisory mechanism, catalog, and dependency semantics; "
             "not dispatch admission or import allowlists")
    result = {"_generated": GENERATED, "schema_version": version, "scope": scope,
              "mapped_count": len(owners), "unresolved_count": len(state["unresolved"]), "domains": domains,
              "files": owners, "unresolved": sorted(state["unresolved"].values(), key=lambda i: i["path"]),
              "test_coverage": state["coverage"],
              "observed_import_semantics": list(OBSERVED_IMPORT_SEMANTICS)}
    if semantics is not None:
        result.update({"mechanisms": semantics["mechanisms"],
                       "catalog_bindings": semantics["catalog_bindings"], "catalog_sizes": sizes,
                       "dependency_interpretations": semantics["dependency_interpretations"],
                       "advisory_notes": list(ADVISORY_NOTES)})
    return result


def card(domain: dict) -> str:
    lines = [f"<!-- {GENERATED} -->", f"# {domain['name']}", "",
             f"Domain: `{domain['domain_id']}`. Coarse navigation owner: `{domain['owner_id']}`.",
             "File accountability does not change a document's law home or a handler's semantic owner.", "",
             "## Responsibility", domain["purpose"], "",
             f"Mapped files: {domain['mapped_count']}; tests: {domain['test_count']}; unresolved candidates: {domain['unresolved_candidate_count']}.",
             "Candidate counts overlap when a file has several candidates; no candidate is an assigned owner.", "",
             "## Code and tests", "Full paths, unresolved reasons, and shared-test coverage: `.concord/navigation/inventory.json`."]
    for field, label in (("include", "Include"), ("exclude", "Exclude")):
        patterns = domain["path_rules"][field]
        for start in range(0, len(patterns), 5):
            lines.append(f"- {label}: " + ", ".join(f"`{p}`" for p in patterns[start:start + 5]))
    if domain["default_path_rules"] is not None:
        lines.append("Explicit rules win over directory defaults; named legacy gaps remain unresolved.")
        for field, label in (("include", "Default include"), ("exclude", "Default exclude")):
            for pattern in domain["default_path_rules"][field]:
                lines.append(f"- {label}: `{pattern}`")
    for package in domain["test_packages"]:
        lines.append(f"- Go test package: `{package}`")
    mechanisms = domain.get("mechanisms") or []
    interpretations_from = domain.get("dependency_interpretations_from") or []
    interpretations_to = domain.get("dependency_interpretations_to") or []
    semantic = bool(mechanisms or interpretations_from or interpretations_to)
    if mechanisms:
        lines.extend(["", "## Mechanisms",
                      "Advisory semantic ownership; the complete enriched references live in the inventory."])
        for mechanism in mechanisms[:10]:
            text = mechanism["responsibility"]
            if len(text) > 96:
                text = text[:96].rstrip() + "…"
            lines.append(f"- `{mechanism['owner_id']}`: {text} "
                         f"(laws {len(mechanism['law_refs'])}, controls {len(mechanism['controls'])}, "
                         f"checks {len(mechanism['check_ids'])}, contracts {len(mechanism['contract_refs'])})")
        if len(mechanisms) > 10:
            lines.append(f"- {len(mechanisms) - 10} more mechanisms: `.concord/navigation/inventory.json`")
    lines.extend(["", "## Entry surfaces", "These are catalog surface entries, not invariant/control or handler joins."])
    verbs = [v["canonical"] + (f" ({v['two_word']})" if v["two_word"] else "") for v in domain["cli_verbs"]]
    for start in range(0, len(verbs), 5):
        lines.append("- CLI: " + ", ".join(f"`{v}`" for v in verbs[start:start + 5]))
    early = domain.get("cli_early_dispatch") or []
    if early:
        lines.append("- CLI early dispatch (accepted before commandSpecs routing): " + ", ".join(f"`{token}`" for token in early))
    operations = domain["agent_operations"]
    for tool in sorted({op.split(".")[0] for op in operations}):
        lines.append(f"- `{tool}`: " + ", ".join(f"`{op.split('.', 1)[1]}`" for op in operations if op.startswith(tool + ".")))
    if not verbs and not operations and not early:
        lines.append("No surface catalog is owned by this Domain; semantic entry-point joins live in the inventory.")
    lines.extend(["", "## Verification references", "Declared repository commands are shared checks, not Domain-specific acceptance or automatic execution.",
                  "Run the narrow selected command with `bin/oc-test targeted -- <command> [args...]`."])
    for tool in domain["checks"]:
        lines.append(f"- `{tool['id']}` ({tool['tier']}): `{tool['invocation']}`")
    if semantic:
        bound = domain.get("bound_entries") or {}
        lines.extend(["", "## Allowed and observed references",
                      "Bindings and interpretations are advisory joins; navigation does not prove dispatch admission at the current workflow step."])
        for catalog, label in (("cli", "CLI entries bound"), ("agent", "agent operations bound"), ("workflow", "workflow actions bound")):
            entries = bound.get(catalog) or []
            summary = ", ".join(f"`{entry}`" for entry in entries[:3])
            lines.append(f"- {label}: {len(entries)}" + (f" ({summary}, …)" if len(entries) > 3 else f" ({summary})" if summary else ""))
        for item in interpretations_from[:6]:
            lines.append(f"- Interpretation `{item['kind']}` -> `{item['target_domain_id']}` (advisory, not an import allowlist).")
        if len(interpretations_from) > 6:
            lines.append(f"- {len(interpretations_from) - 6} more from interpretations: `.concord/navigation/inventory.json`")
        for item in interpretations_to[:6]:
            lines.append(f"- Interpretation `{item['kind']}` from `{item['source_domain_id']}` (advisory, not an import allowlist).")
        if len(interpretations_to) > 6:
            lines.append(f"- {len(interpretations_to) - 6} more to interpretations: `.concord/navigation/inventory.json`")
        imports = domain.get("observed_imports") or []
        lines.append(f"- Observed package imports: {len(imports)} distinct paths; package-level only; "
                     "intra-package edges unmeasured; no symbol graph or execution permission.")
        for edge in (domain.get("observed_package_edges") or [])[:3]:
            targets = ", ".join(f"`{target}`" for target in edge["target_domain_ids"])
            lines.append(f"- Observed package edge via `{edge['import_path']}` -> {targets} (advisory).")
        lines.extend(["", "## Not covered here",
                      "Symbol-level call edges, dispatch-admission proof at the current workflow step, CON-887 packet reading,",
                      "and CON-890 owner oracles remain later work. Required-reading entries will be pinned references,",
                      "not inlined card content."])
    else:
        lines.extend(["", "## Not covered by slice A", "Invariant/control joins, allowed-dependency interpretation, symbol-level call edges,",
                      "non-law navigation homes, CON-887 packet reading, and CON-890 owner oracles remain later work.",
                      "Required-reading entries will be pinned references, not inlined card content."])
    text = "\n".join(lines) + "\n"
    if len(text.encode()) > 8192 or len(lines) > 120:
        raise NavigationError(f"card exceeds 8 KiB / 120 lines: {domain['domain_id']}")
    return text


def artifacts(root: Path, *, base_ref: str = "HEAD") -> dict[str, bytes]:
    registry = read_json(root, REGISTRY)
    data = inventory(root, registry, base_ref=base_ref)
    result = {f"{OUTPUT}/inventory.json": (json.dumps(data, indent=2, sort_keys=True) + "\n").encode()}
    result.update({d["card_path"]: card(d).encode() for d in data["domains"]})
    return result
