#!/usr/bin/env python3
"""Shared typed-anchor machinery for evidence-binding validators.

The floor-readiness and law-coverage validators both judge whether a `satisfied`
record is proved rather than asserted. The proof layer is the same in both
planes: typed anchors must resolve, and the executable kinds must be invoked
by a required workflow. Without a single source of truth the two validators
would drift and a record that one validator accepted would be a finding to the
other — the same defect restated in two syntaxes (CD-0047 D3).

What an anchor is:
- `go_test`: a Go test identified as `<package>.<TestName>`; resolves when the
  test is declared in that package. `go test ./...` is a required CI step, so
  package membership is the executability question.
- `scenario`: a corpus scenario id; resolves when the id appears in a corpus
  file under `scenarios/` and nothing in `internal/` defers it. A deferred
  scenario is executed by nothing and accepting it as evidence would assert a
  rule that no test enforces.
- `validator`: a Python checker or harness identified by `scripts/<prefix>-<name>.py`;
  resolves when the script exists and either the required CI workflow invokes
  it directly, or `scripts/check-json.py` nests it. A checker that exists but
  is wired into nothing proves nothing, which is the failure mode this whole
  machinery exists to surface.
- `generated`: a symbol owned by a generated artifact, identified as
  `<path>#<symbol>`; resolves when the symbol appears in a file whose leading
  comment carries the generator marker. Hand-written files carry no such
  guarantee.

The validator anchor pattern widens here to `scripts/(check|test)-*.py` so the
release/install test scripts are legal anchors too. The CI-invocation proof is
unchanged in principle: the script must appear in a required workflow file
(`.github/workflows/ci.yml` or `.github/workflows/release.yml`) or be nested
via `scripts/check-json.py`.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from coverage_state import bounded_text  # noqa: E402

ANCHOR_KINDS = ("go_test", "scenario", "validator", "generated")

GO_TEST_ANCHOR = re.compile(r"^(?P<package>[a-z0-9/_]+)\.(?P<test>Test[A-Za-z0-9_]*)$")
VALIDATOR_ANCHOR = re.compile(r"^scripts/(check|test)-[a-z0-9-]+\.py$")
GENERATED_ANCHOR = re.compile(r"^(?P<file>[A-Za-z0-9./_-]+)#(?P<symbol>[A-Za-z_][A-Za-z0-9_]*)$")

GENERATED_MARKER = "Code generated by"

REQUIRED_WORKFLOWS = (
    ROOT / ".github/workflows/ci.yml",
    ROOT / ".github/workflows/release.yml",
)


def go_test_exists(package: str, test: str) -> bool:
    """A Go test anchor resolves when the named test is declared in that package.

    `go test ./...` is a required CI step and covers every package in the
    module, so package membership is the whole of the executability question
    for this kind — there is no per-package opt-in that could exclude it.
    """
    directory = ROOT / package
    if not directory.is_dir():
        return False
    declaration = re.compile(rf"^func {re.escape(test)}\(", re.MULTILINE)
    return any(
        declaration.search(path.read_text(encoding="utf-8", errors="replace"))
        for path in directory.glob("*_test.go")
    )


DEFERRAL = re.compile(r"""Deferrals\[\s*["'](?P<id>[^"']+)["']\s*\]\s*=""")


def deferred_scenarios() -> set[str]:
    """Scenario ids the corpus harnesses record as deferred rather than bound.

    A deferred scenario sits in the corpus and is executed by nothing. Accepting
    one as evidence would assert a rule that no test enforces — presence
    standing in for enforcement, which is the exact defect this machinery
    exists to surface. Reading the same registry the corpus test reads keeps
    the two answers from diverging.
    """
    found: set[str] = set()
    for path in (ROOT / "internal").rglob("*_test.go"):
        for match in DEFERRAL.finditer(path.read_text(encoding="utf-8", errors="replace")):
            found.add(match.group("id"))
    return found


def collect_ids(value: object) -> set[str]:
    found: set[str] = set()
    if isinstance(value, dict):
        for key, item in value.items():
            if key in {"id", "scenario_id", "scenario"} and isinstance(item, str):
                found.add(item)
            found |= collect_ids(item)
    elif isinstance(value, list):
        for item in value:
            found |= collect_ids(item)
    return found


def scenario_exists(scenario_id: str) -> bool:
    """A scenario anchor resolves when a corpus declares the id and nothing defers it."""
    if scenario_id in deferred_scenarios():
        return False
    directory = ROOT / "scenarios"
    if not directory.is_dir():
        return False
    for path in directory.rglob("*.json"):
        try:
            corpus = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, UnicodeDecodeError, json.JSONDecodeError):
            continue
        if scenario_id in collect_ids(corpus):
            return True
    return False


def validator_runs_in_ci(script: str) -> bool:
    """A validator anchor resolves when a required workflow actually invokes it.

    A checker that exists but is not wired into the required workflow proves
    nothing, which is the failure mode this whole machinery exists to surface.
    Required workflows are `.github/workflows/ci.yml` and
    `.github/workflows/release.yml`; both are documented sources of durable
    authority. `check-json.py` nests several sub-validators, so a nested
    invocation counts as invocation too.
    """
    if not (ROOT / script).is_file():
        return False
    for workflow in REQUIRED_WORKFLOWS:
        if workflow.is_file() and script in workflow.read_text(encoding="utf-8"):
            return True
    nested = ROOT / "scripts/check-json.py"
    return nested.is_file() and script in nested.read_text(encoding="utf-8")


def generated_symbol_exists(file: str, symbol: str) -> bool:
    """A generated anchor resolves when the symbol lives in a generated artifact.

    The artifact must carry the generator marker, because the guarantee being
    cited is that a generator owns the value — a hand-written file with the
    right symbol name carries no such guarantee.
    """
    target = ROOT / file
    if not target.is_file():
        return False
    text = target.read_text(encoding="utf-8", errors="replace")
    if GENERATED_MARKER not in text:
        return False
    return re.search(rf"\b{re.escape(symbol)}\b", text) is not None


def check_anchor(anchor: object, prefix: str, findings: list[str]) -> None:
    if not isinstance(anchor, dict):
        findings.append(f"{prefix}: anchor must be an object")
        return
    if set(anchor) != {"kind", "value"}:
        findings.append(f"{prefix}: anchor must carry exactly kind and value")
        return
    kind, value = anchor["kind"], anchor["value"]
    if kind not in ANCHOR_KINDS:
        findings.append(f"{prefix}: anchor kind must be one of {list(ANCHOR_KINDS)}, got {kind!r}")
        return
    if not bounded_text(value, 3, 512):
        findings.append(f"{prefix}: anchor value must be trimmed text of 3-512 characters")
        return

    if kind == "go_test":
        match = GO_TEST_ANCHOR.fullmatch(value)
        if not match:
            findings.append(f"{prefix}: go_test anchor must read <package>.<TestName>: {value!r}")
        elif not go_test_exists(match.group("package"), match.group("test")):
            findings.append(f"{prefix}: go_test anchor does not resolve: {value!r}")
    elif kind == "scenario":
        if not scenario_exists(value):
            findings.append(f"{prefix}: scenario anchor is in no corpus under scenarios/: {value!r}")
    elif kind == "validator":
        if not VALIDATOR_ANCHOR.fullmatch(value):
            findings.append(
                f"{prefix}: validator anchor must read scripts/(check|test)-<name>.py: {value!r}"
            )
        elif not validator_runs_in_ci(value):
            findings.append(f"{prefix}: validator anchor is not invoked by a required workflow: {value!r}")
    elif kind == "generated":
        match = GENERATED_ANCHOR.fullmatch(value)
        if not match:
            findings.append(f"{prefix}: generated anchor must read <path>#<symbol>: {value!r}")
        elif not generated_symbol_exists(match.group("file"), match.group("symbol")):
            findings.append(f"{prefix}: generated anchor does not resolve to a generated artifact: {value!r}")