#!/usr/bin/env python3
"""Validate and deterministically generate the CD-0017 lane projections."""
from __future__ import annotations

import copy
import hashlib
import importlib.util
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "contracts/agent-lanes.v1.json"
SCHEMA = ROOT / "contracts/agent-lanes.schema.json"
PACKET_SCHEMA = ROOT / "contracts/agent-lane-packet.schema.json"
REPORT_SCHEMA = ROOT / "contracts/agent-lane-report.schema.json"
EVAL_PACKETS = ROOT / "adapter/opencode/evals/packets"

spec = importlib.util.spec_from_file_location("agent_contract_generator", ROOT / "scripts/generate-agent-contracts.py")
if spec is None or spec.loader is None:
    raise RuntimeError("unable to load shared contract helpers")
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
schema_validate = module.schema_validate


def canonical(value: object) -> bytes:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode()


def digest(value: object) -> str:
    return "sha256:" + hashlib.sha256(canonical(value)).hexdigest()


def lane_digest(lane: dict) -> str:
    body = copy.deepcopy(lane)
    body.pop("digest", None)
    return digest(body)


def load_manifest() -> tuple[dict, str]:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
    schema_validate(manifest, schema, schema, "manifest")
    ids = [lane["id"] for lane in manifest["lanes"]]
    if ids != ["research", "implement", "design", "review", "verify"]:
        raise ValueError("lane registry must contain the closed ordered lane set")
    utility_ids = [utility["id"] for utility in manifest["utilities"]]
    if len(set(utility_ids)) != len(utility_ids) or set(ids) & set(utility_ids):
        raise ValueError("utility registry must contain unique ids that do not collide with lanes")
    manifest_digest = digest(manifest)
    for lane in manifest["lanes"]:
        if "digest" in lane:
            raise ValueError("lane digest is generated, not authored")
        lane["digest"] = lane_digest(lane)
    return manifest, manifest_digest


def go_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def go_slice(values: list[str]) -> str:
    return "[]string{" + ", ".join(go_string(value) for value in values) + "}"


def report_projection_constraints(report_schema: dict, lane: dict) -> list[str]:
    properties = report_schema["properties"]
    evidence_entry = report_schema["$defs"]["evidence_entry"]
    return [
        "Report top-level shape: "
        f"type={report_schema['type']}, "
        f"additionalProperties={json.dumps(report_schema['additionalProperties'])}, "
        f"required={json.dumps(report_schema['required'], ensure_ascii=False)}.",
        "schema_version: "
        f"const={json.dumps(properties['schema_version']['const'], ensure_ascii=False)}.",
        "readback_model: "
        f"type={properties['readback_model']['type']}, "
        f"minLength={properties['readback_model']['minLength']}, "
        f"maxLength={properties['readback_model']['maxLength']}, "
        f"pattern={json.dumps(properties['readback_model']['pattern'], ensure_ascii=False)}.",
        "status: "
        f"enum={json.dumps(properties['status']['enum'], ensure_ascii=False)}.",
        "evidence: "
        f"type={properties['evidence']['type']}, "
        f"minItems={properties['evidence']['minItems']}, "
        f"maxItems={properties['evidence']['maxItems']}, "
        f"items={json.dumps(properties['evidence']['items'], ensure_ascii=False)}.",
        "evidence_entry shape: "
        f"type={evidence_entry['type']}, "
        f"additionalProperties={json.dumps(evidence_entry['additionalProperties'])}, "
        f"required={json.dumps(evidence_entry['required'], ensure_ascii=False)}.",
        "evidence_entry.detail: "
        f"type={evidence_entry['properties']['detail']['type']}, "
        f"minLength={evidence_entry['properties']['detail']['minLength']}, "
        f"maxLength={evidence_entry['properties']['detail']['maxLength']}.",
        "evidence_entry.obligation: "
        f"enum={json.dumps(lane['evidence_obligations'], ensure_ascii=False)}.",
    ]


def go_projection(manifest: dict, manifest_digest: str) -> str:
    lines = [
        "// Code generated by scripts/generate-agent-lanes.py; DO NOT EDIT.",
        "package store",
        "",
        "const LaneRegistryManifestDigest = " + go_string(manifest_digest),
        "",
        "var generatedLaneDefinitions = []LaneDefinition{",
    ]
    for lane in manifest["lanes"]:
        b = lane["budgets"]
        lines.extend([
            "\t{",
            f"\t\tID: {go_string(lane['id'])}, Version: {lane['version']}, Digest: {go_string(lane['digest'])},",
            f"\t\tPurpose: {go_string(lane['purpose'])}, CapabilityClass: {go_string(lane['capability_class'])},",
            f"\t\tCapabilities: {go_slice(lane['capabilities'])}, PacketSchemaRef: {go_string(lane['packet_schema_ref'])}, ReportSchemaRef: {go_string(lane['report_schema_ref'])},",
            f"\t\tBudgets:             LaneBudgets{{CostUSDMax: {b['cost_usd_max']}, ContextTokensMax: {b['context_tokens_max']}, TimeSecondsMax: {b['time_seconds_max']}}},",
            f"\t\tEvidenceObligations: {go_slice(lane['evidence_obligations'])}, LifecycleStates: {go_slice(lane['lifecycle_states'])},",
            "\t},",
        ])
    lines.extend(["}", ""])
    return "\n".join(lines)


def ts_projection(manifest: dict, manifest_digest: str, packet_schema: dict, report_schema: dict) -> str:
    report_constraints = {
        lane["id"]: report_projection_constraints(report_schema, lane)
        for lane in manifest["lanes"]
    }
    return """// Code generated by scripts/generate-agent-lanes.py; DO NOT EDIT.
export const laneRegistryManifestDigest = %s as const;
export const agentLanes = %s as const;
export const agentUtilities = %s as const;
export const agentLanePacketSchema = %s as const;
export const agentLaneReportSchema = %s as const;
export const agentLaneReportConstraints = %s as const;
export type AgentLane = (typeof agentLanes)[number];
export type AgentUtility = (typeof agentUtilities)[number];
""" % (json.dumps(manifest_digest), json.dumps(manifest["lanes"], ensure_ascii=False, indent=2), json.dumps(manifest["utilities"], ensure_ascii=False, indent=2), json.dumps(packet_schema, ensure_ascii=False, separators=(",", ":")), json.dumps(report_schema, ensure_ascii=False, separators=(",", ":")), json.dumps(report_constraints, ensure_ascii=False))


def agent_projection(lane: dict, report_schema: dict) -> str:
    agent_name = f"concord-{lane['id']}"
    evidence = ", ".join(f"`{item}`" for item in lane["evidence_obligations"])
    report_properties = report_schema["properties"]
    report_version = json.dumps(report_properties["schema_version"]["const"], ensure_ascii=False)
    report_statuses = ", ".join(f"`{item}`" for item in report_properties["status"]["enum"])
    report_constraints = "\n".join(f"- {item}" for item in report_projection_constraints(report_schema, lane))
    return f"""---
description: Concord {lane['id']} lane — {lane['purpose']}
mode: all
hidden: true
tools:
  task: false
permission:
  task:
    "*": deny
    "general": deny
    "explore": deny
---

# {agent_name}

{lane['purpose']}

This is a bounded Concord worker lane. Follow the supplied `agent-lane-packet.v1`
packet and return only the `agent-lane-report.v1` report for this attempt. Do not
record workflow transitions, verdicts, completion, or spawn nested workers.

Return the report as a single JSON object, and nothing else, as your final
message. Do not include `attempt_id`, `lane_id`, `lane_version`, or
`lane_digest`: the dispatch window owns those fields and any report that
supplies them is refused. Set `schema_version` to `{report_version}`, `readback_model` to
the `provider/model` identifier you are running as, and `status` to one of {report_statuses}.

Report contract constraints:
{report_constraints}

A successful report must carry at least one entry for every obligation below, and may name no other obligation.

Evidence obligations: {evidence}.
"""


UTILITY_TOOL_KEYS = (
    "bash",
    "read",
    "glob",
    "grep",
    "edit",
    "write",
    "patch",
    "morph_edit",
    "task",
    "webfetch",
    "todowrite",
    "skill",
    "execute",
    "question",
    "concord_domain",
    "concord_knowledge",
    "concord_product_view",
    "concord_work_browse",
    "concord_work_compact",
    "concord_work_define",
    "concord_work_initiative",
    "concord_work_relate",
    "concord_work_start",
    "concord_work_trace",
    "concord_work_transition",
    "opencode_mcp_connect",
    "opencode_mcp_disconnect",
)


def utility_projection(utility: dict) -> str:
    tools = [f"  {key}: {'true' if key == 'bash' else 'false'}" for key in UTILITY_TOOL_KEYS]
    permissions = ["    \"*\": deny"] + [f"    \"{command}\": allow" for command in utility["allowed_commands"]]
    minutes, seconds = divmod(utility["time_seconds_max"], 60)
    duration = f"{minutes} minutes" if seconds == 0 else f"{utility['time_seconds_max']} seconds"
    return f"""---
description: Concord {utility['id']} utility — {utility['purpose']}
mode: all
hidden: true
tools:
{chr(10).join(tools)}
permission:
  bash:
{chr(10).join(permissions)}
---

# concord-{utility['id']}

{utility['purpose']}

This is a host utility. Return only the result of the commands. Do not edit a
file, mutate GitHub, retry a failed check, or start another agent.

## Input

The parent gives you a repository and one selector: a PR number, a commit SHA,
or a run id. If it gives you none of these, report `refused` with the reason.
Do not guess a repository from the working directory.

## Loop

1. Read the current state with one command:
   - PR: `gh pr checks <number> --repo <owner/repo> --json name,state,link,bucket`
   - SHA or run id: `gh run list --repo <owner/repo> --commit <sha> --json databaseId,name,status,conclusion,url`
2. If every check is terminal, stop the loop.
3. If any check is queued, pending, or in progress, run `sleep 15`, then repeat
   from step 1.
4. Stop after {duration} of total wall time, or after 120 iterations, whichever
   comes first. Report `timeout` with the last state you read.

Count your iterations. State the count in your report. Never sleep longer than
60 seconds in one command.

## Failure detail

When a check fails, collect its detail before you report:

1. `gh run view <run-id> --repo <owner/repo> --json jobs --jq '.jobs[] | select(.conclusion==\"failure\") | \"\\(.name) \\(.url)\"'`
2. `gh run view <run-id> --repo <owner/repo> --log-failed | tail -80`

Classify each failure as one of: `test_failure`, `build_failure`,
`lint_or_validator`, `infrastructure`, `cancelled`, `unknown`. Quote the first
error line verbatim.

## Report

Return one result with these fields and nothing else:

- `status`: `success`, `failure`, `timeout`, or `refused`
- `sha`: the head commit you watched
- `checks`: total, passing, failing, skipped
- `failures`: one line per failing check, with its job URL, classification, and first error line
- `run_url`: the run or PR URL
- `iterations`: how many times you read the state

Report what the commands returned. Never infer a conclusion you did not read.
"""


def docs_projection(manifest: dict, manifest_digest: str) -> str:
    lines = ["# Concord agent lane registry", "", "<!-- Code generated by scripts/generate-agent-lanes.py; DO NOT EDIT. -->", "", f"Registry digest: `{manifest_digest}`", "", "| Lane | Capability class | Packet | Report |", "|---|---|---|---|"]
    for lane in manifest["lanes"]:
        lines.append(f"| `{lane['id']}` v{lane['version']} | `{lane['capability_class']}` | `{lane['packet_schema_ref']}` | `{lane['report_schema_ref']}` |")
    lines.extend(["", "## Utilities", "", "| Utility | Commands | Wall-time cap |", "|---|---|---|"])
    for utility in manifest["utilities"]:
        commands = ", ".join(f"`{command}`" for command in utility["allowed_commands"])
        lines.append(f"| `{utility['id']}` v{utility['version']} | {commands} | `{utility['time_seconds_max']}s` |")
    lines.extend(["", "Every lane and utility is closed and versioned. Unknown lane identity or digest fails closed before work begins.", ""])
    return "\n".join(lines)


def eval_packet_projection(path: Path, lane_digests: dict[str, str]) -> str:
    packet = json.loads(path.read_text(encoding="utf-8"))
    lane_id = packet.get("lane_id")
    if lane_id not in lane_digests:
        raise ValueError(f"eval packet {path.relative_to(ROOT)} references unknown lane {lane_id!r}")
    packet["lane_digest"] = lane_digests[lane_id]
    return json.dumps(packet, ensure_ascii=False, indent=2) + "\n"


def refresh_knowledge_index() -> None:
    result = subprocess.run(
        [sys.executable, str(ROOT / "scripts/check-knowledge-index.py"), "--update"],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    if result.returncode:
        detail = result.stderr.strip() or result.stdout.strip() or "unknown knowledge-index failure"
        raise ValueError(f"knowledge-index cascade failed: {detail}")


def main() -> int:
    check = "--check" in sys.argv[1:]
    try:
        manifest, manifest_digest = load_manifest()
        packet_schema = json.loads(PACKET_SCHEMA.read_text(encoding="utf-8"))
        report_schema = json.loads(REPORT_SCHEMA.read_text(encoding="utf-8"))
        expected = {
            ROOT / "internal/store/generated_agent_lanes.go": go_projection(manifest, manifest_digest),
            ROOT / "adapter/opencode/generated-agent-lanes.ts": ts_projection(manifest, manifest_digest, packet_schema, report_schema),
            ROOT / "contracts/agent-lanes.digest": manifest_digest + "\n",
            ROOT / "docs/agent-lanes-contract.md": docs_projection(manifest, manifest_digest),
        }
        expected.update({ROOT / ".opencode/agents" / f"concord-{lane['id']}.md": agent_projection(lane, report_schema) for lane in manifest["lanes"]})
        expected.update({ROOT / ".opencode/agents" / f"concord-{utility['id']}.md": utility_projection(utility) for utility in manifest["utilities"]})
        lane_digests = {lane["id"]: lane["digest"] for lane in manifest["lanes"]}
        if EVAL_PACKETS.is_dir():
            expected.update({path: eval_packet_projection(path, lane_digests) for path in sorted(EVAL_PACKETS.glob("*.json"))})
        if check:
            for path, content in expected.items():
                if not path.is_file() or path.read_text(encoding="utf-8") != content:
                    raise ValueError(f"generated lane contract drift: {path.relative_to(ROOT)}")
        else:
            for path, content in expected.items():
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")
            refresh_knowledge_index()
        print(manifest_digest)
        return 0
    except (OSError, json.JSONDecodeError, ValueError) as exc:
        print(f"agent lane generation failed: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
