#!/usr/bin/env python3
"""Project the durable-tier bounds into Go so the producer reads one source.

CD-0069 D1 puts the bounds in `docs/durable-tier-budget.v1.json` once and says no
surface restates them. The detective layer (`scripts/check-durable-tier.py`)
reads that file directly. The producer cannot: it runs inside a published binary
against an operator's knowledge home, which is not this repository and does not
carry this repository's budget.

Generating the constants is what keeps both surfaces on one number. A Go literal
typed by hand would be a restatement, and CI would not notice when the two
diverged. This generator is checked in the same workflow step as the vocabulary
generators, so a budget edit that is not regenerated fails.
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BUDGET = ROOT / "docs/durable-tier-budget.v1.json"
TARGET = ROOT / "internal/store/generated_durable_tier_budget.go"


def go_projection(budget: dict) -> str:
    return f'''// Code generated by scripts/generate-durable-tier-budget.py; DO NOT EDIT.
package store

// Durable-tier bounds projected from docs/durable-tier-budget.v1.json. CD-0069
// D1 keeps them in that file alone; scripts/check-durable-tier.py reads it
// directly and the producer reads these, so both surfaces enforce one number.
const (
\t// maxDurableNoteBytes bounds the whole serialized note. CD-0002 calls the
\t// artifact a page, not a state dump.
\tmaxDurableNoteBytes = {budget["max_note_bytes"]}
\t// maxDurableFencedJSONBytes bounds any single fenced JSON block inside a
\t// note. A note that carries a large embedded document has stopped
\t// distilling and started serializing.
\tmaxDurableFencedJSONBytes = {budget["max_fenced_json_bytes"]}
)
'''


def main() -> int:
    try:
        budget = json.loads(BUDGET.read_text(encoding="utf-8"))
        if budget.get("schema_version") != "1.0":
            raise ValueError("durable tier budget schema_version must be 1.0")
        for key in ("max_note_bytes", "max_fenced_json_bytes"):
            value = budget.get(key)
            if not isinstance(value, int) or isinstance(value, bool) or value <= 0:
                raise ValueError(f"{key} must be a positive integer")
        content = subprocess.run(
            ["gofmt"], input=go_projection(budget), text=True, capture_output=True, check=True
        ).stdout
        if "--check" in sys.argv[1:]:
            if not TARGET.is_file() or TARGET.read_text(encoding="utf-8") != content:
                print(f"generated durable-tier budget drift: {TARGET.relative_to(ROOT)}", file=sys.stderr)
                return 1
        else:
            TARGET.write_text(content, encoding="utf-8")
        print(f"durable tier bounds: {budget['max_note_bytes']}/{budget['max_fenced_json_bytes']}")
        return 0
    except (OSError, json.JSONDecodeError, ValueError, subprocess.CalledProcessError) as exc:
        print(f"durable tier budget generation failed: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
