#!/usr/bin/env python3
"""Validate and deterministically generate the CD-0017 lane projections."""
from __future__ import annotations

import copy
import hashlib
import importlib.util
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "contracts/agent-lanes.v1.json"
SCHEMA = ROOT / "contracts/agent-lanes.schema.json"
PACKET_SCHEMA = ROOT / "contracts/agent-lane-packet.schema.json"

spec = importlib.util.spec_from_file_location("agent_contract_generator", ROOT / "scripts/generate-agent-contracts.py")
if spec is None or spec.loader is None:
    raise RuntimeError("unable to load shared contract helpers")
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
schema_validate = module.schema_validate


def canonical(value: object) -> bytes:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode()


def digest(value: object) -> str:
    return "sha256:" + hashlib.sha256(canonical(value)).hexdigest()


def lane_digest(lane: dict) -> str:
    body = copy.deepcopy(lane)
    body.pop("digest", None)
    return digest(body)


def load_manifest() -> tuple[dict, str]:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
    schema_validate(manifest, schema, schema, "manifest")
    ids = [lane["id"] for lane in manifest["lanes"]]
    if ids != ["research", "implement", "review", "verify"]:
        raise ValueError("lane registry must contain the closed ordered lane set")
    manifest_digest = digest(manifest)
    for lane in manifest["lanes"]:
        if "digest" in lane:
            raise ValueError("lane digest is generated, not authored")
        lane["digest"] = lane_digest(lane)
    return manifest, manifest_digest


def go_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def go_slice(values: list[str]) -> str:
    return "[]string{" + ", ".join(go_string(value) for value in values) + "}"


def go_projection(manifest: dict, manifest_digest: str) -> str:
    lines = [
        "// Code generated by scripts/generate-agent-lanes.py; DO NOT EDIT.",
        "package store",
        "",
        "const LaneRegistryManifestDigest = " + go_string(manifest_digest),
        "",
        "var generatedLaneDefinitions = []LaneDefinition{",
    ]
    for lane in manifest["lanes"]:
        b = lane["budgets"]
        lines.extend([
            "\t{",
            f"\t\tID: {go_string(lane['id'])}, Version: {lane['version']}, Digest: {go_string(lane['digest'])},",
            f"\t\tPurpose: {go_string(lane['purpose'])}, CapabilityClass: {go_string(lane['capability_class'])},",
            f"\t\tCapabilities: {go_slice(lane['capabilities'])}, PacketSchemaRef: {go_string(lane['packet_schema_ref'])}, ReportSchemaRef: {go_string(lane['report_schema_ref'])},",
            f"\t\tBudgets:             LaneBudgets{{CostUSDMax: {b['cost_usd_max']}, ContextTokensMax: {b['context_tokens_max']}, TimeSecondsMax: {b['time_seconds_max']}}},",
            f"\t\tEvidenceObligations: {go_slice(lane['evidence_obligations'])}, LifecycleStates: {go_slice(lane['lifecycle_states'])},",
            "\t},",
        ])
    lines.extend(["}", ""])
    return "\n".join(lines)


def ts_projection(manifest: dict, manifest_digest: str, packet_schema: dict) -> str:
    return """// Code generated by scripts/generate-agent-lanes.py; DO NOT EDIT.
export const laneRegistryManifestDigest = %s as const;
export const agentLanes = %s as const;
export const agentLanePacketSchema = %s as const;
export type AgentLane = (typeof agentLanes)[number];
""" % (json.dumps(manifest_digest), json.dumps(manifest["lanes"], ensure_ascii=False, indent=2), json.dumps(packet_schema, ensure_ascii=False, separators=(",", ":")))


def agent_projection(lane: dict) -> str:
    agent_name = f"concord-{lane['id']}"
    evidence = ", ".join(f"`{item}`" for item in lane["evidence_obligations"])
    return f"""---
description: Concord {lane['id']} lane — {lane['purpose']}
mode: subagent
tools:
  task: false
permission:
  task:
    "*": deny
    "general": deny
    "explore": deny
---

# {agent_name}

{lane['purpose']}

This is a bounded Concord worker lane. Follow the supplied `agent-lane-packet.v1`
packet and return only the `agent-lane-report.v1` report for this attempt. Do not
record workflow transitions, verdicts, completion, or spawn nested workers.

Evidence obligations: {evidence}.
"""


def docs_projection(manifest: dict, manifest_digest: str) -> str:
    lines = ["# Concord agent lane registry", "", "<!-- Code generated by scripts/generate-agent-lanes.py; DO NOT EDIT. -->", "", f"Registry digest: `{manifest_digest}`", "", "| Lane | Capability class | Packet | Report |", "|---|---|---|---|"]
    for lane in manifest["lanes"]:
        lines.append(f"| `{lane['id']}` v{lane['version']} | `{lane['capability_class']}` | `{lane['packet_schema_ref']}` | `{lane['report_schema_ref']}` |")
    lines.extend(["", "Every lane is closed and versioned. Unknown lane identity or digest fails closed before work begins.", ""])
    return "\n".join(lines)


def main() -> int:
    check = "--check" in sys.argv[1:]
    try:
        manifest, manifest_digest = load_manifest()
        packet_schema = json.loads(PACKET_SCHEMA.read_text(encoding="utf-8"))
        expected = {
            ROOT / "internal/store/generated_agent_lanes.go": go_projection(manifest, manifest_digest),
            ROOT / "adapter/opencode/generated-agent-lanes.ts": ts_projection(manifest, manifest_digest, packet_schema),
            ROOT / "contracts/agent-lanes.digest": manifest_digest + "\n",
            ROOT / "docs/agent-lanes-contract.md": docs_projection(manifest, manifest_digest),
        }
        expected.update({ROOT / ".opencode/agents" / f"concord-{lane['id']}.md": agent_projection(lane) for lane in manifest["lanes"]})
        if check:
            for path, content in expected.items():
                if not path.is_file() or path.read_text(encoding="utf-8") != content:
                    raise ValueError(f"generated lane contract drift: {path.relative_to(ROOT)}")
        else:
            for path, content in expected.items():
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")
        print(manifest_digest)
        return 0
    except (OSError, json.JSONDecodeError, ValueError) as exc:
        print(f"agent lane generation failed: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
