#!/usr/bin/env python3
"""Validate and deterministically generate work-kind projections."""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

from vocabulary_utils import check_schema_keywords, digest, fail, schema_validate


ROOT = Path(__file__).resolve().parents[1]
VOCABULARY = ROOT / "contracts/work-kinds.v1.json"
SCHEMA = ROOT / "contracts/work-kinds.schema.json"


def go_strings(values: list[str]) -> str:
    return ", ".join(json.dumps(value) for value in values)


def go_projection(vocabulary: dict) -> str:
    kinds = vocabulary["kinds"]
    maps = {
        "workKindStored": {item["kind"]: item["stored"] for item in kinds},
        "workKindFoldCreate": {item["kind"]: item["fold_create"] == "allowed" for item in kinds},
        "workKindFoldRevise": {item["kind"]: item["fold_revise"] == "allowed" for item in kinds},
        "workKindAgentCapture": {item["kind"]: item["agent_capture"] == "allowed" for item in kinds},
    }
    map_text = "\n\n".join(
        "var " + name + " = map[string]bool{\n" +
        "".join(f"\t{json.dumps(key)}: {str(value).lower()},\n" for key, value in sorted(values.items())) +
        "}"
        for name, values in maps.items()
    )
    refusals = "\n".join(
        "\t" + json.dumps(item["kind"]) + ": {Message: " +
        json.dumps(item["refusal"]["message"]) + ", Recovery: " +
        json.dumps(item["refusal"]["recovery"]) + "},"
        for item in sorted(kinds, key=lambda value: value["kind"])
        if "refusal" in item
    )
    return f'''// Code generated by scripts/generate-work-kinds.py; DO NOT EDIT.
package store

{map_text}

type workKindRefusal struct {{
\tMessage  string
\tRecovery string
}}

var workKindRefusals = map[string]workKindRefusal{{
{refusals}
}}

func WorkKindStored(kind string) bool {{
\treturn workKindStored[kind]
}}

func WorkKindFoldCreateAllowed(kind string) bool {{
\treturn workKindFoldCreate[kind]
}}

func WorkKindFoldReviseAllowed(kind string) bool {{
\treturn workKindFoldRevise[kind]
}}

func WorkKindAgentCaptureAllowed(kind string) bool {{
\treturn workKindAgentCapture[kind]
}}

func WorkKindRequiresDedicatedOperation(kind string) bool {{
\treturn workKindStored[kind] && !workKindFoldRevise[kind]
}}

func WorkKindRefusalFor(kind string) (message, recovery string, ok bool) {{
\trefusal, ok := workKindRefusals[kind]
\tif !ok {{
\t\treturn "", "", false
\t}}
\treturn refusal.Message, refusal.Recovery, true
}}
'''


def main() -> int:
    try:
        vocabulary = json.loads(VOCABULARY.read_text(encoding="utf-8"))
        schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
        check_schema_keywords(schema)
        schema_validate(vocabulary, schema, schema, "vocabulary")
        kinds = vocabulary["kinds"]
        names = [item["kind"] for item in kinds]
        if len(set(names)) != len(names):
            fail("work kinds must be unique")
        if any(item["stored"] and item["fold_create"] == "refused" for item in kinds):
            fail("stored work kinds must allow fold create")
        vocabulary_digest = digest(vocabulary)
        expected = {
            ROOT / "internal/store/generated_work_kinds.go": subprocess.run(
                ["gofmt"], input=go_projection(vocabulary), text=True, capture_output=True, check=True
            ).stdout,
            ROOT / "contracts/work-kinds.digest": vocabulary_digest + "\n",
        }
        if "--check" in sys.argv[1:]:
            for path, content in expected.items():
                if not path.is_file() or path.read_text(encoding="utf-8") != content:
                    fail(f"generated work kinds drift: {path.relative_to(ROOT)}")
        else:
            for path, content in expected.items():
                path.parent.mkdir(exist_ok=True)
                path.write_text(content, encoding="utf-8")
        print(vocabulary_digest)
        return 0
    except (OSError, json.JSONDecodeError, ValueError, subprocess.CalledProcessError) as exc:
        print(f"work-kind generation failed: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
