#!/usr/bin/env python3
"""Validate and deterministically generate native-run status projections."""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

from vocabulary_utils import check_schema_keywords, digest, fail, schema_validate


ROOT = Path(__file__).resolve().parents[1]
VOCABULARY = ROOT / "contracts/native-run-statuses.v1.json"
SCHEMA = ROOT / "contracts/native-run-statuses.schema.json"


def go_projection(vocabulary: dict) -> str:
    phases = vocabulary["phases"]
    pairs = {
        phase["phase"]: {status["status"]: status["failure"] for status in phase["statuses"]}
        for phase in phases
    }
    phase_text = "\n".join(
        f'\t{json.dumps(phase)}: {{' + " ".join(
            f'{json.dumps(status)}: {str(failure).lower()},' for status, failure in sorted(statuses.items())
        ) + "},"
        for phase, statuses in sorted(pairs.items())
    )
    return f'''// Code generated by scripts/generate-native-run-statuses.py; DO NOT EDIT.
package store

var nativeRunStatuses = map[string]map[string]bool{{
{phase_text}
}}

func NativeRunStatusAllowed(phase, status string) bool {{
\t_, ok := nativeRunStatuses[phase][status]
\treturn ok
}}

func NativeRunStatusIsFailure(phase, status string) bool {{
\treturn nativeRunStatuses[phase][status]
}}
'''


def main() -> int:
    try:
        vocabulary = json.loads(VOCABULARY.read_text(encoding="utf-8"))
        schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
        check_schema_keywords(schema)
        schema_validate(vocabulary, schema, schema, "vocabulary")
        phases = vocabulary["phases"]
        phase_names = [phase["phase"] for phase in phases]
        if len(set(phase_names)) != len(phase_names):
            fail("native run phases must be unique")
        for phase in phases:
            statuses = [item["status"] for item in phase["statuses"]]
            if len(set(statuses)) != len(statuses):
                fail(f"native run statuses must be unique within phase {phase['phase']}")
        vocabulary_digest = digest(vocabulary)
        expected = {
            ROOT / "internal/store/generated_native_run_statuses.go": subprocess.run(
                ["gofmt"], input=go_projection(vocabulary), text=True, capture_output=True, check=True
            ).stdout,
            ROOT / "contracts/native-run-statuses.digest": vocabulary_digest + "\n",
        }
        if "--check" in sys.argv[1:]:
            for path, content in expected.items():
                if not path.is_file() or path.read_text(encoding="utf-8") != content:
                    fail(f"generated native-run statuses drift: {path.relative_to(ROOT)}")
        else:
            for path, content in expected.items():
                path.parent.mkdir(exist_ok=True)
                path.write_text(content, encoding="utf-8")
        print(vocabulary_digest)
        return 0
    except (OSError, json.JSONDecodeError, ValueError, subprocess.CalledProcessError) as exc:
        print(f"native-run status generation failed: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
