#!/usr/bin/env python3
"""Validate and deterministically generate relation vocabulary projections."""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

from vocabulary_utils import check_schema_keywords, digest, fail, schema_validate

ROOT = Path(__file__).resolve().parents[1]
VOCABULARY = ROOT / "contracts/relation-vocabulary.v1.json"
SCHEMA = ROOT / "contracts/relation-vocabulary.schema.json"


def go_projection(vocabulary: dict) -> str:
    kinds = vocabulary["kinds"]
    stored = sorted(kind["kind"] for kind in kinds)
    identity_events = sorted({event for kind in kinds for event in kind["written_by"]})
    addressable = sorted(kind["kind"] for kind in kinds if kind["link"] in {"allowed", "refused"})
    refusals = {
        kind["kind"]: kind["link_refusal"]
        for kind in kinds
        if kind["link"] == "refused"
    }
    transitive = sorted(kind["kind"] for kind in kinds if kind["transitive"])
    labels = {}
    defaults = sorted(kind["kind"] for kind in kinds)
    for kind in kinds:
        name = kind["kind"]
        labels[name] = (name, name, False)
        if kind["inverse_label"] is not None:
            labels[kind["inverse_label"]] = (kind["inverse_label"], name, True)

    def go_strings(values):
        return ", ".join(json.dumps(value) for value in values)

    refusal_entries = "\n".join(
        f'\t{json.dumps(name)}: {{Message: '
        + json.dumps(value["message"])
        + ", Recovery: "
        + json.dumps(value["recovery"])
        + "},"
        for name, value in sorted(refusals.items())
    )
    label_entries = "\n".join(
        f'\t{json.dumps(label)}: {{label: '
        + json.dumps(spec[0])
        + ", stored: "
        + json.dumps(spec[1])
        + ", invert: "
        + str(spec[2]).lower()
        + "},"
        for label, spec in sorted(labels.items())
    )
    addressable_entries = "\n".join(f'\t{json.dumps(kind)}: true,' for kind in addressable)
    transitive_entries = "\n".join(f'\t{json.dumps(kind)}: true,' for kind in transitive)
    return f'''// Code generated by scripts/generate-relation-vocabulary.py; DO NOT EDIT.
package store

var relationStoredKinds = []string{{{go_strings(stored)}}}

var relationIdentityEventKinds = []string{{{go_strings(identity_events)}}}

var relationKinds = map[string]bool{{
 {addressable_entries}
}}

type relationLinkRefusal struct {{
	Message  string
	Recovery string
}}

var relationLinkRefusals = map[string]relationLinkRefusal{{
{refusal_entries}
}}

var relationTransitiveKinds = map[string]bool{{
 {transitive_entries}
}}

var relationQueryLabels = map[string]relationSpec{{
{label_entries}
}}

var relationDefaultQueryLabels = []string{{{go_strings(defaults)}}}
'''


def main() -> int:
    try:
        vocabulary = json.loads(VOCABULARY.read_text())
        schema = json.loads(SCHEMA.read_text())
        check_schema_keywords(schema)
        schema_validate(vocabulary, schema, schema, "vocabulary")
        kinds = vocabulary["kinds"]
        names = [kind["kind"] for kind in kinds]
        labels = names + [kind["inverse_label"] for kind in kinds if kind["inverse_label"] is not None]
        if len(set(names)) != len(names):
            fail("relation kinds must be unique")
        if len(set(labels)) != len(labels):
            fail("relation query labels must be unique")
        vocabulary_digest = digest(vocabulary)
        expected = {
            ROOT / "internal/store/generated_relation_vocabulary.go": subprocess.run(
                ["gofmt"], input=go_projection(vocabulary), text=True, capture_output=True, check=True
            ).stdout,
            ROOT / "contracts/relation-vocabulary.digest": vocabulary_digest + "\n",
        }
        if "--check" in sys.argv[1:]:
            for path, content in expected.items():
                if not path.is_file() or path.read_text() != content:
                    fail(f"generated relation vocabulary drift: {path.relative_to(ROOT)}")
        else:
            for path, content in expected.items():
                path.parent.mkdir(exist_ok=True)
                path.write_text(content)
        print(vocabulary_digest)
        return 0
    except (OSError, json.JSONDecodeError, ValueError, subprocess.CalledProcessError) as exc:
        print(f"relation vocabulary generation failed: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
