#!/usr/bin/env python3
"""Validate and deterministically generate the lane-step dispatch join."""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

from vocabulary_utils import check_schema_keywords, digest, fail, schema_validate


ROOT = Path(__file__).resolve().parents[1]
JOIN = ROOT / "contracts/lane-step-dispatch.v1.json"
SCHEMA = ROOT / "contracts/lane-step-dispatch.schema.json"
LANES = ROOT / "contracts/agent-lanes.v1.json"


def go_projection(join: dict) -> str:
    rows = []
    for binding in sorted(join["bindings"], key=lambda value: value["capability_class"]):
        kinds = "".join(json.dumps(kind) + ", " for kind in binding["step_kinds"])
        rows.append(f"\t{json.dumps(binding['capability_class'])}: {{{kinds}}},")
    table = "var laneStepDispatchKinds = map[string][]string{\n" + "\n".join(rows) + "\n}"
    manifest_digest = digest(join)
    return f'''// Code generated by scripts/generate-lane-step-dispatch.py; DO NOT EDIT.
package store

// LaneStepDispatchManifestDigest pins the authored join contract this
// projection was generated from: contracts/lane-step-dispatch.v1.json.
const LaneStepDispatchManifestDigest = "{manifest_digest}"

// laneStepDispatchKinds maps one agent-lane capability class to the workflow
// step kinds at which a lane of that class may be dispatched. The map is the
// single authority both definition composition and dispatch-time validation
// read; neither may hard-code a step kind a binding does not name.
{table}
'''


def main() -> int:
    try:
        join = json.loads(JOIN.read_text(encoding="utf-8"))
        schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
        check_schema_keywords(schema)
        schema_validate(join, schema, schema, "join")
        classes = [binding["capability_class"] for binding in join["bindings"]]
        if len(set(classes)) != len(classes):
            fail("capability classes must be unique")
        if classes != sorted(classes):
            fail("bindings must be sorted by capability_class")
        lanes = json.loads(LANES.read_text(encoding="utf-8"))
        lane_classes = sorted({lane["capability_class"] for lane in lanes["lanes"]})
        if sorted(classes) != lane_classes:
            fail(
                "the join must name exactly the capability classes contracts/agent-lanes.v1.json carries: "
                f"join={sorted(classes)} lanes={lane_classes}"
            )
        expected = {
            ROOT / "internal/store/generated_lane_step_dispatch.go": subprocess.run(
                ["gofmt"], input=go_projection(join), text=True, capture_output=True, check=True
            ).stdout,
            ROOT / "contracts/lane-step-dispatch.digest": digest(join) + "\n",
        }
        if "--check" in sys.argv[1:]:
            for path, content in expected.items():
                if not path.is_file() or path.read_text(encoding="utf-8") != content:
                    fail(f"generated lane-step dispatch join drift: {path.relative_to(ROOT)}")
        else:
            for path, content in expected.items():
                path.parent.mkdir(exist_ok=True)
                path.write_text(content, encoding="utf-8")
        print(digest(join))
        return 0
    except (OSError, json.JSONDecodeError, ValueError, subprocess.CalledProcessError) as exc:
        print(f"lane-step dispatch generation failed: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
